### ISSUE TITLE
BeforeMap() and AfterMap() not invoked on collection mappings

### ISSUE THREAD

**Issue by MrPerun** [AutoMapper/AutoMapper#1019]
The AfterMap/BeforeMap isn't invoked for collections. Here is an example:

Mapper.CreateMap&lt;Address, AddressDto&gt;();
using (var ctx = new AdventureWorksEntities())
{
    // OK:
    var addressesX = Mapper.Map&lt;AddressDto&gt;(ctx.Addresses.First(), o => o.AfterMap((src, dest) => { /* do XXX */ }));
    // AfterMap not invoked:
    var addressesY = Mapper.Map&lt;AddressDto[]&gt;(ctx.Addresses.ToArray(), o => o.AfterMap((src, dest) => { /* do YYY */ }));
}

Here the first AfterMap - /* do XXX */ - is invoked, but the second, which is used in array mapping for AddressDto[] isn't invoked: /* do YYY */.

**Comment by lbargaoanu** [comment]
You can simply write the code before/after calling Map :)

**Comment by jbogard** [comment]
Yeah, what's the use case here? What are you doing inside that before/after?

**Comment by MrPerun** [comment]
OK, you're true, I can simply do the "after map" code after calling the Mapper.Map(), so the AfterMap() method doesn't have use useless for me. So the question is why the AfterMap method is there in Mapper.Map()?

**Comment by jbogard** [comment]
Honestly don't remember. This is still a bug, however.

**Comment by lbargaoanu** [comment]
Things [are not](https://github.com/AutoMapper/AutoMapper/issues/674) what they [used to be](https://github.com/AutoMapper/AutoMapper/issues/503) :) So now the hooks don't work as initially designed and don't look that useful anymore.
@jbogard If you still want to fix this, it doesn't seem simple. I presume the hook calls are [inside the mapper](https://github.com/AutoMapper/AutoMapper/blob/5074996e9bb391fc82ae25fe7b069a61f3b1d7fd/src/AutoMapper/Mappers/TypeMapObjectMapperRegistry.cs#L90) in order to have access to the destination object. It's easy enough to fix this for the enumerable mapper. But what about the rest? We could simply fix each one when we get a complaint (hoping few people will :)). Or solve it for all the mappers. But I think this would require extending the existing mappers with a GetDestinationValue method.

**Comment by jbogard** [comment]
One possible fix is to remove the calls deep inside the mappers and put it all the way back at the top of MappingEngine.Map.

**Comment by lbargaoanu** [comment]
Yes, but you don't have the destination. That's what I was getting at.

**Comment by jbogard** [comment]
Not fixing for now.

**Comment by Oxymoron290** [comment]
how come?

**Comment by lbargaoanu** [comment]
@Oxymoron290 A PR is welcome.

**Comment by jonathh21** [comment]
Just stumbled onto this whilst trying to verify a mapping was completed with the AfterMap. It doesn't get called. Sad times.

**Comment by lbargaoanu** [comment]
AfterMap is called for each element in the collection, as it should. Maybe you need to upgrade.

**Comment by jonathh21** [comment]
It may be because I am using ProjectTo actually.

Don't think we are due an upgrade..

**Comment by lbargaoanu** [comment]
I think you might want to try to understand what ProjectTo actually does. Of course it's not called then.

**Comment by jonathh21** [comment]
Stand down fella.

Hadn't fully appreciated that ProjectTo was used and my googling for it not
working took me here.

To save future weary travellers from any ire:
http://docs.automapper.org/en/stable/Queryable-Extensions.html

Cheers all.
