### ISSUE TITLE
Feature request: AfterMap support for QueryableExtensions

### ISSUE THREAD

**Issue by MrPerun** [AutoMapper/AutoMapper#1030]
Hello,
I know AfterMap is working with queryable extensions inside automapper Profile. That's great. But I'd like to define AfterMap at execution phase. Something like:
```
Mapper.CreateMap<Address, AddressDto>()
	.ForMember(t => t.TestProperty, opt => opt.Ignore())
public class GetAddressListOperation
{	
	public void IQueryable<AddressDto> GetQuery()
	{
		using (var ctx = new MyEntities())
		{
			var myOperation = new MyOperation();
			var addresses = ctx.Addresses
				.UseAsDataSource()
				.For<AddressDto>()
				.AfterMap((src, dest) => dest.TestProperty = myOperation.ComputeSomething());
			return addresses;
		}
	}
}
```
My motivation for this is based on my opinion that mapping code defined in Profiles or in Mapper.CreateMap shouldn't contain business logic. The business logic should be placed inside business operations (business layer). E.g. things like evaluation of access permissions, eshop discounts, postal fees, etc. As well  as I propagate the entities from data layer thru business layer to UI using kendo grid and the mapper, I'd like to define the business code in the business operations, as you can see in the sample.

Is something like that supported or do you plan to add support for this?

**Comment by TylerCarlson1** [comment]
Currently this isn't supported with `UseAsDataSource()`.  With `ProjectTo<>()` there's [Parameterization] (https://github.com/AutoMapper/AutoMapper/wiki/Queryable-Extensions#parameterization) where you can inject myOperation into the mapper to configure before mappings are called.  It's set up for Member maps, but I'm not 100% sure it's works for AfterMap.  In your example you can do 
```
MyOperation myOperation = null;
Mapper.CreateMap<Address, AddressDto>()
.ForMember(t => t.TestProperty, opt => opt.MapFrom(s => myOperation.ComputeSomething()))
```
and `ProjectTo<>(myOperation)` to pass in the business logic into the mapper at run time.
One of the discussion items of updating `UseAsDataSource()` was to put features of `ProjectTo()` into there, since it calls it at the base.

As far as adding an AfterMap after initialization, that was never an intended scenario.  It should be configured once at start up and never modified again.  The parameterization allows you to inject business logic into the mapper at run time.

**Comment by jbogard** [comment]
Yep, you want parameterization. AfterMap would be very, very weird to do for the queryable stuff, since I just create a LINQ Select expression. I'd have to create a query provider, wrap the existing query provider, and do something custom afterwards. To me that violates the principle of least surprise since you can't easily see what is happening there, and you're modifying stuff *after* the base queryable has run. I just don't see how to make it work easily.
