### ISSUE TITLE
Multiple calls to AfterMap for bidirectional relationships

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#105]
<b>claes[CodePlex]</b><br />When you have entities with bidirectional relationships &#40;e.g. parent&#47;child&#41; and specify an AfterMap handler, that handler gets invoked multiple times. Only the last call is actually &#42;after&#42; the mapping. The previous calls happens when AutoMapper finds the object in its cache and are before the mapping is complete, meaning some of the properties are not yet mapped. <br /><br />This feels like a bug to me. If you add a BeforeMap handler it&#39;s only invoked once as expected.<br /><br />I&#39;ve attached a modified version of the BidirectionalRelationships.cs unit test to show this behaviour<br /><br />Moving the AfterMap call from TypeMapMapper.Map to TypeMapObjectMapperRegistry.Map &#40;i.e same place that BeforeMap is called&#41; seems to solve the problem. All other tests still pass after doing that change.

**Comment by mtomas-mpm** [comment]
I'm having this problem in a mapping (older version 2.1.267.0), sometimes woks and sometimes doesn't work and only in production, so I haven't found a test case to reproduce the bug and I'm not  sure that the upgrade will solve my bug because the comment of the solution is a bit confusing: "to execute less often"...

For the moment I've applied the workaround suggested here: http://blog.shadowmoses.co.uk/2012/05/automapper-21-aftermap-fires-multiple.html

I hope to test the application with the new version soon...

Thanks,

Marc.

**Comment by oliwa19** [comment]
This issue is still unresolved. AfterMap is firing multiple times in v3.3.1.

**Comment by jccounihan** [comment]
+1. I am still getting AfterMap being called multiple times in v3.3.1.

**Comment by oliwa19** [comment]
My issue was related to my IOC container setting multiple bindings so essentially I had the same object mapped multiple times.
