### ISSUE TITLE
Asp.net MVC 5 Migrating from static API

### ISSUE THREAD

**Issue by cirpitch** [AutoMapper/AutoMapper#1068]
Hello!
In Global.asax I create config:
`var config = new MapperConfiguration(cfg => {
                cfg.AddProfile<DomainToViewModelMappingProfile>();
                cfg.AddProfile<ViewModelToDomainMappingProfile>();
                cfg.CreateMap<ApplicationUser, UserDataModel>();
            });`
How to use mapping in controllers?

**Comment by jbogard** [comment]
https://github.com/AutoMapper/AutoMapper/wiki/Migrating-from-static-API

**Comment by cirpitch** [comment]
I read this manual/
But I do not understand how to use mapping in the controller.

**Comment by cirpitch** [comment]
Sorry for disturbing.
Working.

**Comment by fnascimento00** [comment]
You can set an example of dependency injection with Autofac?

**Comment by poshea** [comment]
I concur with cirpitch.  No good examples for setup and use of version 4.2 anywhere.  Can you,  please, provide working example?  Thank you for your consideration.

**Comment by jbogard** [comment]
@poshea the entire wiki is the version 4.2 configuration. You can also look at https://github.com/jbogard/contosouniversity for how I use this in apps with a DI container.

It's almost exactly the same. Instead of Mapper.CreateMap, use var config = new MapperConfiguration(cfg => cfg.CreateMap); and instead of Mapper.Map use a mapper instance, config.CreateMapper() and call mapper.Map. It's instances instead of static.

**Comment by jbogard** [comment]
Static API is back.
