### ISSUE TITLE
Mapping error since 4.2.0 (mapping null Version to Version)

### ISSUE THREAD

**Issue by sickboy** [AutoMapper/AutoMapper#1108]
~~~
.ForMember(x => x.GameVer,
                    opt => opt.ResolveUsing(src => GetVersion(src.GetSettingOrDefault("gamever"))))
~~~

When GetSettingsOrDefault returns null, GetVersion also returns null, and then leads to the following error:

~~~
AutoMapper.AutoMapperMappingException
Message:
    Missing type map configuration or unsupported mapping.
    
    Mapping types:
    Object -> Version
    System.Object -> System.Version
    
    Destination path:
    Server.GameVer.GameVer
    
    Source value:
    (null)
Source: AutoMapper
~~~

**Comment by sickboy** [comment]
Is this related to #1088 ?

**Comment by lbargaoanu** [comment]
Looks like it. Try the MyGet build.

**Comment by RichardLee1001** [comment]
Upgraded 1 day ago via nuget and still this problem persists? Any release fix in sight?

**Comment by lbargaoanu** [comment]
This can be closed.

**Comment by mcartoixa** [comment]
So if I want this bug solved, I have to update to a beta version of the next major release?!

**Comment by jbogard** [comment]
Yes. To be clear, the "next major release" is because the public API changed. The same ~1000 tests have been running for years. Beta because since one of the targets is RC2, I have to mark the package as pre-release.

This is very common for libraries following semantic versioning - the major releases are about API changes, the minor releases are about new features.
