### ISSUE TITLE
AssertConfigurationIsValid Fails to Detect Missing Properties of Mappings Created Using ReverseMap

### ISSUE THREAD

**Issue by hereiznoy** [AutoMapper/AutoMapper#1128]
`AssertConfigurationIsValid` is failing to detect missing properties on maps created using `ReverseMap`. 

For example:

    class Thing
    {
        public string Name { get; set; }
        public int Value { get; set; }
    }

    class ThingDto
    {
        public string Name { get; set; }
    }

    var config = new MapperConfiguration(cfg => cfg.CreateMap<Thing, ThingDto>().ReverseMap());

    // This should detect (at least it's my expectation that it should detect) that the ThingDto->Thing type    
    // map doesn't have a mapping for the Value property of Thing. But it doesn't.
    config.AssertConfigurationIsValid();

I believe the culprit is the `MappingExpression.CreateReverseMapExpression` method.

    protected virtual MappingExpression<TDestination, TSource> CreateReverseMapExpression()
    {
        return new MappingExpression<TDestination, TSource>(MemberList.Source, DestinationType, SourceType);
    }

I'm thinking `MemberList.Source` should be `MemberList.Destination`.

**Comment by lbargaoanu** [comment]
#940?

**Comment by hereiznoy** [comment]
OK, yeah same issue. My bad, I had only searched open issues.

My assumption here was that `IMappingExpression<A, B>.ReverseMap()` would be equivalent to `IMappingExpression<B, A>`. But the intention for `ReverseMap` I guess is more specific to the source mapping.

**Comment by eddiegroves** [comment]
:+1:  I've hit this as well, and I'm not sure how #940 resolves it? Is it just not supported behavior? I'm missing something here :p

**Comment by jbogard** [comment]
No it's not the same as just CreateMap. It inherits some of the ignores, and it assumes that the members you still want to assert are on the original destination type. This is all by design, by default it's MemberList.Source. If you don't want that behavior, don't use ReverseMap.

If you imagine going from a Model -> DTO -> Model, you only care about the DTO not matching, so the direction of member assertions reverses. I can make the documentation more explicit about this (although the described scenario doesn't really make sense to me).
