### ISSUE TITLE
NamingConvention for source and destination

### ISSUE THREAD

**Issue by mc0re** [AutoMapper/AutoMapper#1142]
I am currently using AutoMapper 3.3.1, so bear with me if this was changed in a later version.

When I saw, that there were both _Source_ and _Destination_ naming conventions, I thought that they could be used to level the naming differences between objects, such that a Pascal-cased property could be mapped to/from lower-cased. But this showed to be untrue.

The way it works is that it uses _Destination_ naming convention object's `SplittingExpression` to split the destination property name into parts, and then it uses _Source_ naming convention's `SeparatorCharacter` (which, funny enough, is a string :-) ) to merge the parts. _Destination_'s `SeparatorCharacter` and _Source_'s `SplittingExpression` are blutantly ignored.

This made it untrivial to map e.g. a source property `PersonClass_Id` into `PersonClassId`, for the source property name is never modified. What I did as a workaround is I split on the "Id" ending, but this is a hack.

What I would expect for this to work is that before actual string comparison, both property names are split and merged in accordance with their naming conventions.

**Comment by jbogard** [comment]
Well that's....odd

**Comment by mc0re** [comment]
What's ...odd? :-)
If the behaviour - I checked it in the source code, and added the following test case to verify.

```c#
public class DataSource
{
	public string lowerCase { get; set; }

	public string PascalCase { get; set; }

	public string PascalCase_Id { get; set; }

}


public class DataDest
{
	public string LowerCase { get; set; }

	public string PascalCase { get; set; }

	public string PascalCaseId { get; set; }
}


class RemoveUnderscoreNamingConvention : INamingConvention
{ 
	private static readonly Regex SplitRegex = new Regex(@"(.+ (?= Id) | Id)", RegexOptions.IgnorePatternWhitespace);

	public string SeparatorCharacter => "_";

	public Regex SplittingExpression => SplitRegex;
}


public class When_mapping_with_underscore_naming_conventions : AutoMapperSpecBase
{
	private DataSource mSrc;
	private DataDest mDest;

	protected override void Establish_context()
	{
		Mapper.Initialize(cfg =>
		{
			cfg.CreateProfile("MyMapperProfile", prf =>
			{
				prf.SourceMemberNamingConvention = new RemoveUnderscoreNamingConvention();
				prf.DestinationMemberNamingConvention = new RemoveUnderscoreNamingConvention();
				prf.CreateMap<DataSource, DataDest>();
			});
		});
	}


	[Fact]
	public void All_members_are_mapped()
	{
		Mapper.AssertConfigurationIsValid();
	}


	protected override void Because_of()
	{
		mSrc = new DataSource { PascalCase_Id = "foo"};
		mDest = Mapper.Map<DataDest>(mSrc);
	}


	[Fact]
	public void Source_is_okay()
	{
		mSrc.PascalCase_Id.ShouldEqual("foo");
	}


	[Fact]
	public void Should_map_with_underscore()
	{
		mDest.PascalCaseId.ShouldEqual("foo");
	}
}
```

**Comment by jbogard** [comment]
The existing behavior is odd is what I meant. I don't think it was intentional.

**Comment by TylerCarlson1** [comment]
Well you don't have a PascalAndLowerUnderscoreNamingConvention in Automapper so it's not that odd when you look at it.  The assumption is it's either PascalNaming or underscores with lower case, not a mixture of the two.  If you were going to assume both you would have to change Source and Destination member configurations to be a list instead of a single item, and go through both of them when splitting up the names.  You can't make 1 working instance of them because underscore needs _ as separator character while pascal doesn't have one and you can't differentiate the two.

**Comment by mc0re** [comment]
It's not both in one class, it's pascal in one (destination) and underscore (sometimes) in another (source). If the source was adhering to the `SourceMemberNamingConvention`, I could've created a `NamingConvention` that splits on underscore but then joins with `String.Empty`, then this would've matched the pascal case (as the actual string comparison is case-insensitive).

**Comment by TylerCarlson1** [comment]
"sometimes" meaning not all the time.  AutoMapper assumes you keep the naming convention consistent and "PascalCase_Id" is a mix of Pascal and underscore naming conventions so there's no way AutoMapper can map it one way or the other.
This is also used for splitting names up to do flattening.  If you do this the way you have now, then only underscores will be split up for flattening.  Pascal can never be used.

So in order to make this scenario work AutoMapper would need a MemberNamingConvention list for source and destination.  And you would add both Pascal and Underscore naming conventions.  Then when you split and rejoin all the text you would have to do every possibly combination of every NamingConvention you have in your list.

This should be able to be supported in AutoMapper if you add a list.

As far as the last line in your original post.  It splits down the source's value using it's own naming convention and it re-assembles it using the destinations's naming convention.  So it converts PascalCaseId to pascal_case_id when one is PascalName and the other is Underscore.

**Comment by mc0re** [comment]
My point is that AutoMapper shouldn't make assumptions when I (as a user) can provide the knowledge. I expected Automapper to use the NamingConvention members to split the names according to the rules I could provide, and then flattern / compare. If I decide I need to use both underscores and Pascal case, I can do it with my own rule, no need for a list of rules :-)

Actually, in this scenario AutoMapper doesn't need the SeparationCharacter member - just the two splitting rules, get the arrays and compare their elements would be enough.

**Comment by TylerCarlson1** [comment]
Right now it compares complete strings with separator characters.  If you want to do it by comparing elements elements in an array @jbogard accepts pull requests.
