### ISSUE TITLE
Is there any roadmap to support default constructor : `new MapperConfiguration()`

### ISSUE THREAD

**Issue by hungdoan2** [AutoMapper/AutoMapper#1208]
After update from 3.3.1 to `4.2.1` : 

> Mapper.CreateMap is still obsolete and I will kill it with fire.

It's great to hear that `Mapper.CreateMap is still obsolete` .
But I got a trouble.
There is 2 solution to create a map: 
1. Use `Profile Instances`
2. Use `MapperConfiguration`

**Options 1** : Great, but I can't apply it. Because my object has already inherited from another class. 
=> My current solution for last 1 years is implement an interface like this: 
```C#
public class MyViewModel : IAutoMapperConfigure
{
	public void AutoMapperInitialize()
	{
		Mapper.CreateMap<MyModel, MyViewModel>();
	}
}
```
and when application start, I just call `AutoMapperInitialize`. But I can't apply any more if Mapper.CreateMap is removed

**Options 2**: Fine, but I don't want to centralize the configuration like that.

## My question: 
1.Is there any roadmap to support default constructor : `new MapperConfiguration()`
Then I can do some thing like: 
```C#
var config = new MapperConfiguration();
config.CreateMap<MyModel, MyViewModel>();
```

2.Is there any roadmap to support `IMapperProfile` instead of `Profile` for `Profile Instances`

**Comment by jbogard** [comment]
For number 1, not right now, because I have to configure everything in one go. HOWEVER, you can pass in the `IMapperConfiguration` to your methods:

```
public void AutoMapperInitialize(IMapperConfiguration config) {
    config.CreateMap<MyModel, MyViewModel>();
}
```

The reason I have to keep it in a constructor at the moment is that I need to gather and apply the configuration essentially in one step. The alternative is to do something like forcing you to call CreateMapper that seals the configuration, or breaks this into 3 different objects.
