### ISSUE TITLE
ProjectTo<T> failing with dynamic properties on the target object

### ISSUE THREAD

**Issue by crmckenzie** [AutoMapper/AutoMapper#1258]
Given: 

        public class Widget
        {
            public int WidgetId { get; set; }
        }

        public class WidgetJson
        {
            public int WidgetId { get; set; }
            public object Urls { get; set; }
        }

        public MapperConfiguration Config { get; set; }

        [OneTimeSetUp]
        public void BeforeAll()
        {
            this.Config = new MapperConfiguration(cfg =>
            {
                object Urls = null;
                cfg.CreateMap<Widget, WidgetJson>()
                    .ForMember(output => output.Urls, map => map.MapFrom(src => Urls));
            });

        }

        [Test]
        public void Widgets()
        {
            var widgets = Builder<Widget>
                .CreateListOfSize(10)
                .Build()
                ;

            var urls = new { Urls = new { Edit = "edit" } };
            Expression<Func<WidgetJson, object>> map = config => urls;

            var query = widgets.AsQueryable()
                .ProjectTo<WidgetJson>(this.Config, urls)
                ;

            var results = query.ToList();

            var result = query.First();
            result.Urls.ShouldNotBe(null);
        }

This test passes as written. However, if I change the type of Widget.Urls from object to dynamic:

        public class WidgetJson
        {
            public int WidgetId { get; set; }
            public dynamic Urls { get; set; }
        }

The test will fail.

Further, if I try to use the Expression<Func<T, object>> parameter to ProjectTo<> instead of a constant value, the test will not pass regardless of the type of the Urls property.

**Always Fails**

        [Test]
        public void Widgets()
        {
            var widgets = Builder<Widget>
                .CreateListOfSize(10)
                .Build()
                ;

            var urls = new { Urls = new { Edit = "edit" } };
            Expression<Func<WidgetJson, object>> map = config => urls;

            var query = widgets.AsQueryable()
                .ProjectTo<WidgetJson>(this.Config, map)
                ;

            var results = query.ToList();

            var result = query.First();
            result.Urls.ShouldNotBe(null);
        }

It's possible that I'm misusing the Expression in this case. I was unable to find any examples either in the documentation or in the code. Are there constraints on the Expression that are not visible?

The use-case I'm trying to satisfy is to create hypermedia links in json contracts from data retrieved over an odata api.

**Sample Use Case**

	private object MapUrls(WidgetJson widget)
	{
		dynamic urls = new ExpandoObject();

		urls.edit = Url.Link("Default",
			new { Controller = "Widgets", Action = "Edit", id = widget.Id });
		urls.details = Url.Link("Default",
			new { Controller = "Widgets", Action = "Details", id = widget.Id });

		return new { Urls = urls };
	}

Thoughts?

**Comment by TylerCarlson1** [comment]
The problem is with parameters most likely is when you pass Urls it's of type URL and not of type dynamic, so there's no way to link them together.

Passing the Expression doesn't work to my knowledge, just have to have types you pass in match exactly what is used in the map from functions.

With expression you want to pass it over, but maybe as a function, you need to change `object Urls = null;` to `Func<WidgetJson, object> Urls = null;` and set using `.ForMember(output => output.Urls, map => map.MapFrom(src => Urls(src)));`

That way don't deal with Dynamic and directly and still work with matching concrete types.  Could even do `Func<WidgetJson, dynamic>` and might work as well.

**Comment by TylerCarlson1** [comment]
Actually passing a Func or Expression would possibly cause different problems with the ORM, because it won't know how to translate like it can with a constant.

**Comment by crmckenzie** [comment]
> The problem is with parameters most likely is when you pass Urls it's of type URL and not of type dynamic, so there's no way to link them together.

They're strings in my original code, but your point is well taken. That said, if the target property type is dynamic, I would expect the default behavior to be to simply assign the source property value to the target property. I have a workaround for my other issues, but I still think it would be nice if dynamic was supported in AutoMapper.

**Comment by TylerCarlson1** [comment]
One thing I have to ask about that is does the ORM support dynamic as well?  Because if it doesn't support dynamic with Select statement then there's no point in adding it to ProjectTo because doesn't achieve anything.

If you do a Select Statement setting the dynamic property to constant string does the ORM handle it fine in code?
For example does something like example below work with the ORM.
```
var urls = "url string";
var widgets = db.widgets.Select(w => new WidgetJson { WidgetId = w.WidgetId, Urls = urls }).ToList();
```

If so it's shouldn't be too hard to add dynamic into parameter replacement I would imagine.  Maybe you can PR and @jbogard can add it.

**Comment by crmckenzie** [comment]
In context it shouldn't matter what the ORM supports. The [documentation](https://github.com/AutoMapper/AutoMapper/wiki/Queryable-Extensions) on queryable extensions implies that you can do this (see the section on parameterization).

Re: PR - I have my hands pretty full trying to revive NBuilder so it might be awhile, but if it hasn't been picked up when I get my time back I'll be happy to work on it.

**Comment by TylerCarlson1** [comment]
Ok I got to check this back home, and it does work as intended.  You just can't use Should on dynamics.  It defaults to trying to use dynamic call instead of the extension method.  The test even clearly states this, but my first thought was it's something with mapping.  By casting the result to the type you can make the test pass.

So what you could do for your legit test is
`((Url)result.Urls.edit).ShouldNotBeNull();`

**Comment by crmckenzie** [comment]
Okay, I feel silly. It didn't occur to me that the problem might be in the Assertion library. D'oh!

Last question: do you have any idea what the overload of ProjectTo<T> that takes an Expression<Func<T, object>> is intended to be used for?

**Comment by TylerCarlson1** [comment]
Says members to expend.  My best guess would be it's like EF's Include Statement.  I've never used it myself

**Comment by jbogard** [comment]
Yep, it's meant for OData scenarios, where you want to explicitly decide which members to expand in the Select.
