### ISSUE TITLE
Disable Automatically Mapping Values

### ISSUE THREAD

**Issue by smurfster** [AutoMapper/AutoMapper#1269]
Hi,

Is there a way of disabling the automatic mapping. I'm mapping between domain/database and Data Transfer objects and there is are considerable naming difference's between the two. I would love to use the fluent syntax in automapper to manually map them.

**Comment by jbogard** [comment]
Why are you using AutoMapper? It's for Auto-Mapping. Not for Manual-Mapping. For Manual-Mapping just use manual mapping code.

**Comment by smurfster** [comment]
simply put

1. Multiple mapping instances (restful api versions)
2. Child types are mapped based on there specific mapping config  e.g. Person.Addresses
3. Supports mapping lists
4. I would simply be recreating what automapper already does (without the auto part)

**Comment by jbogard** [comment]
The Auto part is just "names match". If your names don't match, the configuration required for AutoMapper more verbose than manual mapping, `ForMember(dest => dest.Foo, opt => opt.MapFrom(src => src.Bar))` vs `dest.Foo = src.Bar`.

This is a very difficult question to answer without seeing actual source/destination types. Turning off auto-mapping is just weird, that means "don't map when you see the same name on both sides". Otherwise you have your normal ForMember/MapFrom/Ignore stuff that's been in there for ages.

Also something that works well for mapping collections, is LINQ's Select.

**Comment by huancz** [comment]
Would it be possible to reopen this issue if I have more clearly described use case? Situation I'm dealing with: current project has some very strict rules on discoverability. If I use "find all references" on source object property, I must be able to see everywhere it's used. It's acceptable to use second search when I see it's being mapped somewhere else (LINQ-based mapper wouldn't fare any better after all), but the mapping must be explicit (main reason as I understand it is so that new programmers can get into the project easily and orient themselves). So, the "auto" part is straight out for me. Even if source and destination property names are the same, I would like AssertConfigurationIsValid to throw if they don't have explicit mapping. "cfg.ShouldMapProperty = (x) => false;" doesn't help me here, that's more like setting "ignore" on all properties that aren't manually mapped.

Even if "automapper without auto" feels weird, it still brings:

1 - easily deal with subcollections and navigation properties
2 - ProjectTo&lt;Type&gt; for linq2sql
3 - impossible to miss null check when flattening navigation properties - both now and in future when the source class changes
4 - I can can still use auto mapping for quick prototype during development, just mustn't forget to create explicit map before commiting the code
5 - ability to check that I didn't forget to map any of the destination fields. Or later during maintenance, loudly complain if anyone adds new destination field and forgets to add corresponding mapping

Of the above, 1 and 2 are more or less easily solvable with LINQ based mapping. Rest would require replicating almost all of the internal magic that AutoMapper already has. As a workaround I have come up with this:

```c#
    public class NoAutoNamingMapper : IParentSourceToDestinationNameMapper
    {
        public ICollection<ISourceToDestinationNameMapper> NamedMappers => new ISourceToDestinationNameMapper[] { };
        public IGetTypeInfoMembers GetMembers => null;
        public MemberInfo GetMatchingMemberInfo(TypeDetails typeInfo, Type destType, Type destMemberType, string nameToSearch)
        {
            return null;
        }
    }

    public void ConfigureAutomapper()
    {
        AutoMapper.Mapper.Initialize(cfg =>
        {
            cfg.CreateMissingTypeMaps = false;
            cfg.CreateProfile("no-auto-naming", profile =>
            {
                ((AutoMapper.Profile)profile).DefaultMemberConfig.MemberMappers.Clear();
                ((AutoMapper.Profile)profile).DefaultMemberConfig.NameMapper = new NoAutoNamingMapper();
                // profile.CreateMap<...> calls
            }
            // cfg.CreateMap<...> during development where auto behaviour is acceptable
        }
    }
```

I tested this for a while and it seems to work exactly like I need... Only the need to typecast interface to implementation type feels like a brittle hack that may break without warning in future versions, and that I'm messing with AM internals way more than what was intended. And having to create my own dummy name mapper class doesn't feel right either when automapper could just check for null.

I didn't find anything comparable in the "manual mapper" category, and it should be pretty small change in automapper itself that will expand possible use cases without breaking anything. Expose DisableAllConventions on IProfileExpression that does the above in implementation, and add check for null on .NameMapper. Or internal dummy implementation of IParentSourceToDestinatioNameMapper if it makes more sense.

**Comment by TylerCarlson1** [comment]
@huancz No that's more or less how you do it.  I changed it so you can disable things like flattening and also add additional rules if you wanted.  I don't think I made it easy to get rid of the matching name type, but that will work.  Was suppose to use [Member Configurations](https://github.com/AutoMapper/AutoMapper/wiki/Conventions#member-configuration) to edit stuff like that but removing the basic name mapping IDK.  Maybe clearing out the MemberMappers after adding member configuration will get rid of name match mapping.

It was intentionally designed to eliminate the Auto Parts of mapping if you really wanted to.

**Comment by huancz** [comment]
Thank you. I looked at the member configuration you linked. It looks promising if I want to specify my own rules on top of default ones, but I think it's somewhat misleading. Only place where member config is really used is TypeMapFactory.MapDestinationPropertyToSource which will try all member configs until one is able to perform the mapping. AddMemberConfiguration() does start with blank slate, but there will always be earlier MemberConfiguration instance with .AddMember&lt;NameSplitMember&gt; already applied that will satisfy most mapping requests. Just calling AddMemberConfig won't turn off flattening, or anything else. Or did I miss anything? (I did try running quick sample code to verify my assumptions, just adding empty "AddMemberConfiguration()" doesn't assert that invalid configuration is invalid, but it wouldn't be the first time that I interpret what the code is doing wrong). Any way to replace default MemberConfig with something else is blocked by at least internal (assembly) access.

But when reading through linked wiki and related pages I noticed I could just subclass my own Profile which does have access to at least the DefaultMemberConfig - without need to downcast anything. And after bit of trial/error I noticed that I don't even need dummy IParentSourceToDestinationNameMapper if I clear some things.

For anyone that lands here in the future - the code to get rid of the "auto" part of AutoMapper:

```c#
    public class NoAutoNamingProfile : AutoMapper.Profile
    {
        public NoAutoNamingProfile()
        {
            this.DefaultMemberConfig.MemberMappers.Clear();
            this.DefaultMemberConfig.NameMapper.NamedMappers.Clear();

            this.CreateMap<...>();
        }
    }

    private void ConfigureAutomapper()
    {
        AutoMapper.Mapper.Initialize(cfg =>
        {
            cfg.CreateMissingTypeMaps = false;
            cfg.AddProfile<NoAutoNamingProfile>();
        });
    }
```

I think this doesn't even look like a hack anymore, and profiles are better for project structure anyway.

**Comment by mrdnote** [comment]
PS Another advantage of mapping all members in AutoMapper is keeping track of references to those members. The properties that are normally AutoMapper are not showing as referenced members e.g. in VS' code lens.

**Comment by jbogard** [comment]
Then seriously don’t use AutoMapper in this case. It doesn’t add any value.

**Comment by mrdnote** [comment]
It does, it reminds you when you missed mapping a property :)

**Comment by zachsawcs** [comment]
Fail first, fail fast, fail loudly.
