### ISSUE TITLE
Consider Configuring Debug/Diagnostics Expressions

### ISSUE THREAD

**Issue by Mike-EEE** [AutoMapper/AutoMapper#1285]
This is in regards to https://github.com/AutoMapper/AutoMapper/issues/1067#issuecomment-220161054

Performance has been improved greatly, however expressions still retain additional information for debugging purposes, which impacts performance. This issue would make this configurable.  By turning off debug information, expressions would contain less information and compile/run faster.

**Comment by jbogard** [comment]
So it turns out the performance improvements for this are very minimal. Pretty much not worth the effort.

Additional perf improvements would be gained by removing actual features, something I'm not really too keen on. Here's where the perf looks like today:

![image](https://cloud.githubusercontent.com/assets/104498/15685222/647a0f46-2730-11e6-9368-ccc09e2ab1fc.png)

5x slower, I'm OK with that.

**Comment by TylerCarlson1** [comment]
@jbogard Those stats are they just simple maps or does it cover more complicated scenarios?  Like lists, objects within objects, ect?

**Comment by jbogard** [comment]
More complicated scenarios, lists and arrays.
