### ISSUE TITLE
Add new maps to an existing mapper

### ISSUE THREAD

**Issue by gpcaretti** [AutoMapper/AutoMapper#1323]
As per user group I am opening this as a improvement request.

Let's suppose I have a mapper initialized somewhere in this way:

```
Mapper.Initialize(cfg => {
    cfg.CreateMap<Foo, Bar>();
    cfg.AddProfile<FooProfile>();
});
```

Is it possible to add new maps to it or to reinitialize it by adding new maps? For example:

```
Mapper.Initialize(cfg => {
    cfg.CreateMap<NewFoo, NewBar>();
    cfg.AddProfile<NewFooProfile>();
    // here I get the old maps and profiles
    cfg.CreateMaps(Mapper.GetOriginalMaps());      // ???
    cfg.AddProfiles(Mapper.GetOriginalProfiles()); // ???
});

```

**Comment by TylerCarlson1** [comment]
You could make [Conventions](https://github.com/AutoMapper/AutoMapper/wiki/Conventions) that will automatically make new maps based on criteria you set, and you can also add conventions for mapping properties to each other.

**Comment by jbogard** [comment]
You can do this via the new configuration expression model:

```

var baseMappings = new MapperConfigurationExpression();
baseMappings.CreateMap<Foo, Bar>();
baseMappings.AddProfile<FooProfile>();

var config = new MapperConfiguration(baseMappings);
IMapper mapper = new Mapper(config);

// later
baseMappings.CreateMap<NewFoo, NewBar>();
config = new MapperConfiguration(baseMappings);
mapper = newMapper(config);


```

I don't allow this via the static part because I'm trying to encourage initializing once. If you need more dynamic config, use the instance based version.

**Comment by Soruk** [comment]
Hello Jimmy.

I saw similar post about this issue [here](https://groups.google.com/forum/#!msg/automapper-users/nNSxNv_UfVw/Ne2FSE-gAgAJ)
And I want to know if there is a way (or will be) to add statically multiple mapping configurations of mappers without erasing the previous configuration.
Today, I wanted to migrate fro version 4 to  5 and as there is no direct method CreateMap on Mapper class, I tried to use Mapper.Initialize() but it erases previous configuration. Using version 4, I could bypass this using Mapper.Configuration but with the version 5 it is not possible.
The problem is, that we have multiple  classes / methods of mapper configuration and it is not possible in simple way to pass an instance of given MapperConfigurationExpression as an argument to all methods.

Thanks in advance for your response.

Aleksander.

**Comment by gpcaretti** [comment]
This is exactly my issue too.

Il 20 ott 2016 5:36 PM, "Soruk" <notifications@github.com> ha scritto:

**Comment by jbogard** [comment]
There's a really straightforward way to do this. Put your configuration in Profiles. In AutoMapper, add all the Profile types (or in the latest, you can just pass in the assemblies or marker types to search for profiles).

**Comment by jbogard** [comment]
See the docs on how to do this:

https://github.com/AutoMapper/AutoMapper/wiki/Configuration#assembly-scanning-for-auto-configuration

You shouldn't add maps after the fact, really ever. You only call Mapper.Initialize once, and that's it. Use profiles and you're set.

**Comment by rocifier** [comment]
What if I don't have access to the original Mapper which was initialized? In my case a 3rd party library is using Automapper and calling Initialize() once, yet I find myself wanting to use Automapper as well.

**Comment by TylerCarlson1** [comment]
@rocifier You can go instance based mapper and make your own IMapper and then pass that around independent of the other mapper you use.  If it's not using static then you could use that as well.

**Comment by mohitmadaan** [comment]
Hello
We were using automapper 3.0 and now upgraded to 6.2.1. There are few problems we are facing while converting the design of application because configure() method is no more exists after 5.0. I am sharing the existing structure of application and the conversion we have made as per definition.

Current we were using:
 public class OptionMapping : Profile
    {
         protected override void Configure()
              {
                     CreateMap<AddAuditedEntityRequest, AuditedEntity>()
                           .ForMember(d => d.AuditUserId, o => o.MapFrom(s => s.AuditUserId))
                           .ForMember(d => d.EntityIdentifier, o => o.MapFrom(s => s.EntityIdentifier))
                           .ForMember(d => d.EntityType, o => o.MapFrom(s => s.EntityType.ToString()))
                           .ForMember(d => d.Id, o => o.Ignore())
                           .ForMember(d => d.LogTime, o => o.ResolveUsing(v => DateTime.Now))
                           .ForMember(d => d.Details, o => o.MapFrom(s => s.Fields));
     }
}
Now we have modified this and creating map in the constructor of the class.
 public class OptionMapping : Profile
    {
        public OptionMapping()
        {
             CreateMap<AddAuditedEntityRequest, AuditedEntity>()
                           .ForMember(d => d.AuditUserId, o => o.MapFrom(s => s.AuditUserId))
                           .ForMember(d => d.EntityIdentifier, o => o.MapFrom(s => s.EntityIdentifier))
                           .ForMember(d => d.EntityType, o => o.MapFrom(s => s.EntityType.ToString()))
                           .ForMember(d => d.Id, o => o.Ignore())
                           .ForMember(d => d.LogTime, o => o.ResolveUsing(v => DateTime.Now))
                           .ForMember(d => d.Details, o => o.MapFrom(s => s.Fields));
        }
    }

We are initializing and adding classes to profile in a static initialize method and calling the function while creating a service host of a wcf service. In our project structure we have five class libraries with different name spaces and we are adding profile mapping for each of them in the initialize method of service host.

Existing method we were using in auto mapper version 3.0 is: 

public static class Mapping
       {
              public static void Initialize()
              {
                     var automapperProfiles = typeof(Mapping).Assembly.GetTypes()
                           .Where(type => type.IsSubclassOf(typeof(Profile)));

                     foreach (var automapperProfile in automapperProfiles)
                     {
                           Mapper.AddProfile((Profile)Activator.CreateInstance(automapperProfile));
                     }
              }
       }

Now as per new structure  to consume version 6.2.1 we are converting this into:

 public static void Initialize()
        {
            var automapperProfiles = typeof(Mapping).Assembly.GetTypes()
              .Where(type => type.IsSubclassOf(typeof(Profile)));

            Mapper.Initialize(cfg =>
            {
                foreach (var automapperProfile in automapperProfiles)
                {
                    cfg.AddProfile(automapperProfile);
                }
            });
         }

Now we are facing problem in other dependent project that are referencing to a web application in which mapper is already initialized.

how to use the already initialize mapper in other class libraries in the same domain.

-Mohit

**Comment by lbargaoanu** [comment]
See [this](http://docs.automapper.org/en/stable/Configuration.html). You should call some AddProfiles overload once when your app initializes.

**Comment by jbogard** [comment]
Also, you've got a lot of explicit member mappings when the properties are exactly the same. You shouldn't have to do that.
