### ISSUE TITLE
Inline sub map expressions

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#1377]
When a type map has a member that itself is a type map, today we go through a process of calling the ResolutionContext.Map method.

For most cases we probably don't need this. ResolutionContext.Map should be reserved when it needs to determine the mapping strategy at runtime.

I think we do this with a sort of two-pass mapping. We leave placeholder expressions in the tree, then the second pass fills in the placeholders with inlined calls for child maps, or with a regular context mapping call.

We could probably start simple, not worry about inheritance or collection stuff.

This is now where I see the bulk of time spent in the profiling.

**Comment by TylerCarlson1** [comment]
I think inheritance would be the first, otherwise tests won't work.  In which case what you have to do is put all the conditions into a single SUPER expression that conditions all the inherited types and then compiles all the mapping expressions.

Funny thing is if you do this, then there's even more performance gain from something else.  At this point when you search for mapping function, you don't need to know the object types for Generic map calls because the function will take care of that for you.  And from there you don't need to make MapRequest or a new TypeMap saving time there.  Also it might make sense to go back to my `TypeMap<TSource,TDest>` static class idea, so you don't have to search a possibly big dictionary to find the expression.

**Comment by TylerCarlson1** [comment]
Oh yea and the two pass sample isn't going to be any good I think because what you would want is to pass the inline expression over and replace parameters, but you can't do it cause there's the create map part.  If you were going to implement it without fixing inheritance problem all you would be doing is replacing ResolutionContext.Map with an expression doing the same thing, providing little performance gain.  And when you do resolve the inheritance problem you will remove all that expression code with a simple ReplaceParameters call.

That's what I think.  I could be overly complicating things as well.  Happened [before](https://github.com/AutoMapper/AutoMapper/pull/1353) :)
