### ISSUE TITLE
StackOverflowException related to CreateMissingTypeMaps and AddConditionalObjectMapper

### ISSUE THREAD

**Issue by khorvat** [AutoMapper/AutoMapper#1422]
This issue was discussed in the #1398 but here is some background:

_I just upgraded a large app from 3.3.1 that has few thousands types, scattered across modules etc. In 3.3.1 I had lazy CreateMap custom functionality that was automatically creating maps for me. After the upgrade I had to remove that auto create map functionality and now I don't have many CreateMap calls. I tried to use CreateMissingTypeMaps and I get StackOverflowException, I have created configuration and all profiles are loaded, when I hit first Map I get the StackOverflowException._

Here is the [gist](https://gist.github.com/khorvat/70007d92dad3abd89420835a23ee7bdb) for this issue. In both cases I get StackOverflowException while this is working in 4.2.1 (I have updated the gist with the _PreserveReferences_ proposal)

I have tried to use @TylerCarlson1 [suggestion](https://github.com/AutoMapper/AutoMapper/issues/1398#issuecomment-229840694) and set _PreserveReferences_ in _cfg.ForAllMaps()_ and it's still returning _StackOverflowException_.

@TylerCarlson1 proposed a feature request to modify TypeMap after it's generated by AddConditionalObjectMapper/CreateMissingTypeMaps so could this be an option ?

**Comment by TylerCarlson1** [comment]
Actually after running the gist, the stack overflow exception is not caused from PreserverReferences.

It's cause CreateMissingTypeMaps is trying to create maps that have a circular dependency on each other is the problem.

UsersInRole gets TypeMap created, but while creating it tries to create Role TypeMap, and that tries to create UsersInRole which gets it in an infinite loop at configuration.

PreserverReferences isn't getting set for CreateMissingTypeMaps, so that still needs to be fixed.

**Comment by TylerCarlson1** [comment]
@khorvat try the MyGet build.  PerserveReferences = true should work for new type maps from convention or CreateMissingTypeMaps
