### ISSUE TITLE
Calling ForMember with open generics throws NullRef

### ISSUE THREAD

**Issue by simsod** [AutoMapper/AutoMapper#1427]
Repro: 

```
using AutoMapper;

namespace ConsoleApplication3 {
    class Program {
        static void Main(string[] args) {
            Mapper.Initialize(mapper => {
                mapper.CreateMap(typeof(Foo<>), typeof(Bar<>))
                .ForMember("C", to => to.MapFrom("A"))
                .ForMember("D", to => to.MapFrom("B"));
            });
        }
    }

    public class Foo<T> {
        public int A { get; set; }
        public int B { get; set; }
    }

    public class Bar<T> {
        public int C { get; set; }
        public int D { get; set; }
    }
}
```

If the property names are the same, i.e no need for ForMember calls it works as expected.
Automapper 5.0.0
.net 4.5.2

**Comment by lbargaoanu** [comment]
A workaround is to use non-generic base interfaces and customize that map, which you would include in the generic map. Hopefully that would work :)

**Comment by jbogard** [comment]
When do you see this exception?

**Comment by karl-sjogren** [comment]
The exception is thrown after the lambda passed into `Initialize()` has finished.

**Comment by karl-sjogren** [comment]
After some digging the exception is thrown here: 

https://github.com/AutoMapper/AutoMapper/blob/37f9d5682a91e119cca4326bbcabc5b1a0b92841/src/AutoMapper/TypeMap.cs#L236

This part is easily fixed by using `string.Equals` instead of `Name.Equals`.

```
(pm => string.Equals(pm.DestinationProperty.Name, destinationProperty.Name));
```

It doesn't solve the problem however which falls back to the type `NulloMemberGetter`being assigned to the property map but without being setup in any way. It's properties are readonly and it has no constructor.

https://github.com/AutoMapper/AutoMapper/blob/37f9d5682a91e119cca4326bbcabc5b1a0b92841/src/AutoMapper/Execution/MemberGetter.cs#L24

Adding a short constructor that sets `Name` and `MemberType` gets around this and I can actually map stuff, it doesn't however care about the customized member mappings. This test "seems to work", but it's just because we map `A` from `A`.

```
[Fact]
public void Can_map_explicit_members() {
    var config = new MapperConfiguration(cfg => cfg.CreateMap(typeof(Source<>), typeof(Dest<>)).ForMember("A", from => from.MapFrom("A")));

    var source = new Source<int> {
        A = 5
    };

    var dest = config.CreateMapper().Map<Source<int>, Dest<int>>(source);

    dest.A.ShouldEqual(5);
}
```

The following however doesn't, it's still just `A` being mapped to `A`, `Value` is still 0.

```
[Fact]
public void Can_remap_explicit_members() {
    var config = new MapperConfiguration(cfg => cfg.CreateMap(typeof(Source<>), typeof(Dest<>)).ForMember("Value", from => from.MapFrom("A")));

    var source = new Source<int> {
        A = 5
    };

    var dest = config.CreateMapper().Map<Source<int>, Dest<int>>(source);

    dest.Value.ShouldEqual(5);
}
```

And about here I got lost, there is just to much lambda/expression/reflection stuff everywhere to do a "quick dig" into the source..
