### ISSUE TITLE
Auto mapper for JsonPatchDocument

### ISSUE THREAD

**Issue by arielorvits** [AutoMapper/AutoMapper#1576]
How about adding support to map `JsonPatchDocument<A>` to `JsonPatchDocument<B>` ? 
Can we expect something like this in the future? thanks!

**Comment by lbargaoanu** [comment]
It seems to contain a list of operations, try mapping that instead.

**Comment by lbargaoanu** [comment]
Just to be clear, AutoMapper is a generic mapper, so you just need to see how this particular case maps :) to what it can do. There is no special support for Json in AM. You just map it as any other object.

**Comment by arielorvits** [comment]
WOW! cool :)
`CreateMap<JsonPatchDocument<AccountDTO>, JsonPatchDocument<Account>>();
            CreateMap<Operation<AccountDTO>, Operation<Account>>();`
thanks!

**Comment by jbogard** [comment]
I think you can go one further, doing `CreateMap<JsonPatchDocument<>, JsonPatchDocument<>>` and AutoMapper will correctly fill in the types for you.

**Comment by arielorvits** [comment]
@jbogard maybe you mean `CreateMap(typeof(JsonPatchDocument<>), typeof(JsonPatchDocument<>));
            CreateMap(typeof(Operation<>), typeof(Operation<>));`
your code didn't compiled for me

**Comment by jbogard** [comment]
Lol yes, correct

**Comment by lbargaoanu** [comment]
This can be closed.

**Comment by jpa00** [comment]
I don't think AutoMapper is currently capable of fully mapping between JsonPatchDocument's Operations. If the property names differ between the DTO and entity, the Operations' paths will not get mapped between the two, even if you've created maps between DTO and entity. And in my case, having the names match is in no way an option. I also didn't really truly expect AutoMapper to be able to handle mapping the Operations, since they are so clearly beyond the scope of AutoMapper. Now I just need to find a way to access the mappings in my own code, so I can put together a simple way to map the paths, or maybe build a custom converter to use in CreateMap<DTO, entity>.

**Comment by lbargaoanu** [comment]
Using AutoMapper makes sense while most of the mappings work by default. You can always customize things, but the more you do it, the less you get from AutoMapper. So of course AutoMapper can map JsonPatchDocument one way or another. If it's less work than a manual approach, that's a different issue.

**Comment by jpa00** [comment]
Oh don't get me wrong, AutoMapper is an excellent tool and I don't really expect it to do everything for me. Especially this, since it's obviously beyond what it is meant for. Just dropping a comment so maybe someone will save a bit of time, not having to check in code if this actually fully works. :) And AutoMapper has features that make it absolutely worth it even in cases where you need to create most of the mapping manually.
