### ISSUE TITLE
Mapping onto existing object does no longer clear existing items from List [5.1.1]

### ISSUE THREAD

**Issue by sickboy** [AutoMapper/AutoMapper#1630]
```
class SomethingDto {}
class ADto {
    public List<SomethingDto> Somethings { get; } = new List<SomethingDto> { new SomethingDto() };
}

class Something {}
class ACls {
    public List<Something> Somethings { get; protected set; } = new List<Something> { new Something() };
}
```

```
Mapper.CreateMap<ADto, ACls>();
Mapper.CreateMap<SomethingDto, Something>();
```

```
var existing = new ACLs();
Mapper.Map(new ADto(), existing);
```

Observed: `existing.Somethings` will now have two Something instances.
Expected: `existing.Somethings` will now have one Something instance.

Workaround: `.BeforeMap((_, dst) => dst.Somethings.Clear());`
However, that does not make for a happy panda :)

**Comment by jbogard** [comment]
Huh, I was pretty sure someone else had an issue where they didn't want us to clear out the list. That we used to clear out the list, but because we pass in an existing list, the implication was "I'm giving you a collection so that you don't clear it". If you wanted a new list, you wouldn't pass in an existing list, that sort of thing.

**Comment by lbargaoanu** [comment]
@jbogard I think that one was about how to create the instance. See the PR, all the tests pass. I think the behavior was to clear it no matter what.

**Comment by pfiggins** [comment]
Same issue here. Noticed my child entities were all of a sudden being duplicated after mapping from viewmodel in 5.1.1,
