### ISSUE TITLE
InstancePropertyNotDefinedForType

### ISSUE THREAD

**Issue by allanrsmith** [AutoMapper/AutoMapper#1633]
```Exception thrown: 'System.ArgumentException' in System.Linq.Expressions.dll
Additional information: InstancePropertyNotDefinedForType, Current, System.Collections.Generic.IEnumerator`1[Core.Models.Project]```

Only hitting this in .Net Native builds.  Anyone seen this issue?  Happens during configuration of the mapper.

Automapper 5.1.1
Microsoft.NETCore.UniversalWindowsPlatform 5.2.2

**Comment by allanrsmith** [comment]
I tried going back to Automapper 5.0.2 and I do not hit this issue.  Something between 5.0.2 and 5.1.1 broke.

**Comment by lbargaoanu** [comment]
But Current is a member of ```IEnumerator<T>```. So maybe the problem is with .NET Native?

**Comment by allanrsmith** [comment]
So we dug around some more.  We had add the following to our csproj files to get around an issue with .Net Native: ```<UseDotNetNativeSharedAssemblyFrameworkPackage>false</UseDotNetNativeSharedAssemblyFrameworkPackage>```

We now removed that, and the application appears to not have the issue with 5.1.1.  I dunno... Microsoft... oy vey.

**Comment by lbargaoanu** [comment]
So the issue can be closed?

**Comment by MattWhilden** [comment]
@jspuij send enough info for me to reproduce this class if issue. Adding this to a *.rd.xml in your project should cause the error to go away:
`<Type Name="System.Collections.Generic.IEnumerator{T}" Dynamic="Required All"/>`

As part of .NET Native compilation we don't want to generate big blobs of native code for things you'll never use. So we need to determine everything your application will need at runtime. Complex flows can cause our analysis engine to bail out just a bit too early and not everything that should be saved, will be. "Fortunately" the directive above should be enough of a hint to avoid this particular issue. 

Would love to know if there's anything else lurking. Can someone else give this a shot?

I'll have to dig in some more to see what can be done to make this pattern work "out of the box".

**Comment by MattWhilden** [comment]
A bit few more gory details for those interesting in playing along from home. :-)

The reason this doesn't fail when you have SharedLibrary enabled is because we end up inadvertently trigging one of our "save everything for this type" heuristics. As soon as you disable SharedLibrary, the analysis engine doesn't hit that condition and we rely on precise marking for these members which eventually leads us off the rails.

Our analysis gets lost somewhere shortly after [here](https://github.com/AutoMapper/AutoMapper/blob/29753736e911979ae07e62ff19b2b15d64f24570/src/AutoMapper/ExpressionExtensions.cs#L25). We've discussed work that can help the analysis engine more properly follow things through expression construction like this so I'll add this as a +1 to maybe getting that funded... It's somewhat nontrivial so we'll need to balance it against other work we want to get done. A quick and dirty approach that we may try is "every time you call MakeGenericType we just save everything for that type". We'll have to see if that has any disastrous consequences downstream.

As with the other .NET Native related issue, adding a rd.xml file to the automapper library with these hints will probably be the cleanest workaround until we can get a new set of tools out an into the world.

Hope that helps.

**Comment by jspuij** [comment]
@MattWhilden I can confirm that adding the runtime directive for IEnumerator{T} makes it possible to disable the use of the SharedLibrary.

**Comment by jspuij** [comment]
@MattWhilden There is a further runtime directive that is neccessary, at least in my project:

`<Type Name="System.Collections.Generic.List{T}" Dynamic="Required All" />`

**Comment by lbargaoanu** [comment]
Enumeration is most efficient when using the concrete type enumerator methods because these use value types and avoid interface dispatch. So the generated enumeration code looks for the iterator pattern methods.
