### ISSUE TITLE
ProjectTo and GroupBy problem

### ISSUE THREAD

**Issue by banarualexandru** [AutoMapper/AutoMapper#1644]
Hi Jimmy.
You did a great job here, Thanks a lot for that.

I met a problem using Automapper. I use EF as an ORM and have query with joins and I use ProjectTo to avoid include all table columns in query, and use an Mapper.Map on the result, because I need to do some things on .AfterMap (As I know, can't use .Aftermap with ProjectTo). Till here, everything was great, untill I need to make an: `MyList.GroupBy(x=>x.SomeModel).Select(x=>x).ToList()` So I need to group by entire entity, but the groupby is not working. 
I tried to use `IEquitable<SomeModel>` But it didn't work. 
As a solution was to use Mapper.Map over IQuaryable from DB, but I have to use many .Include() which increasing the size of my query.

Did you meet this problem earlier? Can I find an workaround to use ProjectTo first, to generate optimized query, and then use an Mapper.Map?

Thanks in advance.

**Comment by jbogard** [comment]
Where is ProjectTo in the entire chain? I generally make sure that ProjectTo is the very last thing done, simply because that's how you'd use LINQ without AutoMapper. I know if you put it earlier it tends to screw up the LINQ you can use.

So, if possible, remove AutoMapper from the equation FIRST, make sure your LINQ query works, then add it back in at the very end.

Also, I'd avoid both ProjectTo and Map, and instead of Map just manually loop through your results, it's much more explicit and obvious.
