### ISSUE TITLE
Using DI to create Profiles or Converters in AutoMapper?

### ISSUE THREAD

**Issue by shawnwildermuth** [AutoMapper/AutoMapper#1724]
I'm using AutoMapper in an ASP.NET Core project. I need to inject a service (IUrlHelper or HttpContext) to be used during a mapping operation. I know I can send them as an Options.Items object when I call Map(...) but I'd rather not have to send the service from a controller on every single call. Anyway to have the Converter or Profile constructed by the DI layer so I can include a DI Service upon construction. 

My plan is to inject a IServiceProvider so I can resolve the service I need into Mapping operation. But perhaps another way to create a transient object that is used in a mapper during the lifetime of a request (e.g. a Scoped object). 

Any suggestions on solutions I'm missing in AutoMapper to allow for this?

**Comment by lbargaoanu** [comment]
Try ConstructServicesUsing. Also see https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection.

**Comment by shawnwildermuth** [comment]
I think I found a solution using the DI project. Thanks. Not super happy with the elegance, but it works great.

**Comment by jbogard** [comment]
What's the elegance issue?

**Comment by shawnwildermuth** [comment]
Not an elegance issue with AutoMapper, but elegance in passing the IUrlHelper to the mapper (since I don't want the mapper to recreate on every request), so I did this:

```
  public class BaseController : Controller
  {
    public const string URLHELPERKEY = "URLHELPER";

    public override void OnActionExecuting(ActionExecutingContext context)
    {
      base.OnActionExecuting(context);
      context.HttpContext.Items[URLHELPERKEY] = Url;
    }
}
```

Instead of passing using the Items in the resolver, I'm using the items from HttpContext so that I can do it generally in the base controller. Then in the resolver, I'm doing this:

```
  public class IdToUrlResolver<Source, Dest> : IValueResolver<Source, Dest, string>
  {
    private IHttpContextAccessor _httpContextAccessor;

    public IdToUrlResolver(IHttpContextAccessor httpContextAccessor)
    {
      _httpContextAccessor = httpContextAccessor;
    }

    public string Resolve(Source source, Dest destination, string destMember, ResolutionContext context)
    {
      var urlHelper = _httpContextAccessor.HttpContext.Items[BaseController.URLHELPERKEY] as IUrlHelper;

      if (urlHelper == null) throw new InvalidOperationException("IUrlHelper must be added to HttpContext");

      var id = (int)source.GetType().GetProperty("Id").GetValue(source);

      return urlHelper.Link("GetCamp", new { id = id });
    }
  }
```

If I were just writing code, this would be fine as I could do it once and be done. But since I'm teaching it, I have to explain all the IHttpContextAccessor and reflection bits which makes it inelegant.

**Comment by lbargaoanu** [comment]
Creating a mapper is a negligible cost for most apps. Just a few extra allocations.

**Comment by shawnwildermuth** [comment]
@lbargaoanu I thought creating the mappings themselves (all the reflection) was expensive which is why sharing it was a usual pattern. Am I wrong?

**Comment by jbogard** [comment]
You WERE right, in the <5.0 days. We now cache the expression tree compilation (also where all the speed improvements came from) at the configuration level (but only compile on first map). So in the AutoMapper DI project, I configure the IMapper instance to be a scoped instance, that way the factory method that the Mapper instance uses gets scoped instances (like a repository, DbContext etc):

https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/blob/master/src/AutoMapper.Extensions.Microsoft.DependencyInjection/ServiceCollectionExtensions.cs#L112

If your resolvers/type converter use scoped instances, then injecting the IMapper instance as a scoped instance is supported and recommended.

In fact, the AutoMapper DI project supports both the static instance of AutoMapper and the instance one, since I've made the IMapper implementation lightweight.

**Comment by lbargaoanu** [comment]
If all is clear, this can be closed.

**Comment by adam-resdiary** [comment]
I know this is a bit late, but in case it helps, here's how I've done it. Just bear in mind that I came up with this before the change from the static to instance API, so you can probably simplify it a bit using profiles, or this might be totally unnecessary now.

Define an interface for configuring your mappings:

```csharp
public interface IAutoMapperConfiguration
{
    void Configure(IMapperConfigurationExpression config);
}
```

Then define your config class (I guess this was maybe a bit like profiles for us but before that concept was available in AutoMapper):

```csharp
public class AtoBMapperConfiguration : IAutoMapperConfiguration
{
    private readonly ISomeService _myService;
    private readonly Func<IUrlHelper> _urlHelperFactory;

    public AtoBMapperConfiguration(ISomeService myService, Func<IUrlHelper> urlHelperFactory)
    {
        _myService = myService;
        _urlHelperFactory = urlHelperFactory;
    }

    public void Configure(IMapperConfigurationExpression config)
    {
        config.CreateMap<A, B>()
            .ForMember(b => b.CalculatedProp, o => o.ResolveUsing(a => _myService.Calculate(a))
            .ForMember(b => b.MyUrl, o => o.ResolveUsing(a => _urlHelperFactory().Action("MyAction", "MyController");
    }
}
```

So in the example above, our mapping requires a couple of services, so we inject them into the config class so we can use them in the mappings. I'm using a Func<IUrlHelper> instead of an IUrlHelper directly, because it will be scoped to the current web request. So what you need to do is register the IUrlHelper in your container as per web request, then register a Func<IUrlHelper> that returns the one for the current request. We use the Windsor typed factory facility to do that.

Then in your application startup code, you can resolve all the IAutoMapperConfiguration objects and configure them:

```csharp
Mapper.Initialize(cfg =>
{
	foreach (var configuration in container.ResolveAll<IAutoMapperConfiguration>())
	{
		configuration.Configure(cfg)
	}
});
```

This means that you can now unit test your mappings, and they don't use a ServiceLocator style pattern, so you get compile time support:

```csharp
[Test]
public void TestUrlIsMappedCorrectly()
{
	// Arrange
	var service = new Mock<ISomeService>();
	var urlHelper = new Mock<IUrlHelper>();
	
	var configuration = new MapperConfiguration(
		cfg => new AtoBMapperConfiguration(service.Object, () => urlHelper.Object).Configure(cfg));
	var mapper = configuration.CreateMapper();
	
	var source = new A();
	
	urlHelper.Setup(h => h.Action("MyAction", "MyController").Returns("http://my.com/Controller/Action");
	
	// Act
	var destination = mapper.Map<B>(source);
	
	// Assert
	Assert.AreEqual("http://my.com/Controller/Action", destination.MyUrl);
}
```

It also means that your controller doesn't need to worry about injecting the correct services to the mapper - they just get defined as normal constructor dependencies.

Like I say - I reckon you could get rid of the IAutoMapperConfiguration interface and just use profiles. I've just used that example because that's what currently works in our code base. I'm guessing you could do the same by just using constructor arguments with a Profile. The key is to use a factory method to get your per web request dependencies so you get the one for the correct request.
