### ISSUE TITLE
Inherited Ignore Ignored

### ISSUE THREAD

**Issue by sickboy** [AutoMapper/AutoMapper#1732]
``` C#
class A {
  public int Version { get; set; }
  public string Name { get; set; }
}
class ADTO {
    public Version Version { get; set; }
    public string Name { get; set; }
}

class BDTO : ADTO {
}
```

``` C#
CreateMap<A, ADTO>();
   .Include<A, BDTO>()
   .ForMember(x => x.Version, opt => opt.Ignore());
CreateMap<A, BDTO>();

Map(new A(), new BDTO());
```

Results in error mapping Int to Version.
While the following variants seem to work:

``` C#
Map(new A(), new ADTO());
Map<A, ADTO>(new A(), new BDTO()); // However this one doesn't seem to call the A, BDTO mapping at all
```

Shouldn't the inherited configuration always apply unless I would've overriden the Member configuration in the BDTO map?

p.s using IncludeBase in the derrived configuration doesn't work either.

My only fix is to remove the `Include`/`IncludeBase` and just clone configuration (e.g in internal extension methods).

**Comment by lbargaoanu** [comment]
The rules are byzantine, but the fact that the source matches overrides the inherited ignore.

**Comment by lbargaoanu** [comment]
Maybe a global ignore?

**Comment by sickboy** [comment]
@lbargaoanu I see, at least i'm glad i'm not seeing things :)
Also big thanks for being so responsive on the tracker here, that's really top-notch!

What's the reasoning behind the source-match, override inherited ignore behavior?

**Comment by lbargaoanu** [comment]
I guess that somebody asked for it and it was deemed reasonable :) Maybe @jbogard knows more.

**Comment by lbargaoanu** [comment]
This can be closed.

**Comment by sickboy** [comment]
@lbargaoanu it can?

**Comment by jbogard** [comment]
Well, my original thinking was you can't un-ignore. But maybe that's wrong - you can un-ignore with MapFrom.

**Comment by lbargaoanu** [comment]
Maybe I was not clear, but there is a test that asserts this exact behavior.

**Comment by jbogard** [comment]
@sickboy in the meantime, one easy way around this is to decorate your ignored member with the Ignore attribute. That gets applied every time.

In general, I try not to inherit *too* much behavior, only the things you can undo or override.

**Comment by TylerCarlson1** [comment]
@jbogard I thought the issues back then for this was some want it one way and some want it another way, and it was easier to keep it as the way it is now, so that changing doesn't pop up a whole new set of issues from people who used it the other way.

Can't satisfy everyone when it comes to inheritance

**Comment by sickboy** [comment]
I see, well to me the behavior feels wrong. It isn't really inheritance if non-transparently things are not inherited left and right. It goes against natural expections in my opinion, and i've been bitten by it a few times now :)
ForMember should indeed override the Ignore. In worst case, NotIgnore could perhaps be added.
However i'd argue that if a property is ignored in a base class, it's highly likely the property should be ignored in a derrivative as well. (E.g why define a property in a base class, only to ignore it, and then lower in the chain suddenly unignore it)
I do understand that different people will have different requirements, however this behavior seems to be counter-intuitive.

**Comment by jbogard** [comment]
I think so - this could have been made much more explicit with a property instead of Ignore() and DontIgnorePlease();

**Comment by darren-clark** [comment]
Word of caution on this one. 

I was just writing such a map, and luckily came across this issue in a search, so I'm making sure I'm adding an explicit mapping in derived classes for properties ignored in the base class. If I hadn't looked, I probably would have left them off since it worked as I wanted. Leaving me open to a subtle bug should I update to vNext.

While I would generally think the behavior of Ignore _should_ be to be inherited(as this change does), the combination of the fact that it doesn't currently, the wide distribution of AutoMapper, and the silent change in behavior(no warning, no configuration error) would make me seriously reconsider making this change.
