### ISSUE TITLE
Automapper not respecting EnumMemberAttribute value when mapping

### ISSUE THREAD

**Issue by TsengSR** [AutoMapper/AutoMapper#1741]
It seems that automapper only looks at the defined enum value but ignores [EnumMember(Value = "..")] attribute. 

```
class Test 
{
    public string Value { get; set; }
}

class TestDto
{
    public TestEnum Value { get; set; }
}

public enum TestEnum 
{
    [EnumMember(Value = "some-value")]
    SomeValue
}

Mapper.CreateMap<Test, TestDto>();

var test = new Test { Value = "some-value };
// fails: ArgumentException: Requested value 'some-value' was not found.
var testDto = Mapper.Map<TestDto>(test);

var test = new Test { Value = "SomeValue };
// works
var testDto = Mapper.Map<TestDto>(test);
```

When converting the testDto to JSON it all works fine and displays the `EnumMember`'s value. 

I'm not huge fan of this, but I'm working on an ASP.NET Core application which uses an legacy database and the values there are stored with dashes, so it'd be nice if AutoMapper respect EnumMember too. Using strings here isn't an option.

**Comment by lbargaoanu** [comment]
PR? :)

**Comment by Tornhoof** [comment]
Hi,
do you still want a PR for that?
I implemented the string->enum side here : https://github.com/Tornhoof/AutoMapper/commit/d3b8daacf3b6d13d6d959bc6aaa8d4b51557cc9e
I used a switch table for those EnumMember values and defaulted to the original impl if there are none

Do you also need the other side, enum->string?
Because as far as I see this is a bit more involved, as currently this way is done via the default StringMapper.cs and I don't think the handling of that Enum specific attribute has a real place in there, so probably a EnumToStringMapper.cs would be necessary.

**Comment by Tornhoof** [comment]
I added the other side too, was way less involved than previously anticipated.
