### ISSUE TITLE
Mapping configuration to keep using destination value (ignore source)

### ISSUE THREAD

**Issue by maurosampietro** [AutoMapper/AutoMapper#1784]
I'm sorry concrete examples when explaining a problem with Automapper tend to be tedious; by the way I cannot get a configuration to achieve what i want.

**Class definitions:**

```
public class A
{
 public List<B> Collection{get; set;}
}

public class A1
{
 public List<B1> Collection{get; set;}
}

public class B
{
 public string PropertyA{get;set;}
}

public class B1
{
 public string PropertyA{get;set;}
 public string PropertyB{get;set;}
}

```

**Instances**

```
var a = new A
{ 
 B = new List<B>() {  new B1() { PropertyA="c",  } )
}

var a1 = new A1
{ 
 B1 = new List<B1>() {  new B1() { PropertyA="a",  PropertyB="b"  } )
}
```

What i want to achieve when mapping A to A1 using mapper.Map(a,a1):

```
var a1 = new A1
{ 
 B1 = new List<B1>( new B1(){ PropertyA="c", PropertyB="b" } )
}
```

but instead I get:

```
var a1 = new A1
{ 
 B1 = new List<B1>( new B1(){ PropertyA="c", PropertyB=null } )
}

```

I read other threads and i though configuring like this would work:

```
new MapperConfiguration( cfg =>
{
      cfg.CreateMissingTypeMaps = true;
      cfg.CreateMap<A, A1>().PreserveReferences();
      cfg.CreateMap<B, B1>().ForMember( x => x.PropertyB,
           config => config.UseDestinationValue() ).PreserveReferences();
 }
```

How can i get the destination type's property to keep its value (and not being set null since the source type do not have that property)?

**Comment by lbargaoanu** [comment]
When you pass a collection destination, you reuse just the collection instance, the items are cleared. That's by design.

**Comment by maurosampietro** [comment]
I don't mind getting rid of UseDestinationValue(), how can i achieve my goal?
Is it somehow possible?

**Comment by lbargaoanu** [comment]
You can map item by item.

**Comment by maurosampietro** [comment]
But Im already doing it!

   cfg.CreateMap<A, A1>().PreserveReferences();
      cfg.CreateMap<B, B1>().ForMember( x => x.PropertyB,
           config => config.UseDestinationValue() ).PreserveReferences();

**Comment by TylerCarlson1** [comment]
You would have write the code yourself to iterate through each of them and add map them item by item.  With collection maps in AutoMapper the destination list is cleared and then items are mapped from source and then added to the destination.  The reason for this, is because AM doesn't know what items should be mapped to each other.

[AutoMapper.Colleciton](https://github.com/TylerCarlson1/Automapper.Collection) does this, but you need to provide a way to see if 2 objects are equivalent to each other, so they map.  If you are going purely by their order in the list it won't work though.

**Comment by lbargaoanu** [comment]
This can be closed.
