### ISSUE TITLE
How to donate

### ISSUE THREAD

**Issue by mrwillis** [AutoMapper/AutoMapper#1820]
I absolutely love this library. It has saved me so much headache with mapping. Is there any way I can donate or send a gift?

**Comment by lbargaoanu** [comment]
When I was about to lose all hope in humanity. That's nice :)

**Comment by adam-resdiary** [comment]
I'll second that. If there's some way I can donate I will. I know I've been raising tons of issues recently because my company is in the middle of upgrading to version 5, but we've been mega impressed with how quickly you've dealt with anything we're raised, and the performance improvements are amazing! Well done!
