### ISSUE TITLE
Exception when mapping expression with a property that maps to a string type

### ISSUE THREAD

**Issue by arknu** [AutoMapper/AutoMapper#1821]
Say I have two types like this:

```
public class ItemDto
{
	public int Id { get; set; }

	public string Name { get; set; }

	public DateTime CreateDate { get; set; }
}
```

and

```
public class Item
{
	public int Id { get; set; }

	public string Name { get; set; }

	public DateTime Date { get; set; }
}

```

If I then do this, I would expect the expression to be mapped correctly:

```
Mapper.Initialize(cfg =>
{
	cfg.CreateMap<ItemDto, Item>()
	.ForMember(dest => dest.Date, opts => opts.MapFrom(x => x.CreateDate));
});

Expression<Func<Item, object>> exp = x => x.Name;

var mapped = Mapper.Map<Expression<Func<ItemDto, object>>>(exp);
```

Instead, I get an exception:

> System.InvalidCastException: 'An object of the type 'System.Linq.Expressions.Expression`1[System.Func`2[AutomapperTest.Models.ItemDto,System.String]]' cannot be converted to the type 'System.Linq.Expressions.Expression`1[System.Func`2[AutomapperTest.Models.ItemDto,System.Object]]'.'

However, when mapping an expression for the Date/CreateDate property, there is not problem.

The difference seems to be that the expression generated for the string property has a body of type `MemberAccess`, whereas the expression for the Date property has a body of type `Convert`

**Comment by TylerCarlson1** [comment]
I would suggest explicitly casting the string to object and see if that works. Also if you made return type string instead of object that would also avoid an exception.

With expressions you need to be very explicit on types. Can't assume the types will figure themselves out

Sent from my iPhone

On Nov 25, 2016, at 11:47 AM, Asbj?rn Riis-Knudsen <notifications@github.com<mailto:notifications@github.com>> wrote:


Say I have two types like this:

public class ItemDto
{
        public int Id { get; set; }

        public string Name { get; set; }

        public DateTime CreateDate { get; set; }
}


and

public class Item
{
        public int Id { get; set; }

        public string Name { get; set; }

        public DateTime Date { get; set; }
}



If I then do this, I would expect the expression to be mapped correctly:

Mapper.Initialize(cfg =>
{
        cfg.CreateMap<ItemDto, Item>()
        .ForMember(dest => dest.Date, opts => opts.MapFrom(x => x.CreateDate));
});

Expression<Func<Item, object>> exp = x => x.Name;

var mapped = Mapper.Map<Expression<Func<ItemDto, object>>>(exp);


Instead, I get an exception:

System.InvalidCastException: 'An object of the type 'System.Linq.Expressions.Expression1[System.Func2[AutomapperTest.Models.ItemDto,System.String]]' cannot be converted to the type 'System.Linq.Expressions.Expression1[System.Func2[AutomapperTest.Models.ItemDto,System.Object]]'.'

However, when mapping an expression for the Date/CreateDate property, there is not problem.

The difference seems to be that the expression generated for the string property has a body of type MemberAccess, whereas the expression for the Date property has a body of type Convert

-

**Comment by arknu** [comment]
Unfortunately, this is going into an API (NPoco, to be specific) that wants that expression. What I do as a workaround is this:

```
public static Expression<Func<TParam, TResult>> WrapExpressionBody<TParam, TResult>(Expression<Func<TParam, TResult>> expression)
{
	if(expression.Body.NodeType == ExpressionType.MemberAccess)
	{
		//Wrap in Expression convert
		var wrap = Expression.Convert(expression.Body, typeof(TResult));
		var lambda = Expression.Lambda<Func<TParam, TResult>>(wrap, expression.Parameters);
		return lambda;
	}
	
	return expression;
}
```

Basically, wrapper the MemberAcces block a Convert block. 

But AutoMapper should be able to handle this without going through this.

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-Build) build.
