### ISSUE TITLE
Identify unused mappings

### ISSUE THREAD

**Issue by vegar** [AutoMapper/AutoMapper#1841]
So after a year or two using Automapper, we see a growing maintenance challenge.

It is easy to add a new mapping, but no one dear to remove the old one, cause who knows where else that mapping might be used?

So my question for you, and the community is:

* Is there any reliable way of identifying if a given mapping is in use or not?
* How should we best organize our mappings to remedy this problem?

**Comment by jbogard** [comment]
Well that's never been a problem for me. Since I have mappings for View
Models, and there's one view model per view, an unused mapping would mean I
deleted a screen. And that's super easy to find during our pull request
reviews.

I also organize my mappings inside my feature folders, so it's easy to look
at a feature folder and the mappings it uses.
