### ISSUE TITLE
IQueryable auto mapper

### ISSUE THREAD

**Issue by AmolHegana** [AutoMapper/AutoMapper#1878]
I have EF data object in repository project where as my business logic method uses BusinessObjects. I am using AutoMapper for conversion from Data obejct to business object.

But if my business logic methid returns IQueryable<BusinessObject>. So i have 2 options
1. Convert DB object into Business objects and then make it AsQuerable()
2. AutoMapper on Queryable. [Approach looks better if it doesn't traverse[enumerate] for conversion.]

I just want to know whether it traverses though collection and maps entities??

**Comment by TylerCarlson1** [comment]
[UseAsDataSource](https://github.com/AutoMapper/AutoMapper/wiki/Expression-Translation-(UseAsDataSource)#useasdatasource) is probably what you want.  And it doesn't enumerate the collection, so if you have any filtering or take/skip on top of that it will be translated into a T-SQL statement instead of in memory.  Then after filtering on the DB level it will then map the results like ProjectTo.
