### ISSUE TITLE
Issue when using an abstract base class

### ISSUE THREAD

**Issue by Ciwan1859** [AutoMapper/AutoMapper#1891]
Hello everyone

I've been trying to solve [this problem](http://stackoverflow.com/q/41430679/613605) for weeks but still no luck, then I came across [this question](http://stackoverflow.com/q/3441916/613605) on StackOverflow, which seem to relate to mine since we're both using an abstract base class.

According to comments and answers, this was an issue, but got fixed! I'm thinking this bug might have crept back in? Either that, or I'm totally using it wrong.

Any help would be greatly appreciated.

Thank you

**Comment by TylerCarlson1** [comment]
Problem is probably Address and Contact are causing the problem.  AM clears out the collection then remaps everything.  So all your child entities get orphaned and replaced with new entities.  These orphaned entries aren't deleted because of how EF works.

[AutoMapper.Collection](https://github.com/AutoMapper/AutoMapper.Collection) will help with this by comparing values by their ID and Add/Remove items and Update existing entities in child lists.

This doesn't solve the orphan issue unfortunately, it just helps not constantly re-creating entities.  If you don't remove Addresses or Contacts it will work but once you delete one this exception will come back up.

One way to sort of solve this is https://github.com/AutoMapper/AutoMapper.Collection/issues/4 but it has some issues, and there's not a really good all encompassing solution.
You can check for other issues about handling orphaned object in EF.

The other similar question is asking something unrelated and should of been fixed in the latest version.  The having a base class shouldn't have any issues with what you are trying to do.

**Comment by Ciwan1859** [comment]
Thanks @TylerCarlson1, so what do people do? Cause I'm sure this is a common scenario. Do I only use AutoMapper when going from Entity to ViewModel?

And when doing a POST where I have to go from ViewModel to Entity, I do manual mapping? Cause when I manually map, all works with no issues.

**Comment by jbogard** [comment]
So me personally - no I don't go back from ViewModel to Entity. Our apps
it's never that simple. But some are, so I'd check out the
AutoMapper.Collections package, it should help here.

**Comment by TylerCarlson1** [comment]
As far as what people do it depends on who you ask.  I'm all for mapping back, even with issues that come with it.
[AutoMapper.Collection](https://github.com/AutoMapper/AutoMapper.Collection) handles all the complexties of EF mapping back except the orphan problem.

https://github.com/AutoMapper/AutoMapper.Collection/issues/4 could fix the orphan issue.  Works for most general cases and might need slight tweaking.

I have 30+ entities that have instances of 1-4 child lists and some have their own sub child lists, so for me having to manually map the lists for each one was not an option.

Maybe I'll get Automapper.Collection to elegantly handle the orphan problem, but for now dealing with this issue is WAY better than dealing with manual mapping back.

**Comment by TylerCarlson1** [comment]
Also there's [this](http://stackoverflow.com/questions/11033348/is-it-possible-to-remove-child-from-collection-and-resolve-issues-on-savechanges) option.

Example of changes
```
public class Address : IEntity
{
  public Address()
  {
    CreatedOn = DateTime.UtcNow;
  }

  [Key, Column(Order = 1)] // Must set both as a composite key
  public int Id { get; set; }
  [Key, Column(Order = 2)] // Setting this as part of the key means it will be removed instead of orphaned when removed from Business.Addresses
  public int BusinessId { get; set; }

  public string AddressLine1 { get; set; }
  public string AddressLine2 { get; set; }
  public string Area { get; set; }
  public string City { get; set; }
  public string County { get; set; }
  public string PostCode { get; set; }
  public string Country { get; set; }
  public bool IsDeleted { get; set; }
  public DateTime CreatedOn { get; set; }
  public DateTime? ModifiedOn { get; set; }
  public virtual Business Business { get; set; }
}
```

It's weird having primary key like this, but EF will see this and say the Address's identity depends on having a Business parent, so removing it from Business.Addresses will Deletes the entry instead of Orphaning it.

**Comment by lbargaoanu** [comment]
Maybe move the issue to AM.Coll?

**Comment by jbogard** [comment]
Yep, closing this on here.
