### ISSUE TITLE
Conditional mapping to existing collection doesn't work from version 5.2.0

### ISSUE THREAD

**Issue by vukasinspasic** [AutoMapper/AutoMapper#1918]
Starting from version **5.2.0** conditional mapping to existing object no longer works. I tried also with latest version of MyGet build **5.3.0-alpha-01281**, but no luck. Conditional mapping works fine with **5.1.1**!

I made a Gist so you can reproduce it:
https://gist.github.com/vukasinspasic/64d4abf3870443c83f2830e80b452e13

**Comment by lbargaoanu** [comment]
Check [the execution plan](https://github.com/AutoMapper/AutoMapper/wiki/Understanding-your-mapping).

**Comment by vukasinspasic** [comment]
Execution plan contains

                    if (condition.Invoke(src))
                    {
                        typeMapDestination.Details = propertyValue;
                    }

but Details collection still gets mapped, even though condition.Invoke(src) should return false if src.Id is not Guid.Empty

**Comment by lbargaoanu** [comment]
Yes, I see it. The bug happens only when you pass a destination.

**Comment by vukasinspasic** [comment]
If you have some pointers, I can try to fix this issue?

**Comment by lbargaoanu** [comment]
The problem is [here](https://github.com/AutoMapper/AutoMapper/blob/539659d41b88e83502ab5265b6b4a2c63280e9d2/src/AutoMapper/Execution/TypeMapPlanBuilder.cs#L355). The condition is checked above, but propertyValue is still set. The idea is to move it inside the condition check :)

**Comment by lbargaoanu** [comment]
I think the best course of action here is to work around it with a PreCondition.

**Comment by lbargaoanu** [comment]
@jbogard I'm not sure the Condition overloads make much sense. I think the original idea was to receive the source, destination and the source and destination members. But actually only the destination member type is involved here. So the condition receives the new destination member value and the old one :) So it's not even the resolved value, it's the final value. And the overloads, after two parameters, it's easy to get confused :) ResolveUsing is somewhat better because it considers the source member type.
About the current issue. The condition needs the destination property value. So it's mapped before calling the condition, making the condition useless. I guess special casing the overloads that don't need the destination value would solve it, but I don't know.
It's not nice to break things, but it's messy as it is.

**Comment by vukasinspasic** [comment]
I agree that problem is not in Condition because same type map is used when mapping to new object and in that case it works. If you have some more pointers, I am ready to help and make changes

**Comment by vukasinspasic** [comment]
Any news on this bug?

**Comment by Mytza** [comment]
Any news when this is going to be fixed?

**Comment by lbargaoanu** [comment]
As it says above, try a PreCondition.

**Comment by ggirard07** [comment]
Hi! Sorry for stepping into this discussion without much knowledge about AutoMapper as I am a new user. Thanks for pointing me in the direction of `PreCondition`, I missed the overload passing directly my entity instead of the `ResolutionContext`.

Even if this is now working, I still have difficulty to understand what really happen during the mapping for each property as. My understanding now is:

1. Execute PreCondition
2. Execute Copy
3. Execute Condition

If it is right, I just don't understand the point of `Condition` as it runs after the copy... For me it is no longer a condition, but instead a kind of PostCopy action.
Also, `Condition` looked so much appropriated to what I was trying to achieve as It precisely matched the context of the current copy. I would have even be able to make a generic condition to bypass any null members of any entity from any mapping really easily. `PreCondition` is really specific to the current entity and can't really be made generic.

Again I am pretty new with AutoMapper, but if this is right, it is pretty misleading for those who wants to start using your stuff.

**Comment by lbargaoanu** [comment]
To understand read [this](https://github.com/AutoMapper/AutoMapper/wiki/Conditional-mapping) and follow the last link in there. This is really a corner case because it's about collections and you pass the destination. So then the destination collection is the same as the source collection. And the destination collection is cleared as per my comment above. If you're using this with EF, you might want to look into AutoMapper.Collection.
