### ISSUE TITLE
Ability to map from source child object to flattened destination object where fields match

### ISSUE THREAD

**Issue by ChronosWS** [AutoMapper/AutoMapper#1945]
Given a source type hierarchy:

class ASrc {
  BSrc b;
  int aFoo;
}

class BSrc {
  int bFoo;
}

and a destination type hierarchy:

class ADst : BDst {
  int aFoo;
}

class BDst {
  int bFoo;
}

Request a feature

CreateMap<ASrc, ADst>()
  .Flatten(s => s.b);

Where Flatten selects a source member whose members must map exactly from s.b onto d, and which counts toward validation for unmapped destination members.  Currently this does not appear to be achievable via workarounds which use tricks like AfterMap() without having to explicitly Ignore() those properties.  See http://stackoverflow.com/questions/35573006/how-to-use-automapper-to-map-destionation-object-with-a-child-object-in-the-sour.

**Comment by ChronosWS** [comment]
NOTE: There *is* an unsafe alternative, as follows:

CreateMap<ASrc, ADst>()
.ConstructUsing(s => AutoMapper.Mapper.Map<ADst>(s.b)
...
.ForAllOtherMembers(o => o.Ignore)

Unfortunately, the blanket ignore means that if you add other members that you would intend to map, validation will not catch it.  This also requires a mapping to be created from BSrc to ADst explicitly.  It's a trivial mapping (since all the members match exactly) but it's a smell.

**Comment by lbargaoanu** [comment]
AutoMapper supports flattening by default. You just have to respect a naming convention that you can customize. I don't think it supports members named the same, probably because it makes the mapping more difficult to understand (it seems clearer to make the flattening explicit). That Flatten method you should be able to implement it yourself as an extension method. It's true that you would have to use MapFrom(Expression), I don't see an easier way. Definitely maybe :)

**Comment by lbargaoanu** [comment]
Seems related to https://github.com/AutoMapper/AutoMapper/issues/1811.

**Comment by lbargaoanu** [comment]
[Here](https://gist.github.com/lbargaoanu/8e15798a8b4facd292feb5fcfbf1e3f7#file-flatten-cs) is an example.
