### ISSUE TITLE
Could Mappers collection be on IProfileExpression?

### ISSUE THREAD

**Issue by flcdrg** [AutoMapper/AutoMapper#1967]
I'm moving some mapping configuration code into separate profiles and noticed that in the trunk codebase the `Mappers` property currently only exists on `IMapperConfigurationExpression`.

Would it make sense to push this up to `IProfileExpression` so you could add custom mappers in each profile?

**Comment by flcdrg** [comment]
Yes, in this case the custom mappers only make sense in one profile.

I'm currently registering them with the static `MapperRegistry.Mappers`
property (using 5.2). I've moved this code to the custom profile
constructor just because it makes sense to be there, and thinking about
what would make sense with the changes coming in trunk.

**Comment by lbargaoanu** [comment]
That could work. The final list would merge the singleton global mappers with the per profile mappers, so the existing mappers wouldn't be affected.

**Comment by TylerCarlson1** [comment]
I understand it makes sense to put the code in the profile it associates too for readability.  My question is putting it in the `IMapperConfigurationExpression` going to cause any problems with the mappings working correctly?

Like if the mapper was global would it accidentally map things incorrectly as apposed to being only applied to maps generated in the profile it was set in?

**Comment by lbargaoanu** [comment]
I don't see a problem.

**Comment by TylerCarlson1** [comment]
@lbargaoanu I see it as new possible source of confusion when mapping, so I ask if this is necessary or a would be nice to have.

**Comment by lbargaoanu** [comment]
I think it makes sense. If I can have a map per profile, I should be able to do the same for mappers. I think most people would happily ignore it. The "Advanced" thing would probably help. @flcdrg should make a PR. Maybe wait for @jbogard to agree first.

**Comment by jbogard** [comment]
Sooooooo I went back and forth on this. A LOT.

The problem is I wanted Profiles to segregate configuration, so that things applied at the Profile level only applied to maps created in the Profile. Things that you wanted _across_ all maps you'd put in the global, `MapperConfiguration` level.

You can see this from the methods on `IMapperConfigurationExpression`:

```
bool? CreateMissingTypeMaps
void ConstructServicesUsing
List<IObjectMapper> Mappers
```

And the methods since it inherits from Profile and `IProfileExpression`, all the configuration at the root also applies to any Profile created under it.

This would invert that, where profile configuration would bubble up. We already do that with type maps, would this be any different?

The question is - would users expect that mappers created on a profile to only apply to that profile? I'm guessing not?

The other issue is that today with that one list it's one reference, so you can remove, add, insert etc. on that list. If we went this route we'd have to make sure it was the SAME instance that all profiles mutated.

**Comment by lbargaoanu** [comment]
If you configure mappers per profile, you expect them to apply per profile. Every profile has it's own list of mappers that it's initialized with the root profile list. So you get to customize per profile what you want. For example a profile without the StringMapper. So that would be like profile configuration, not like the maps. I think :)

**Comment by jbogard** [comment]
Which I think would be a bit confusing I think.

**Comment by lbargaoanu** [comment]
Well, yes, but that's how it works right now with settings that are collections, like global ignores for example.

**Comment by jbogard** [comment]
Not anymore! Global ignores are only "global" for the profile. The root configuration's global ignores are pushed down to the profile.

**Comment by TylerCarlson1** [comment]
@jbogard Exactly my thoughts on how it would be implemented and why I wouldn't want to do it.  Adds more confusion on top of what we already have.

I think in his scenario leaving the mapper in the `IMapperConfigurationExpression` vs the profile won't cause any kind of bug.  It would just be nice to have aesthetically for him.

**Comment by flcdrg** [comment]
Yeah, that's right.

As a user of AM, I didn't really see a big distinction between `ObjectMapper` and `CreateMap` - just two different ways to achieve similar things. Maybe as the authors of AM you do see more of a difference though.

**Comment by jbogard** [comment]
Yeah, there's an order involved in the registration. Unlike type maps.

**Comment by lbargaoanu** [comment]
I don't see it, like at all. I agree that profile configuration is somewhat confusing, but I don't see mappers as different. It could work the same way.
@jbogard About global ignores, that's exactly what I'm saying :)
Anyway, very few people would use it.

**Comment by jbogard** [comment]
@lbargaoanu but global ignores don't have any ordering issues, the IObjectMapper collection does. I just don't see this as simple as today there are no connections between the Profile and global configuration instances. If someone wants to re-order or remove instances from the mapper collection (or totally replace it), they could. I'm not sure how that could be accomplished with mapper collections in profiles.
