### ISSUE TITLE
Allow profiles to add custom mappers

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#2069]
Today it's hard to add custom mappers to the collection. This makes new mappers like the AutoMapper.Collections package weird to register.

For simplicity's sake we can just allow:

```
AddCustomMapper(IObjectMapper)
```

And these would just be added to the top of the mapper collection.

**Comment by TylerCarlson1** [comment]
Ehhhhhhhhhh I don't know about this one.  It's not that hard to add custom mappers to the collection.  The big issue is the order in which it's placed, which you would have to look at all the other mappers, if you want to replace logic.  And adding custom mappers is more of an Advance feature.  You have to deal with Expressions, so I think they can handle inserting the the mapper into the main list.

Maybe adding at the beginning of the list will work in most situations, but it might have un-intended consequences.  I can't predict what the intent is.  I would think they would just do Insert(0, CustomMapper).

Also the title is misleading to what's in the post.  Is this Profile specific IObjectMapper collections or just having profiles load to the main collection?

Maybe you want some kind of common extension framework, and I can see that I guess.  But I don't think it should be part of the Profile because it will effect other profiles if I understand what you want to do correctly.

**Comment by jbogard** [comment]
Not profile-specific collections - that's too confusing. Type maps are global, so are object mappers.

No matter what you'd still have order issues. Which is weird anyway. There's a separate issue of us relying on order in that collection and bugs that come up with order not being correct.

**Comment by TylerCarlson1** [comment]
Oh now that I see #2070 I get what you are going for more with this.

**Comment by jbogard** [comment]
It's yours and AutoMapper.Data. Well really any extensions to AutoMapper. It should be a lot easier to register extensions.

**Comment by TylerCarlson1** [comment]
I think it's fine now and the developer of the extension has to make the decision to how it should be registered using the configuration.
AM.Collections I changed to an extension method to register it, and another extension method to adding conventions like EF Database for Primary Key matching.  Same could be done for AM.Data where it's like `cfg.AddDataMappers()` which adds the the object mapper to the end of the collection.

Unless you want to make a new interface just to register extensions from passing in the configuration, which doesn't gain you anything except having people expect a certain standard.  If you break AM down into smaller pieces this might make sense, but otherwise not really.

**Comment by jbogard** [comment]
Hmmm, that might be a better approach, an extension method to that root configuration expression.

The way of adding custom mappers in AutoMapper.Collections is still....wonky to say the least. You're inserting the custom mappers before things - I'd love to be able to have just AddMapper somewhere, even if it's in the root. It could just add that custom mapper to the top of the list.

**Comment by jbogard** [comment]
Yeah you're right, this isn't really a problem. You can create an extension method on IMapperConfigurationExpression if you wanted to make it easier.
