### ISSUE TITLE
Break out "special" mappers from main repo

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#2070]
And introduce new repos and packages for them.

This would include:

- LINQ projection (ProjectTo)
- ExpressionMapper
- Dynamic/dictionary

This would cut down the core repo to just the in-memory object-to-object mapping. A couple of reasons to do this:

- Not every uses the above features
- Having all in the same repo is confusing - we've got 3-4 different "ways" to map from A-B
- Make it more obvious that these mappings go outside the normal configuration, so your MapFrom etc won't necessarily work

I already did this with IDataReader. The packages could be:

- AutoMapper.Linq
- AutoMapper.ExpressionMapping
- AutoMapper.DynamicMapping

**Comment by jbogard** [comment]
Oh I forgot to add, Conventions would be on this list too.

**Comment by jbogard** [comment]
Conventions *might* be on this list that is.

**Comment by TylerCarlson1** [comment]
I think ExpressionMapper and ProjectTo could share a lot of code with TypeMapPlan builder if you consolidated them.  So I don't know if you would want to separate them, or have a variable changing Advanced API for expression helper calls.

Also you would have to take things like ProjectUsing from an interface call to an extension method, and retain it's own map expression configuration in a different repo, or make the existing mapping expression be expandable.

**Comment by TylerCarlson1** [comment]
Like AutoMapper.Collections has to have its own list of type map pairs to keep track of Equivalency expressions, and use them accordingly.  And all function calls are extension methods off the existing interfaces.

Almost seems like you need to make this thing expandable on a type map generation level when you get down too it.

Right now I think this is overkill.

But if you refactor to this and then merge it back into a single project, you would be able to **greatly** organize internal functionality, and get rid of duplicate code for things like Expression generation.

**Comment by jbogard** [comment]
Is there actually duplicate code for expression generation? The trees generated are really quite different, and TypeMap -> Expression generation is also quite different than Expression -> Expression generation.

Maybe not though.

A lot of my motivation here is trying to have the core library really only concerned with in-memory mapping and remove the ancillary mappings that don't go through Mapper.Map. Keep the focus on that and anything else can be extensions. But the extension story today is pretty lousy.

**Comment by TylerCarlson1** [comment]
Expression mapping is closer to ProjectTo with the visitors, but they all share some similar components.

Most common would be replacement visitors(Think there might be 3-4 that could be put into one), and ToType which is used a lot of places, but there might be more that could be consolidated or configured.

Since the visitors for Expression Mapping have been broken up into their own compact classes those might have overlapping functionality with TypeMap plan builder, or ProjectTo's visitors.

As far as breaking it up I think it's possible and will lead to overall better consistent code.  It's just going to be a whole lot of work for possibly not that much benefit.  Don't know if users would even want to break it up into pieces.  I can see for .NET Foundation that makes more sense as a general mapper for ASP.NET and stuff but that's about it.

**Comment by BlaiseD** [comment]
Happy to work on moving AutoMapper.ExpressionMapping - the functionality is already siloed since it is new.  IMHO consolidating reusable code can be separate effort.  It does sound like some of the code that maps expressions can be reused across features.
