### ISSUE TITLE
`CreateMissingTypeMaps` doesn't work for destination object if source and destination types are the same

### ISSUE THREAD

**Issue by llRandom** [AutoMapper/AutoMapper#2129]
### Source/destination types

```csharp
class A
{
    public string X { get; set; }
}

class B
{
    public string X { get; set; }
}
```

### Mapping configuration

```csharp
var config = new MapperConfiguration(cfg => cfg.CreateMissingTypeMaps = true)
```

### Expected behavior
I pass an existing object to be filled. The type of source and destination objects are the same. I expect the destination object to be filled.

### Actual behavior
The destination object is not filled. If I use a different destination type, it works fine. If I create a new object of the same type, it also works fine.

### Steps to reproduce

```csharp
var config = new MapperConfiguration(cfg => cfg.CreateMissingTypeMaps = true);
var mapper = config.CreateMapper();
var a1 = new A { X = "sample" };
var a2 = new A();
mapper.Map(a1, a2); // a2.X was not set, looks like a bug
var a3 = mapper.Map<A>(a1); // a3.X is set, ok

var b = new B();
mapper.Map(a1, b); // b.X is set, ok
```

**Comment by jbogard** [comment]
This is expected behavior. If the source/destination types are assignable to each other, AutoMapper simply assigns them (as AutoMapper is not a cloning library).

If you want to explicitly map between two assignable types in a pseudo-cloning behavior, you need to explicitly create the map.

`CreateMissingTypeMaps` should be used with extreme caution - it's not meant to be a fix for developer laziness. It's really when you don't know all the maps at config-time.

You're also not even cloning, but filling in an existing object. Just call CreateMap. That works.

**Comment by llRandom** [comment]
But the cloning actually works (case with `a3` variable). It's really not clear why this call just returns the `source` object and doesn't modify the `destination`. Could you please explain it in more details?

**Comment by jbogard** [comment]
This kind of behavior, mapping to itself PLUS `CreateMissingTypeMaps` isn't a supported scenario, so the behavior is unknown.

**Comment by llRandom** [comment]
But why it could not or should not be supported? Why this case is an exception?

**Comment by jbogard** [comment]
It's just a scenario that has any tests around it. That's what I mean "not
supported", it's not designed for this scenario. Things also tend to act
not ideal for CreateMissingTypeMaps, which is why I discourage its use as
much as possible. Be explicit about what you intend to map, and things tend
to work just fine.

**Comment by llRandom** [comment]
I still don't understand, is it some design limitation that blocks from implementing it or is there a logical reason why this particular case should not be supported?

**Comment by feafarot** [comment]
I also can't understand what is the real reasoning behind this.

**Comment by jbogard** [comment]
AutoMapper isn’t a cloning library. Never has been as part of its design.

Specifically what’s going on here is there is a fallback mapping strategy,
that if two types are assignable, just assign them. If you want to
explicitly map these two types, call `CreateMap` or remove the
`AssignableMapper` from the list of mappers. I don’t know what those side
effects will be, likely making your mapping slow since everything has to
now go through some mapping strategy. Primitive types will be wonky for
example.

So while you can clone in some scenarios, it’s not an out of the box
behavior.
