### ISSUE TITLE
Custom value resolver doesn't work when `AddConditionalObjectMapper()` is used

### ISSUE THREAD

**Issue by mrahhal** [AutoMapper/AutoMapper#2181]
A minimal repro of this issue is [here](https://github.com/mrahhal/AutoMapperRepro).

When using a simple custom value resolver that just maps an inner property, and `AddConditionalObjectMapper()` has been configured, the returned mapped value doesn't reflect what the value resolver returned. It's still being called though, but it's like the returned value isn't being used.

If I comment out the call to `AddConditionalObjectMapper()` everything works as expected (please check the repro).

**Comment by lbargaoanu** [comment]
Try to investigate what's causing it. Usually excluding some types does the job. If it's something more serious, we'll investigate. That's the problem with AddConditionalObjectMapper & friends. You don't really know in all cases whether it's OK to create a map or not. I've given up a long time ago :)

**Comment by mrahhal** [comment]
Heh, well that's problematic. I think we're using something that you recommended someplace:

```
var efDynamicProxiesNamespace = "System.Data.Entity.DynamicProxies";

@this.AddConditionalObjectMapper().Conventions
	.Add((TypePair tp) =>
		tp.SourceType.Namespace != efDynamicProxiesNamespace &&
		tp.DestinationType.Namespace != efDynamicProxiesNamespace);
```

I just thought the problem is not specific to what conventions are configured. Will investigate more.

**Comment by lbargaoanu** [comment]
I think that's @TylerCarlson1. Take a look [here](https://github.com/AutoMapper/AutoMapper/blob/859612d672a45c62f3cce5c8b236be796497c916/src/AutoMapper/ProfileMap.cs#L19) to see what I mean.

**Comment by mrahhal** [comment]
Ah thanks a lot. Adding the excluded types your link points to, in addition to the "System.Data.Entity.DynamicProxies" namespace, fixed this.

**Comment by TylerCarlson1** [comment]
What I usually do for conventions is for things like EF to Dto and back and if names match except have like Dto at the end.  Like Order -> OrderDto and OrderDto -> Order, so that I specifically make a convention for just that situation and doesn't bleed into other places.

Other people use CreateMissingTypeMaps which is map anything to anything.  And the general fix is don't use dynamic not in "System.Data.Entity.DynamicProxies" namespace, where you still get CreateMissingType functionality, but fix the EF mapping problem.  That seems to work in most cases, but it's really still not the best idea cause anything can be mapped to anything else which you might not want.

**Comment by mrahhal** [comment]
@TylerCarlson1 thanks for your input.

I usually use `CreateMissingTypeMaps` for things like Order -> OrderDto and Input -> Order (I don't use the dto as an input), except for when I need to really configure something, at that point I do create a map. I find creating a map for each and every pair I want to map is extremely inconvenient since 90% of times the default mapping behavior will work.

**Comment by jbogard** [comment]
Just never misspell anything :)
