### ISSUE TITLE
UseDestinationValue is not inherited

### ISSUE THREAD

**Issue by ds1709** [AutoMapper/AutoMapper#2194]
`UseDestinationValue` doesn't works when using Include<,> or IncludeBase<,>. Looks similar like here #2188, also used `IncludeBase`, but option is `PreserveReferences`.

### Source/destination types

```csharp
// Model
sealed class Root { public List<Element> Elements { get; } = new List<Element>(); }
class Element { public List<Item> Items { get; } = new List<Item>(); }
class ElementX : Element { }
sealed class Item { }

// Dto
sealed class RootDto { public List<ElementDto> Elements { get; } = new List<ElementDto>(); }
class ElementDto { public List<ItemDto> Items { get; } = new List<ItemDto>(); }
class ElementXDto : ElementDto { }
sealed class ItemDto { }
```

### Mapping configuration

```csharp
CreateMap<Root, RootDto>().ForMember(_ => _.Elements, _ => _.UseDestinationValue());
CreateMap<Element, ElementDto>().ForMember(_ => _.Items, _ => _.UseDestinationValue());
CreateMap<ElementX, ElementXDto>().IncludeBase<Element, ElementDto>();
CreateMap<Item, ItemDto>();
```

### Expected behavior
When mapping `Root` to `RootDto`, for each source `Element` in `Elements` will be created `ElementDto` (`ElementXDto` for `ElementX`), and it's `Items` collection will be populated by mapped objects from source collection.

### Actual behavior
For `ElemenDto` colelction populated, but for `ElemenXDto` collection is empty.

### Steps to reproduce
```csharp
var config = new MapperConfiguration(cfg =>
{
    cfg.CreateMap<Root, RootDto>().ForMember(_ => _.Elements, _ => _.UseDestinationValue());
    cfg.CreateMap<Element, ElementDto>().ForMember(_ => _.Items, _ => _.UseDestinationValue());
    cfg.CreateMap<ElementX, ElementXDto>().IncludeBase<Element, ElementDto>();
    cfg.CreateMap<Item, ItemDto>();
});
config.AssertConfigurationIsValid();
var mapper = config.CreateMapper();

var source = new Root
{
    Elements =
        {
            new Element { Items = { new Item(), new Item(), new Item() } }, // 3 items
            new ElementX { Items = { new Item(), new Item(), new Item() } } // 3 items
        }
};

var target = mapper.Map<RootDto>(source);
```
As result:
```
source.Elements[0]
{MapperTestApp.Program.Element}
    Items: Count = 3
source.Elements[1]
{MapperTestApp.Program.ElementX}
    Items: Count = 3

target.Elements[0]
{MapperTestApp.Program.ElementDto}
    Items: Count = 3
target.Elements[1]
{MapperTestApp.Program.ElementXDto}
    Items: Count = 0
```

### Note
Same if exact map `ElementX` to `ElementXDto`. Problem can be resolved by adding `UseDestinationValue` into `ElementX` to `ElementXDto` mapping, but why??? I almost configured it for `Element` to `ElementDto` mapping, and `ElementX` to `ElementXDto` mapping should include it. It looks like I need to configure same things twice, and this is simple example with just one derived class. In this case `Include` or `IncludeBase` looks useless, or works incorrect. Same in #2188, but used option is `PreserveReferences`.

**Comment by jbogard** [comment]
This is what is inherited:

https://github.com/AutoMapper/AutoMapper/blob/master/src/AutoMapper/PropertyMap.cs#L116

In general, I've tried to only inherit things that can be overridable. Since you can't un-preserve references or un-"UseDestinationValue", I've left them alone.

Honestly those should have been properties so you could set them however you like.

**Comment by ds1709** [comment]
I think you should discuss this to rework. In general case, as I assume, there's no need to override this options, and they should be inherited. If i "say" "I need to preserve references" or "I need to use destination value", in general case it should be go derived classes too.

**Comment by antoinebj** [comment]
Any reason why this has been closed? I've face this exact problem in my project, and it feels awkward to have to repeat the same configuration on child mappings that inherit everything else.

The main (and currently only) case where I set `UseDestinationValue` is to force mapping for read-only collection properties.
For anyone stumbling upon this, if it helps, as a workaround for my use case I've used `ForAllPropertyMaps()` to detect if the destination member is a read-only property of a collection type (`ICollection` or `ICollection<>`, and then set `UseDestinationValue`. That way, I don't even have to write `UseDestinationValue` anymore in my mappings.

Here is an early shot at it:
```csharp
var mapperConfiguration = new MapperConfiguration(cfg =>
{
    cfg.ForAllPropertyMaps(propertyMap =>
    {
        if (propertyMap.UseDestinationValue)
        {
            return false;
        }

        if (!(propertyMap.DestinationProperty is PropertyInfo propertyInfo) || propertyInfo.CanWrite)
        {
            return false;
        }

        bool IsCollectionType(Type type) =>
            type.GetInterfaces().Any(i =>
                (i.IsGenericType && i.GetGenericTypeDefinition() == typeof(ICollection<>))
                || (!i.IsGenericType && i == typeof(ICollection)));

        return IsCollectionType(propertyMap.DestinationPropertyType);
    }, (p, o) => o.UseDestinationValue());
    // calls to .CreateMap here
});
```

**Comment by lbargaoanu** [comment]
Nobody is interested to work on it, that's why it was closed.

**Comment by antoinebj** [comment]
I'm interested to work on it ASAP. I noticed that UseDestinationValue is not even inherited even when it makes no sense for it not to be. It's very counter-intuitive and I've lost a few hours on this at least twice.

Take the following:
```csharp
public class SubObject
{
    public string Value { get; set; }
}

public class SourceBase
{
    public SubObject SubObject { get; } = new SubObject();
}

public class Source : SourceBase
{
}

public class DestinationBase
{
    public SubObject InnerObject { get; } = new SubObject();
}

public class Destination : DestinationBase
{
}
```

Configure the mapping as such:
```csharp
new MapperConfiguration(cfg =>
{
    cfg.CreateMap<SubObject, SubObject>();

    cfg.CreateMap<SourceBase, DestinationBase>()
        .ForMember(dest => dest.InnerObject, opt =>
        {
            opt.MapFrom(src => src.SubObject);
            opt.UseDestinationValue();
        });

    cfg.CreateMap<Source, Destination>()
        .IncludeBase<SourceBase, DestinationBase>();
});
```

And map it like that:
```csharp
var source = new Source { SubObject = { Value = "Success" } };
var destination = mapper.Map<Source, Destination>(source);
```

There is no specific mapping on the derived types, and no convention-based property map gets generated as the properties `InnerObject` and `SubObject` have different names.
So it would be very surprising that the mapping defined on the base types not apply exactly as it is defined, right? Well, it doesn't. `UseDestinationValue` is ignored.
It does go to the trouble of creating a new instance of `SubObject` and mapping it from the source, but that new instance then gets garbage collected as it ends up nowhere. So it does some work, but for nothing.

The most obvious reason is the call to the `new PropertyMap(inheritedMappedProperty, this)` in `TypeMap.ApplyInheritedTypeMap()` (I'm on the 7.0.1 code base as I write).
That happens when it did not find an existing property map on the derived type map. So the expected behaviour is to take the property map from the base types exactly as it is, as there is no reason not to and every reason to.
Unfortunately, that constructor of `PropertyMap` relies on the same `ApplyInheritedPropertyMap()` that is used for existing property maps (which is where Jimmy said he did not want to risk overwriting what could not be overriden).
Therefore `UseDestinationValue` is not applied.

Another problem might be in the mapping plan.
This is the generated expression, when inheriting the property map defined for base types:
```csharp
(src, dest, ctxt) =>
{
//...
    typeMapDestination = dest ?? new UseDestinationValueInheritance.Destination();
//...
    var propertyValue =
    {
//...
        typeMapDestination = ((dest == null) ? null : typeMapDestination.InnerObject) ?? new UseDestinationValueInheritance.SubObject();
//...
    }
//...
    return typeMapDestination;
}
```
(this is not exactly correct C# because it re-uses the same variable names for different types, it's just an illustration of the Expression tree by the ReadableExpressions VS extension)

Look at `(dest == null) ? null`.
`dest` is the `Destination` object, it is null when we're mapping like that: `mapper.Map<Source, Destination>(source)`
The mapping plan does create an instance of `Destination` at the very beginning, but that instance is not in the `dest` argument which remains null throughout.
So a new `SubObject` is instantiated, but as the destination member is read-only, it does not get set to that new instance, which just ends up in the ether.

If, however, we map like that: `mapper.Map<Source, Destination>(source, destination)` where `destination` is a pre-instantiated object, then it works fine becaue the `dest` argument is not null.
I think that there should not have been such a difference in behavior between the calls to the two different overloads of the `Map()` method.

For reference, when defining the property map directly for derived types, this is how the line looks:
```csharp
typeMapDestination = typeMapDestination.InnerObject ?? new UseDestinationValueInheritance.SubObject();
```

As you can see, in that case it does not check `dest` and so takes the destination value from the instance that was created by the mapping plan. It works fine.

So, to sum up, it looks like there are 2 problems to fix.

The first problem can have a relatively easy fix that would be to enrich the `UseDestinationValue` property.
Of the top of my head, I'd say it could be based on a nullable private field. When calling `ApplyInheritedPropertyMap()`, if the field is null, we inherit, otherwise, we leave it as it is.
Then we can also add a `DoNotUseDestinationValue()` configuration method to override it to false in maps for derived types.

For the second problem, which is the mapping plan and its expression tree, even though what is generated looks not OK to me (specifically the `(dest == null) ? null` bit), I'm a bit more wary on changing anything.
I can make the effort of looking deeper into it, but if anyone has better insight, I would gladly leave it to them.

Anyway, before I go forward with coding anything and making a PR, I need to know a few things:
1. Are the owners of this project OK with my analysis? Any remarks?
2. Does anyone else want to take this matter in their hands, or is it OK for me to own it and make the PR?
3. As this issue is closed, should I create a new issue and copy this post there, or can this one be re-opened? (I will do it if I don't get any reply in the next couple of weeks)

**Comment by antoinebj** [comment]
Inline, AllowNull and ExplicitExpansion could also need the same treatment.

**Comment by lbargaoanu** [comment]
Let's start simple with a PR to inherit the setting and DontUseDestinationValue. Please open a new issue.

**Comment by antoinebj** [comment]
Ok
