### ISSUE TITLE
Feature / Question: combine ProjectTo with existing collection

### ISSUE THREAD

**Issue by JanEggers** [AutoMapper/AutoMapper#2231]
### Version: 
AutoMapper 6.1.1
AutoMapper.Collections 3.0.1

### Expected behavior

im searching for an api to project a queryable into an existing collection 

### Actual behavior

i have two options:

`source.ProjectTo<TTarget>();`
positive: best possible query generation
negative:  creates a new list of TTarget

`Mapper.Map(source.ToList(), targets);`
positive:  existing targets are updated 
negative: many lazy queries are executed because source.ToList() doesnt include all required joins like projectto

**Comment by lbargaoanu** [comment]
Why an existing collection?

**Comment by JanEggers** [comment]
im in a wpf mvvm scenario and i have a observable collection of view models replacing the collection will trigger much work for wpf. so bad ui perf.

**Comment by lbargaoanu** [comment]
OK, but there are things in WPF for batch changes (smth like Begin/End or Suspend/Resume change notifications). Doesn't that help?

**Comment by JanEggers** [comment]
no it doesnt help. i have 50 visible rows with 10 visible columns (500 cells) in a datagrid with (10000) entries in the list. view virtualization is enabled.

if i replace the list and raise a property change wpf will rebind to the new list and layoutupdate will be triggered for 500 visible cells

if i just update what actually changes there are 2 - 5 property changes on some of the rows. so wpf updates 2 - 5 cells. and that is 100 times faster, at least. 

anyway i dont want to discuss my usecase, 

i currently use projectto and after that i merge that list with an existing list with some equal and gethashcode.

i just wanted to know if there is a better way.

**Comment by lbargaoanu** [comment]
No, there isn't. 500 cells doesn't sound like a lot.

**Comment by JanEggers** [comment]
oki

**Comment by lbargaoanu** [comment]
I'm not exactly familiar with AM.Collections, but you could try mizing the two. ProjectTo and map the result into your final collection.

**Comment by TylerCarlson1** [comment]
What @lbargaoanu said.  Although I've never tried mapping source to itself with AM.Collections
Add 
`cfg.CreateMap<TTarget,TTarget>().EqualityComparer((s, d) => s.ID == d.ID)`
Or whatever it is to uniquely identify and map using
```
var from = source.ProjectTo<TTarget>().ToList();
Mapper.Map(from , targets);
```
and you get the best performance of both systems.

Also AM.Collections 3.1.x uses hashes for faster comparisons for larger collections.  3.0.1 had some improvement from before but 3.1 is even faster than this by a large factor.  Which probably has same perf to what you are using now.

As far as projection API to existing collection that seems unlikely because either you have to map object to itself, which isn't recommended by AM Standards, or you have to define an intermediary object and make a query extension for that.
