### ISSUE TITLE
Cite NeinLinq in our license

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#2235]
I missed it, but a PR included some code copied from the NeinLinq project:

https://github.com/AutoMapper/AutoMapper/blob/master/src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs#L339

We should cite this in our license https://github.com/axelheer/nein-linq

cc/ @axelheer

**Comment by mario-d-s** [comment]
@jbogard @axelheer 

I'm not super experienced with legal stuff, but most of it is made pretty clear on pages such as [Open Source Initiative's FAQ](https://opensource.org/faq) and [Managing Copyright Information on Softwarefreedom.org](https://softwarefreedom.org/resources/2012/ManagingCopyrightInformation.html).
https://opensource.guide/legal is also helpful.

Having skimmed through those, here's the gist of what I think applies in this specific situation:

1. AutoMapper's [License.txt](https://github.com/AutoMapper/AutoMapper/blob/master/LICENSE.txt) says this entire project's source code is **by default** licensed under MIT license at the time of writing.
2. Licenses can be scoped to different parts of the source code, and one scope widely recognized is **file scope**.
3. Nein-linq is also licensed under MIT, that means the copy that is present in this code-base also falls under that license (since it doesn't have a file-scope license).
4. MIT license says
> [...] The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

Given those points, what I think should happen is:

- Isolate the code contained in https://github.com/axelheer/nein-linq/blob/master/src/NeinLinq/NullsafeQueryRewriter.cs to a separate file. I think C#'s `partial` mechanism will be particularly helpful here since it's contained as a nested class.
- Prepend the MIT license to that file, along with original source and mention of the original author.

The second point is important because this allows AutoMapper's own license to change in the future without affecting the included code.

If this makes sense, I'd be happy to open a PR.

Thoughts?

**Comment by axelheer** [comment]
Makes sense, thank you!

**Comment by lbargaoanu** [comment]
Fixed by #2610.
