### ISSUE TITLE
Apply same condition for multiple destination members

### ISSUE THREAD

**Issue by raihaniqbal** [AutoMapper/AutoMapper#2236]
Hi,

Basically certain properties in the destination DTO need to mapped only if the `Entity` property in the source object is not null. I have mapped two members in the code below but I have more to map using the condition.

`CreateMap<PersonMaster, PersonSummaryDto>()
                .ForMember(d => d.Id, o => o.MapFrom(s => s.Id))
                .ForMember(d => d.GivenName, o => o.MapFrom(s => s.Contact.GivenName))
                .ForMember(d => d.Surname, o => o.MapFrom(s => s.Contact.Surname))
                .ForMember(d => d.Email, o => o.MapFrom(s => s.Contact.Email))
                .ForMember(d => d.TemplateId, o =>
                {
                    o.Condition(s => s.Entity != null);
                    o.MapFrom(s => s.Entity.TemplateId);
                })
                .ForMember(d => d.TemplateName, o =>
                {
                    o.Condition(s => s.Entity != null);
                    o.MapFrom(s => s.Entity.Template.Name);
                });`

**Comment by lbargaoanu** [comment]
This has been discussed many times before. See https://github.com/AutoMapper/AutoMapper/issues/1703#issuecomment-250137782 for example.

**Comment by raihaniqbal** [comment]
I dont see how it's related to my question. I cant use the ForAllOtherMembers method because the condition applies only to certain members. Also the solution provided does not work for 4.1. I cant update to the latest version due to various project constraints.

**Comment by Dan-True** [comment]
**lbargaoanu**: This is different from the issue your linking too.

We're experiencing the same as the generated linq expression after a ProjectTo<T> on a Queryable has a lot of rendundant selects.

In the above example, instead of:

.ForMember(d => d.GivenName, o => o.MapFrom(s => s.Contact.GivenName)) 
.ForMember(d => d.Surname, o => o.MapFrom(s => s.Contact.Surname)) 
.ForMember(d => d.Email, o => o.MapFrom(s => s.Contact.Email)) 

We would like to be able to reuse the s.Contact call, so it doesn't generate three reduncant equivalent selects (in our case, because our equivalent is a Computed field) which in turn becomes three redundant SQL joins.

**Comment by lbargaoanu** [comment]
@Dan-True A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by Dan-True** [comment]
For us, the problem is quite complex (we're projecting OData queries onto models with computed fields). For a mapper with 10 fields, the resulting decompiled queryable became a 5 MB SQL expression when executed by EF, with extreme nesting. 

For *our* case, it may not even be automapper that's the point to look at the solution and I don't expect you to handle such an extreme case. I just wanted to point out the OP was not the same issue as what you linked to, as far as I can tell. He just wanted a way to avoid specifying .Contact in a hundrd MapFrom() statements.

Will see if I can boil down the problem into a simple example over the weekend.
