### ISSUE TITLE
Constructor mapping and NullSubstitute

### ISSUE THREAD

**Issue by dlfsdev** [AutoMapper/AutoMapper#2265]
### Source/destination types

```csharp
private sealed class Source
{
    public Source(object theObject)
    {
        TheObject = theObject;
    }

    public object TheObject { get; }
}

private sealed class Destination
{
    public Destination(object theObject)
    {
        TheObject = theObject;
    }

    public object TheObject { get; }
}
```

### Mapping configuration

```csharp
Mapper.Initialize(cfg =>
{
    cfg.CreateMap<Source, Destination>()
        .ForMember(d => d.TheObject, e => e.NullSubstitute(new object()));
});
```

### Version: x.y.z
 
6.1.1

### Expected behavior

When mapping `Source source` to `Destination destination`, if `source.TheObject` is null, `destination.TheObject` will be set to the provided null substitute (`new object()`). This works when `Destination` has a default constructor and `Destination.TheObject` is settable.

### Actual behavior

`destination.TheObject` is set to null

### Steps to reproduce

```csharp
[TestMethod]
public void NullSubstituteWorks()
{
    var source = new Source(null);
    var destination = Mapper.Map<Destination>(source);
    Assert.IsNotNull(destination.TheObject);
}
```

**Comment by lbargaoanu** [comment]
Constructor mapping is different from property mapping and the null substitute only applies for property mapping. So this is a feature request. It could work like ForCtorParam [here](https://github.com/AutoMapper/AutoMapper/wiki/Construction). But then I guess it's easier to do it by hand :)

**Comment by lbargaoanu** [comment]
cc @jbogard

**Comment by jbogard** [comment]
Should we open a new GH issue for this feature request?

**Comment by lbargaoanu** [comment]
I don't know :) Technically we map from a source property to a constructor parameter, not to a destination property. But clearly many times that parameter has a corresponding property. And we actually consider that when we don't do property mapping because we did constructor mapping. But we did add ForCtorParam instead of using an existing MapFrom. I'd say most people see them as equivalent, but they aren't exactly, so the implementation might suffer.
