### ISSUE TITLE
Enforce calling Mapper.Initialize once

### ISSUE THREAD

**Issue by lbargaoanu** [AutoMapper/AutoMapper#2295]
I've seen people calling it more than once again and again. It might break some scenarios, but maybe they should use the instance based API or make their own statics.

**Comment by jbogard** [comment]
Would we include an option to reset? Or maybe include that old `Mapper.Reset` method?

**Comment by lbargaoanu** [comment]
I'd say no. It's weird to do that, how do you know it's safe? I'm sure there are scenarios where you do know, but there are alternatives and we would prevent misuse in the general case. Of course we'll see how people feel about that :)

**Comment by mscrivo** [comment]
While I applaud the intent here, I'm a bit curious how to achieve the scenario where you have tests that run in the same app domain, but you'd like to setup and tear down their DI containers and thus mapping configuration on each run, or given set of tests?

**Comment by lbargaoanu** [comment]
You should use the object based API. Two MapperConfiguration objects shouldn't share anything.

**Comment by mscrivo** [comment]
Thanks @lbargaoanu, when you say object based API?  can you be a little more specific or provide a link to the docs that shows what you mean?

**Comment by lbargaoanu** [comment]
http://automapperdocs.readthedocs.io/en/latest/Configuration.html

**Comment by mscrivo** [comment]
I assume you mean to prefer this:

`var config = new MapperConfiguration(cfg => cfg.CreateMap<Order, OrderDto>());`

over this?

`Mapper.Initialize(cfg => cfg.CreateMap<Order, OrderDto>());`

That's a rather big change for us as we don't inject an IMapper in our DI container, instead we use the static Mapper.   I'd be nice, if we had the Reset function, with a big warning to only use for test scenarios?

**Comment by jbogard** [comment]
What do DI containers have to do with mapping configuration? You shouldn’t
be reconfiguring a container for every test.

**Comment by lbargaoanu** [comment]
I don't think that's such a big change, we certainly did it :) You can always implement your own static that behaves that way.

**Comment by mscrivo** [comment]
@jbogard Why shouldn't we be reconfiguring the container for every test or at least sets of tests?   How would you achieve scenarios where you want to test with in-memory implementations, rather than real ones without overriding or re-configuring the container?  

The way we have our system setup is that each area has a DI registry where you register the components required for that area.  Our mapping configs are tied to these registries, and in the real app, at the end of the day, all these registries get loaded up into the container and all the associated mappings as well and InitalizeMappings is called once and all is good.  But in our tests, we want to test with only the registries for the area we're testing, and thus the need to reconfigure the container.  

Anyhow, I agree it's probably a good design decision to enforce the call only once, so we'll find a way to work around it. Thanks.

**Comment by jbogard** [comment]
Use child containers for specific config for a single test, that’s how I’ve
handled it.

I’d be careful with tests only loading part of the DI config though. Try to
match production as much as possible.
