### ISSUE TITLE
ReplaceMemberName with RecognizePrefixes fails to map

### ISSUE THREAD

**Issue by worknate** [AutoMapper/AutoMapper#2339]
### Version: 6.1.1

I ran into an issue today trying to use both RecognizePrefixes and ReplaceMemberName in a profile. 

### Expected behavior

I would expect the two to work together in a config; if I remove either, the config works as expected.

### Actual behavior

When both RecognizePrefixes and ReplaceMemberName are present, any property that relies on ReplaceMemberName is not mapped.

### Steps to reproduce

Unit test gist [here](https://gist.github.com/worknate/446d390132748b8517f931c2cddfb36c), includes a couple different destination examples, and separate tests for the config validation and the mapping in action.

For now I can just leverage ForMember, but I'd like to come up with a way to do a handful of substitutions, instead of a lot of manual mapping for dozens of entities.

**Comment by KoditkarVedant** [comment]
@lbargaoanu @worknate Hey guys, I was thinking of working on this issue but I unable to understand the test cases given by @worknate in gist.

@worknate as you're saying it works properly when you use either of the RecongnizePrefixes and ReplaceMemeberName in config. But I found that for Replace_ConfigAssert_IsValid() test case you are creating the map between **c.CreateMap<source, DestinationReplace>();** when I look at the DestinationReplace class it has following.
```
public class DestinationReplace
        {
            public int AsKey { get; set; }
            public int? AsUsKey { get; set; }
        }
```
and as I can see it works..

For **public void Prefix_Replace_NoConfigAssert_IsValid()** test case you've combine both RecognizePrefixes and ReplaceMemberName in a profile and creating the map for **c.CreateMap<source, Destination>();** and when I look at Destination class it has following.

```
public class Destination
        {
            public int Key { get; set; }
            public int? UserKey { get; set; }
        }
```
and does not work.

But as you can see you used the **AsUsKey** in DestinationReplace class while using a ReplaceMemberName but while using the both config you used UserKey as destination key in Destination class but when you replace the **UserKey** to **UsKey** in Destination class then the configuration work just fine.

So I'm little confused that whether you want to say that both **RecognizePrefixes** and **ReplaceMemberName** in a profile doesn't work or **ReplaceMemeberName** config method doesn't work in then first place.@lbargaoanu @worknate Hey guys, I was thinking of working on this issue but I unable to understand the test cases given by @worknate in gist.

@worknate as you're saying it works properly if you use either of the **RecongnizePrefixes** and **ReplaceMemeberName** in a Profile and it doesn't work if you use both of them in a Profile.

But I found that for **Replace_ConfigAssert_IsValid()** test case you're creating the map between **c.CreateMap<source, DestinationReplace>();**. I look at the DestinationReplace class and it has following.
```
public class DestinationReplace
{
	public int AsKey { get; set; }
	public int? AsUsKey { get; set; }
}
```

For **Prefix_Replace_NoConfigAssert_IsValid()** test case you've both RecognizePrefixes and ReplaceMemberName in a profile and creating the map between **c.CreateMap<source, Destination>();** I look at Destination class it has following.
```
public class Destination
{
	public int Key { get; set; }
	public int? UserKey { get; set; }
}
```

But as I can see you've used the **AsUsKey** in DestinationReplace class while using a ReplaceMemberName in Profile but while using the both config you used **UserKey** in Destination class but when you replace the **UserKey** to **UsKey** in Destination class then the configuration work just fine.

So I'm little confused, whether you want to say that both **RecognizePrefixes** and **ReplaceMemberName** in a profile doesn't work or **ReplaceMemeberName** config method doesn't work in the first place. 

Because it look like the **ReplaceMemberName** config method doesn't work in the first place.

**Comment by lbargaoanu** [comment]
@KoditkarVedant It's definitely convoluted, but I tend to see it his way. The two tests pass and the other two don't. I think the models make sense and it seems indeed RecognizePrefixes and ReplaceMemberName don't work together.

**Comment by worknate** [comment]
My apologies... there's a lot going on. I wanted to be thorough.

Here are the tests that matter:

https://gist.github.com/worknate/619f860c2ff782ab78554df9b36b0274

1. **AssertConfigurationIsValid()** fails
2. the actual mapper fails

This problem only happens when using _both_ **ReplaceMemberName** and **RecognizePrefixes**

Here are passing tests to show they work separately: [RecognizePrefixes](https://gist.github.com/worknate/95d445dd228bdd430953d773676444bd), [ReplaceMemberName](https://gist.github.com/worknate/5897f6c9692bfb3262a13d44a23c5cd7).

**Comment by lbargaoanu** [comment]
PR welcome.
