### ISSUE TITLE
Wrong mapping with CAST suffix

### ISSUE THREAD

**Issue by xkubow** [AutoMapper/AutoMapper#2365]
When I have field with suffix CAST it will map incorrectly. When I change the suffix CAST to something else (CAST1) it maps correctly. How should I set the mapper to map correctly with the suffix CAST?

### Source/destination types

```csharp
public class Source
{
    public string OBEC { get; set; }
    public string OBEC_CAST { get; set; }
}
public class Destination
{
    public string Obec { get; set; }
    public string ObecCast { get; set; }
}
```

### Mapping configuration

```csharp
    Mapper.Initialize(cfg =>
    {
      cfg.ClearPrefixes();
      cfg.SourceMemberNamingConvention = new LowerUnderscoreNamingConvention();
      cfg.DestinationMemberNamingConvention = new PascalCaseNamingConvention();
      cfg.CreateMap<Source, Destination>();
    });
```

### Version: x.y.z
 
4.2.0 

### Expected behavior

Obec = "obec", 
ObecCast = "cast obce"

### Actual behavior

Obec = "obec", 
ObecCast = "obec"

### Steps to reproduce

```csharp
    Source c1 = new Class1() { OBEC = "obec", OBEC_CAST = "cast obce" };
    Destination c2 = Mapper.Map<Destination>(c1);
```

**Comment by lbargaoanu** [comment]
The default naming convention will try to call [this](https://msdn.microsoft.com/en-us/library/bb341406(v=vs.110).aspx). So you should use another name. I don't think you can ignore already added extension methods, such as IEnumerable.

**Comment by xkubow** [comment]
I can't change the name.

**Comment by lbargaoanu** [comment]
Then I guess you'll have to map it explicitly

    cfg.CreateMap<Source, Destination>().ForMember(d=>d.ObecCast, o=>o.MapFrom(s=>s.OBEC_CAST));

**Comment by xkubow** [comment]
So if I defined that I don't want to use prefixes/suffixes it will use it against the configuration?
Is it documented somewhere what kind of prefixes/suffixes will by mapped incorrectly (used extension methods etc.) against that I defined that I don't want use them?

**Comment by jbogard** [comment]
Hmmmm I would think we would prefer member mapping matches over extension
method names. I think this is a bug?

**Comment by lbargaoanu** [comment]
It makes sense, but I don't think the code tries to do that now.

**Comment by TylerCarlson1** [comment]
It picks first in list that matches.  And yes it calls Cast like @lbargaoanu says.  String is an IEnumerable of char's.  We have to explicitly ignore strings in enumeration logic because of this fact.

Also it takes the first match it finds.  If you put OBEC_CAST in front of OBEC it should map correctly.
ObecCast can be mapped from either OBEC_CAST or OBEC by the rules stated.  So first property to match wins I'm guessing.

I don't know the extension logic off the top of my head.  You should be able to add to it but I'm not sure how you can remove extensions from the configuration.  Have to look into that more.

**Comment by jbogard** [comment]
I think it's just that we don't have a precedence. We're not checking all
instance methods before moving on to extension methods.

**Comment by jbogard** [comment]
Ah, I've found the problem! Your source naming convention is wrong. You've told AutoMapper that the naming convention is 'LowerUnderscoreNamingConvention', which means the members are so:

`foo_bar_baz`

With that naming convention, AutoMapper will split the string based on underscores and treat it like a series of members:

`["foo", "bar", "baz"]`

Then look for members that match that combination of members on the destination. Not `FooBarBaz`. In your case, AutoMapper matches `Opec.Cast` because it split your source members as `["opec", "cast"]`. Technically it did the right thing :)

The naming convention you chose is typically for destination types, especially those from Ruby communities that use underscores to separate member names and such.

What you *really* want to do is remove those underscores. Change your config to:

```
    Mapper.Initialize(cfg =>
    {
      cfg.ReplaceMemberName("_", "");
      cfg.CreateMap<Source, Destination>();
    });
```

And it works!

**Comment by xkubow** [comment]
So when I use PascalCaseNamingConvention that means the ObecCast will be processed same as in the LowerUnderscoreNamingConvention? It will look for destination types like Obec.Cast? Don't know if the naming convention should be used for the structural case. Or you could use custom definition for the structural separator.

The config solution worked,
Thanks.

**Comment by jbogard** [comment]
The `PascalCaseNamingConvention` is the default, but in general, naming conventions are how to split a member name up. `OBEC_CAST` did not exactly match `ObecCast` because of that underscore. When names don't match exactly, we go through the split up names of the members to see if we can get a member map (`Foo.Bar.Baz`). This is how we go `Foo.Bar.Baz` -> `FooBarBaz`.

We have to start with the destination member first, and see what on the source it could map to. Naming conventions don't make as much sense on the source type because you're typically doing flattening or 1:1 exact matches.

**Comment by xkubow** [comment]
When I use the example from begin and swap `OBEC_CAST` to `OBECT_CASTA` it will mapp correctly.  What is the difference between `OBEC_CAST` and `OBEC_CASTA`? Shouldn't bout `OBEC_CAST` and `OBEC_CASTA` behave similar?

And The configuration you presented with the `ReplaceMemberName("_", "");` will not work when you have for example PNV_OBEC and PNVOBEC. Those two properties will end up with same value.

What should be the correct configuration for uppercase naming separated with underscore to PascalCase?

**Comment by jbogard** [comment]
Sure! It might be helpful to explain how AutoMapper matches members up.

First, we support flattening. That means a collection of member names maps to a single member name. "Foo.Bar.Baz" can map to "Foo.Bar.Baz" or "FooBar.Baz" or "Foo.BarBaz" or "FooBarBaz"

Second, we start from the destination to determine what/how to map. We loop through all the destination members and compare that to the source members to see what matches.

Finally, we combine the two sets of rules with naming conventions to determine how to split up member names to match to a collection of members. Naming conventions break up `"FooBarBaz"` to `["Foo", "Bar", "Baz"]`. It's complicated regular expression to do so, but the end result is a collection of member names.

With that collection of member names, we go back to the other type to see how we can match things up to the parent and child types.

Let's go back to your example. You have two destination members with a similar name:

```
Obec
ObecCast
```

AutoMapper first tries to match the names exactly, then falls back to your naming convention's rules.

So what does a naming convention do here? Instead of matching *directly* against the type's member names, it processes them to get a series of transformed names. The naming convention transforms the one type's member names into a common form.

In your example, you first applied a naming convention with underscores. That particular naming convention tells AutoMapper to *split* names on underscores, not ignore them. So `OBEC_CAST` transforms to `["obec", "cast"]`.

This is a problem! We can no longer match on the destination to `ObecCast` as we've told AutoMapper that there are actually two member names to search, "obec" and "cast".

Naming conventions are about flattening rules. Going from a complex "Foo.Bar.Baz" navigation to a single property, but how is that property's name constructed? Just removing navigations? Adding underscores? Adding emoji? That's what naming conventions do.

Finally, the example you showed seems to be a naming collision. You have to describe what the member names on *both* sides are to see what the right rules should be.

**Comment by xkubow** [comment]
Still don't understand why is the behavior different for my example `OBEC_CAST` / `OBEC_CASTA`. 
When I mapp:
```
public class Source
{
    public string OBEC { get; set; }
    public string OBEC_CAST { get; set; }
}
public class Destination
{
    public string Obec { get; set; }
    public string ObecCast { get; set; }
}

```
The result will be  :
```
Obec = "obec",
ObecCast = "obec"
```

But when mapping :
```
public class Source
{
    public string OBEC { get; set; }
    public string OBEC_CASTA { get; set; }
}
public class Destination
{
    public string Obec { get; set; }
    public string ObecCasta { get; set; }
}
```

The result will be  :
```
Obec = "obec",
ObecCast = "cast obce"
```

There shouldn’t be naming collision because when you have property OBECCAST and OBEC_CAST and will it mapp to Obeccast and ObecCast those are different properties and should be processed that way.

**Comment by jbogard** [comment]
Sure!

I'm assuming you're talking about when you use the naming conventions. Which you shouldn't - that's about splitting a member name up to match to a complex navigation. You have two flat models, so naming conventions don't apply.

Now why does your mapping get screwed up? You've told AutoMapper to split member names on an underscore.

So what you actually mapped was OBEC_CAST to Obec.Cast<string> because you've split member names to ["obec", "cast"]. Well it turns out that does match a complex mapping to `Obec.Cast` using extension methods in IEnumerable.

So what it "should" do depends on your configuration. You'll have to tell me how you've configured things before I can tell you what it "should" do.

If there's anything you take away here (and me too, it's not documented well), naming conventions are for configuring how members get flattened. You are not flattening in the above example. Don't use a naming convention.

**Comment by xkubow** [comment]
By using the same configuration that is at beginning (the wrong LowerUnderscoreNamingConvention). I understand that is for flattening. But why is result different for OBEC_CAST versus OBEC_CAST**A**? Shouldn't be the same result? Both are splitted and both should by mapped to the first finding, what is OBEC. But the result for OBEC_CAST is ObecCast = "obec" and for the second is ObecCast**a** = "cast obce". Why is there the difference?

Ok I will not use naming convention.
What is correct setting for my purpose that will map uppercase word separated with underscore to Pascal case?

**Comment by jbogard** [comment]
The reason why "Casta" works is because of the flattening conventions of the destination type. The destination members have *also* been split to `["Obec", "Casta"]` and the source members split to `["obec", "casta"]`.

I posted something that will fix the specific use case, but to know if it truly is going to work - what is your overall naming convention for destination members? What rules do you want? Drop the underscores, compare case-insensitive? Split each string differently (underscores vs. PascalCase)?

You had a naming collision, so the first member that matched won. `OBEC.Cast()` was considered before `OBEC_CAST` because we do a complete search for one member (`OBEC`) before moving on to the next (`OBEC_CAST`).

The problem with collisions is there's no real consensus on what the "right" way to handle naming collisions should be. You're in a weird spot because the naming collision was an extension method, and right now you can't remove the build-in ones.

**Comment by xkubow** [comment]
OK I now understand that case. I forgot that extension method :).

Yes the source should by separated by underscore and the destination by first uppercase (PascalCase). Comparison could be case-insensitive (you have already defined word separation), this should be working correctly.

I think that there should by option to define the world separator for flattening and word separator for name comparison. In the name collision I would prefer the name comparison before flattening because I think that’s what you want in first place (correct property mapping). Then you could use some settings to enable other mapping options like flattening.

**Comment by jbogard** [comment]
One other thing - you're using "word separator" in a different context than AutoMapper. For AutoMapper, word separators are all about figuring out flattening rules. You're not flattening. For you, these are member name transformation rules.  Transform the source member name before comparing *directly* to a destination  member name.

I realize this is a bit complicated, but I agree, this can be made more explicit. Having different flattening vs. comparison vs. transformation rules.

**Comment by xkubow** [comment]
Ok could you point me to right way to set the member name transformation rule (method, class, url to documnetation)? Is it Automapper seting or I have to use other options?

**Comment by jbogard** [comment]
Removing the underscore is the right way to go here from waaaaaaay up at the top. That transforms the source member names before comparison.

And I agree, this is confusing. There are lot of levers to pull here and not really documented.

**Comment by xkubow** [comment]
Thats not very good way for comparing properties by name. You have to keep the world separated to corectly compare. You can have same two names with and without separator and both mean something diferent.

**Comment by jbogard** [comment]
OK. I have this destination property:

`FooBar`

And on my source type, I have:

`FOO.BAR`
`FOO_BAR`

Which one wins? Why?

**Comment by xkubow** [comment]
In my option FOO.BAR is for flattening so I would prioritize the FOO_BAR. It depends what have byger priority. Is it methods or property of the owning objects or is it the property of the owner.

**Comment by jbogard** [comment]
And that's how it works today - we prefer members at the root type before considering child members.

However, naming conventions tell us how to split flattened members for comparison. Lower_underscore convention is there for `Foo.Bar` -> `foo_bar` (as opposed to `FooBar`).

That's why I see 3 things - transforming, splitting, and comparing. Transforming are also things like prefixes/postfixes. Splitting is about flattening - how does a series of member accessors translate into a single member name? Finally comparing.

"LowerUnderscoreNamingConvention" combines two things - splitting by underscore for flattening rules, AND calling "ToLower" for transformation.

**Comment by xkubow** [comment]
If I implement transforming, splitting, and comparing then I can do my own mapper. Consider better setting for comparing (word splitting etc...).

**Comment by jbogard** [comment]
lol touche.
