### ISSUE TITLE
Empty string maps to DateTime.MinValue

### ISSUE THREAD

**Issue by jaxidian** [AutoMapper/AutoMapper#2452]
The issue is when the Source is an empty string and the target is a nullable DateTime. Perhaps other cases as well but this is specifically the one hitting us right now as we upgraded from 6.1.1 to 6.2.1. Turns out the breaking change happened in 6.2.0. For now, we're just reverting to 6.1.1 until this is resolved.

### Expectations
I expect the nullable DateTime property to be set to null. This is what happens in 6.1.1. However, in 6.2.0, it instead sets it to 1/1/0001. If the target property was not nullable, then this is what I would expect. But as a nullable target, I'd expect null in this case since there was no date in the source.

### Steps to reproduce
Here is an nunit test to reproduce the issue (I'm just using Nuget to quickly change versions to test quickly). This test case passes in 6.1.1 (and many versions prior) but fails in 6.2.0 and 6.2.1.

```csharp
    public class FooA
    {
        public string Prop { get; set; }
    }

    public class FooB
    {
        public DateTime? Prop { get; set; }
    }

    [TestFixture]
    public class MapperTest
    {
        [OneTimeSetUp]
        public void Setup()
        {
            Mapper.Initialize(cfg =>
            {
                cfg.CreateMap<FooA, FooB>();
            });
        }

        [Test]
        public void Tests()
        {
            var a = new FooA { Prop = "" };
            var b = Mapper.Map<FooB>(a);

            Assert.That(b.Prop, Is.EqualTo(null));
        }
    }
```

**Comment by lbargaoanu** [comment]
@jbogard This seems to happen because of the nullable destination mapper. An empty string is not null and it will never map to null.

**Comment by SProst** [comment]
This is a breaking change for anyone who has code that relied on empty strings to map to null for nullable DateTimes. Why wasn't this included in the release logs?

**Comment by ericaho** [comment]
I would like to throw in my own "this affects me too."   

We rolled back to 6.1.1 because we have unit tests explicitly checking the assumption that an empty string will map into a null datetime.  At this time, we will probably freeze at this version until we determine if this will be resolved, or if we need to possibly modify our codebase to support special case-checking for for every nullable type we map (application-wide) from when using 6.2.x forward.

**Comment by jbogard** [comment]
Because this is weird behavior I’d never expect?

It’s fairly trivial to add your own behavior for this. Create a map from
string to DateTime? to do the logic you want.

**Comment by jbogard** [comment]
And just to clarify the original behavior you describe is accidental. It’s
not in the release notes because I didn’t know this was what it used to do
(and there was not a test for your behavior).

But like I said, it’s trivial to configure AutoMapper to have the behavior
you want, I’d go that route.

I generally try not to break core mapping behavior but what you’re
describing wasn’t an intended behavior.
