### ISSUE TITLE
Wrong destination property is mapped with upper case underscore destination members

### ISSUE THREAD

**Issue by vincechan** [AutoMapper/AutoMapper#2546]
### Source/destination types

```csharp
public class MyDestType {
	public string MYPREFIX_FOO { get; set; }
	public string MYPREFIX_OTHER_FOO { get; set; }
}

public class MySourceType {
	public string FOO { get; set; }
}
```

### Mapping configuration

```csharp
Mapper.Initialize(cfg => {
	cfg.RecognizeDestinationPrefixes("MYPREFIX_");
	cfg.CreateMap<MySourceType, MyDestType>();
});
```

### Version: x.y.z
 
6.2.2

### Expected behavior

MYPREFIX_FOO will be mapped from FOO
MYPREFIX_OTHER_FOO will *not* be mapped

### Actual behavior

Both MYPREFIX_FOO and MYPREFIX_OTHER_FOO are mapped from FOO

### Steps to reproduce

```csharp
var sourceObj = new MySourceType() {
	FOO = "testfoo"
};
var destObj = Mapper.Map<MyDestType>(sourceObj);
```
The resulting destObj will be
{
	"MYPREFIX_FOO":"testfoo",
	"MYPREFIX_OTHER_FOO":"testfoo"
}

**Comment by vincechan** [comment]
Right now I am ignoring the MYPREFIX_OTHER_FOO member to work around this problem. Like so:

`.ForMember(dest => dest.MYPREFIX_OTHER_FOO, opt => opt.Ignore());`

Also, interestingly , I found that if I changed all properties to lowercase, it works as expected.

**Comment by lbargaoanu** [comment]
Another workaround is to [disable](https://github.com/lbargaoanu/AutoMapper/blob/19c29483b20f666d5406f938fc0d01bba1faee4e/src/AutoMapper/NoNamingConvention.cs) the default destination naming convention.

**Comment by lbargaoanu** [comment]
@jbogard I'm not sure about a fix here. The default naming convention causes this, without any other configuration. So any solution would have to touch that and it seems risky.

**Comment by jbogard** [comment]
Yeah, I'd say the solution is to put in a different naming convention. The default one works when it's PascalCase, but unknown behavior for other naming conventions.

@vincechan you need to replace your naming convention for these mappings. There's a built-in naming convention that's lowercase underscore:

https://github.com/AutoMapper/AutoMapper/blob/master/src/AutoMapper/LowerUnderscoreNamingConvention.cs

It turns out rules for matching strings can be complicated :) You can't have separate splitting rules and matching rules, the two are intertwined as you have found out.
