### ISSUE TITLE
Cannot consume scoped service 'AutoMapper.IMapper' from singleton service

### ISSUE THREAD

**Issue by adnan-kamili** [AutoMapper/AutoMapper#2569]
Hi,

I recently changed some service types from being transient to singleton, which caused automapper to throw error:

`Cannot consume scoped service 'AutoMapper.IMapper' from singleton service
`
The error is clear enough, but I wonder why Automapper is a scoped service and not a singleton. It doesn't contain any state information.

Is there any way to register it as singleton or that will create issues. I am using .Net Core 2.0

### Version: x.y.z
6.1.1

**Comment by jbogard** [comment]
Singleton can’t consume scoped services. Change your singleton to scoped.

IMapper is marked scoped because anything that depends on a factory should
be scoped as the Mapper class does. The configuration is singleton, because
it does not create other things. Mapper depends on the configuration, so
scoped can depend on singletons but not the other way.

**Comment by adnan-kamili** [comment]
Thanks for clarifying.

**Comment by michael-freidgeim-webjet** [comment]
@jbogard , could you please explain(or provide a link) why "anything that depends on a factory should
be scoped"?

**Comment by jbogard** [comment]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.0#service-lifetimes-and-registration-options

**Comment by ChristianSauer** [comment]
Honestly I think this is a bad decision - I am constantly running into this problem and it's just annoying as hell

**Comment by jbogard** [comment]
What's worse, having configuration get overwritten because you called
Mapper.Initialize twice? Or throwing to say, "don't do this"?

**Comment by jbogard** [comment]
@ChristianSauer it's not a decision that was or was not made, it's a fundamental design constraint. You can't have singletons depend on transients or scoped items. It's not a fault of the container, those lifecycles are incompatible. If you want compatible lifecycles, choose different lifecycles.

Singleton <- Singleton GOOD
Singleton <- Scoped BAD
Singleton <- Transient BAD
Scoped <- Singleton GOOD
Scoped <- Scoped GOOD
Scoped <- Transient GOOD
Transient <- Singleton GOOD
Transient <- Scoped GOOD inside a scope, BAD outside a scope
Transient <- Transient GOOD

So really there's only 2 scenarios that are "always bad", and one scenario that is "sometimes bad".

ASP.NET Core DI makes this pretty explicit, even passing factory methods into context objects for things like filters. A filter is Singleton, so you can't have constructor dependencies. Instead, you use the various XyzContext objects passed in to the filter methods to resolve dependencies.

**Comment by jholovacs** [comment]
The reference is for ASP.NET Core, but AutoMapper is not dependent on ASP.NET Core.  There is no reason to have a scoped life cycle for a .NET Core console app that relies on a factory, is there?  This is a bad idea, based off a bad reason, and has a leaky abstraction smell.  If ASP.NET Core standards should have it as scoped, then it should be made scoped only for ASP.NET Core... not for every application.

**Comment by jbogard** [comment]
FYI the MS Extensions DI is *explicitly designed* for ASP.NET Core and
nothing else. As the other container authors can attest, it is an enormous
leaky abstraction, with behaviors that only exist because ASP.NET Core
needs them, and PRs that get rejected to add behaviors because ASP.NET Core
wouldn’t use them. See my currently open PR in the DI repo as an example.

I’m assuming this will change as other frameworks start to use the MS DI
and run into similar scenarios. Right now for example to include
AppInsights in a Worker I have to reference all of ASP.NET Core.
