### ISSUE TITLE
How define a global map rules?

### ISSUE THREAD

**Issue by kangkangkf** [AutoMapper/AutoMapper#2576]
Version 6.2.2.0

Model.cs
```
new Model()
{
    public int Id{get;set;}
}
```

Dto.cs
```
new Dto()
{
    public int Id { get; set; }
    public string Name { get; set; }
    public DateTime Birthday { get; set; }
}
```

StartUp.cs
```
AutoMapper.Mapper.Initialize(config =>{
   //Each Models and Dtos map rule
config.CreateMap<Dto, Model>().ForMember("Birthday", m => m.Ignore())
});
```

Each Model and Dto need to write a rule, Is there a simple way? Like use Attributes to define which one attribute to auto Ignore.

**Comment by jbogard** [comment]
There's an `IgnoreAttribute` you can use. Otherwise, there's a lot of stuff in the docs. You'll have to elaborate which kinds of "automatic rules" because there's sensible defaults built in but you can change quite a few things like which members to validate (in `CreateMap`) or for all maps with `ForAllMaps`.

**Comment by kangkangkf** [comment]
I solve this problem from issues 1309 and docs. Thank you so much! 👍
