### ISSUE TITLE
Using a default namespace with AutoMapper?

### ISSUE THREAD

**Issue by jez9999** [AutoMapper/AutoMapper#2735]
I have a complex object that I want to flatten into a destination object in AutoMapper:

```
	public class Family {
		public Person FamilyMember { get; set; }
		public string Address { get; set; }
	}

	public class Person {
		public string FirstName { get; set; }
		public string Surname { get; set; }
	}

	public class FamilyInfo {
		public string FirstName { get; set; }
		public string Surname { get; set; }
		public string Address { get; set; }
	}

	mapper.Map<FamilyInfo>(new Family());
```

I could prefix the `FirstName` and `Surname` in `FamilyInfo` but then I get a bunch of ugly long member names like `FamilyMemberFirstName` and `FamilyMemberSurname` - is there a way I can configure AutoMapper with a "default namespace", so it basically says "look in `DestinationObject.FamilyMember.PropertyName`, then fall back to `DestinationObject.PropertyName`?

**Comment by lbargaoanu** [comment]
See [this](https://gist.github.com/lbargaoanu/8e15798a8b4facd292feb5fcfbf1e3f7).

**Comment by jez9999** [comment]
@lbargaoanu But that's not officially part of AutoMapper....

**Comment by lbargaoanu** [comment]
There's nothing built in. You can customize the default naming convention, but that won't help here.

**Comment by jez9999** [comment]
Wouldn't it be a useful thing to build in?  If I extend an EF type to add some metadata, I need to create something like:

```
public class EntityWithMetadata : Entity {
    public Entity TheEntity { get; set; }
    public string Meta1 { get; set; }
    public int Meta2 { get; set; }
}
```

I don't see another way to do it.  I then need to flatten this to a DTO during mapping.  Is this not a common use-case or is there a better way to map extra metadata from an EF query to a DTO?

**Comment by jbogard** [comment]
The problem is you invite naming collisions. One of the early design goals of AutoMapper's flattening was to make it simple - just remove the "dots" and you have your member names. If your member names look funny in your DTO, it's not the DTO's fault, it's your object model.

In your example, why do you have the `EntityWithMetadata` both inheriting *and* composing. It contains the entity, and inherits it.

**Comment by jbogard** [comment]
Ha, that makes more sense.

This has come up a couple of times over the years, to ignore some prefix or something. Ultimately, I've leaned against it because it invites a bit too much "magic". The rules aren't immediately obvious like a `MapFrom`.

**Comment by jez9999** [comment]
@jbogard Any suggestions on how to extend an EF entity with a bit of metadata and then sanely map the entity and metadata to a DTO without setting up a ton of individual mappings or having a prefix in front of everything?

**Comment by jbogard** [comment]
Where does the metadata come from?

**Comment by jez9999** [comment]
The database.  For one of the metadata pieces, it's:

```
var roomsData =
	from rm in plan.Rooms
	join ccount in (
		from lnk in context.ContactsLink
		join cont in context.Contacts on lnk.ContactId equals cont.Id
		group new { } by lnk.RoomId into grp
		select new { RoomId = grp.Key, ContactsCount = grp.Count() }
	) on rm.Id equals ccount.RoomId
	select new { Room = rm, ccount.ContactsCount };
```

**Comment by jbogard** [comment]
Ah, so you've projected into another type, and need to map that one. That's always going to be an issue, you've got a second type with Room and ContactsCount properties. It's not really a design goal of AutoMapper to flatten intermediate anonymous types.

**Comment by jez9999** [comment]
Why shouldn't it be?  Seems exactly the sort of thing AutoMapper was intended for - you have this long set of boilerplate mappings you need to do to move from one type to another and you want to automate it.

**Comment by jbogard** [comment]
AutoMapper's design goal is flattening two types, but you're introducing a third, intermediate type. It's not one type to another, you're showing N -> (1) -> 1, where you want to more or less ignore the middle type and flatten straight from the N types to the 1 type.

That's quite a bit different, and more complicated. The middle type is a compiler-generated type, too. I'd have to invent new ways of doing mappings to skip the intermediate type.

Complicated manners further is the compile-time nature of that intermediate type. You can't easily configure for it. It now becomes quasi-tuple operations, not quite destructuring.

**Comment by jez9999** [comment]
No, I'm not using an anonymous type for the intermediate type, that was just for a quick illustration.  What I'm doing is something like:

`select new RoomWithMetadata { Room = rm, ContactsCount = ccount.ContactsCount, ... };`

**Comment by jbogard** [comment]
No, it's not arbitrary, because the "Auto" in "AutoMapper" encapsulates a set of conventions on how to flatten one type to another. You're doing a completely different operation, where I "lift" some members up. What would this look like with multiple complex objects to be lifted? What do I do when members collide?

You're not the first one to ask for this, especially in situations where you don't even want the intermediate type. To do something like `Mapper.Fill<Dest>(src1, src2, src3)`. It's different enough that you'd have completely different rules for choosing how to flatten, a new, different kind of "Auto".

The general idea behind flattening rules was to remove the dots. There's still a potential for a collision, like `FooBar.Baz` vs `Foo.BarBaz` but I viewed these problems as design issues - it would be confusing for someone using the objects to understand the difference.

Finally, AutoMapper has pretty strict configuration validation rules. If you have a member "Id" on the root, now I can look not only on the root, but any child object (kinda?) Is this behavior you opt-in to? Or do you just greatly relax the matching rules? None of this is obvious, so my "arbitrary" rules are more "carefully thought out to make it both obvious, intuitive, and difficult to screw up".

I'm not saying the behavior you're describing isn't desirable, but it's a huge departure from current behavior, full of nasty edge cases, and would potentially break existing maps. If you can think of ways to opt-in to this behavior via configuration, perhaps:

```
CreateMap<RoomWithMetadata, RoomDTO>()
   ForSourceMember(src => src.Room, opt => opt.LiftMembers());
```

Or similar. You're explicitly telling me "lift these members up to the destination type". That's a feature request.

**Comment by jez9999** [comment]
Well as you said, you could opt in via configuration.  And I'd throw an exception upon finding a name clash.  Seems like it would be a good feature to add.

**Comment by lbargaoanu** [comment]
A PR is welcome.

**Comment by jez9999** [comment]
Would the feature be added in principle, though?

**Comment by lbargaoanu** [comment]
I for one think we could work smth out.

**Comment by jbogard** [comment]
Also, for explicit configuration, I'd not throw exceptions for collisions. You're opting in to this behavior. We can have collisions today without exceptions.

In terms of precedence, I'd opt for:

 - Implicit match (first match wins)
 - Lifted match (first match wins)
 - Explicit configuration (`MapFrom`)

**Comment by jez9999** [comment]
I'd want a collision exception.  How about opting in to collision exceptions? ;-)

**Comment by jbogard** [comment]
That would be a departure from the current norm.

**Comment by jbogard** [comment]
Because even opting in is a departure. I don't want to go down the rabbit hole of implementing opt-in exceptions for other configuration collisions. Today exceptions are *never* thrown. Now we have a special case. I don't want a special case unless that special case is intended to become the norm.

**Comment by jez9999** [comment]
How about an opt-in callback lambda which could throw an exception if it wanted?

**Comment by jbogard** [comment]
That again is completely inconsistent with the rest of the configuration API and behavior. While that feature in isolation may seem trivial, I can't look at features by themselves. I have to look at the whole - and so, do I also then add this feature for the other places that can exhibit similar configuration problems?

My gut is no - we already have configuration validation as an explicit step. If you want to have some mode that checks collisions during validation, that's a bit different. It at least fits in with the way configuration validation happens for the last almost 10 years.
