### ISSUE TITLE
Built-in support for tuple types

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#2818]
This is more a discussion than anything else.

A couple scenarios:

### Tuple -> Tuple

```c#
var result = Mapper.Map<(Model1, Model2, Model3), (Dto1, Dto2, Dto3>(tuple);

// named

var result = Mapper.Map<(Model1 m1, Model2 m2, Model3 m3), (Dto1 m1, Dto2 m2, Dto3 m3)>(tuple);
```

I think this scenario works today, but we don't really have any explicit tests to map tuple members.

### (Multiple sources) -> Tuple

```c#
var result = Mapper.Map<Model1, Model2, Model3, (Dto1, Dto2, Dto3)>(model1, model2, model3);
```

This would assign to `Item1`, `Item2`, `Item3` etc.

```c#
var result = Mapper.Map<Model1, Model2, Model3, (Dto1 m1, Dto2 m2, Dto3 m3)>(model1, model2, model3);
```

This would assign to the named members.

I haven't really thought this through, thoughts?

**Comment by TylerCarlson1** [comment]
I would support Tuple->Tuple if it's not already supported.
As far as multiple sources to a single tuple I would think no, because nothing in Map uses anymore than 2 parameters.  1 for new object and 2 for existing object.  Now you are throwing 3 and more which logic is now different.

Not super tuples user, so couldn't tell you the practical uses of having Multiple Sources to single Tuple.

**Comment by lbargaoanu** [comment]
@jbogard Are we done here? :)
