### ISSUE TITLE
Automapper issue on TeamCity

### ISSUE THREAD

**Issue by NeenaDadwal** [AutoMapper/AutoMapper#2869]
I updated Automapper from 6.2.2 to 7.0.1.0.
Everything is working fine but When I am running my build on teamcity, its failing the test project and giving me the following error:

System.InvalidProgramException : Common Language Runtime detected an invalid program.
    at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression)
   at AutoMapper.MapperConfiguration..ctor(Action`1 configure) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 57
   at Project.Tests.ProgramFile..ctor() in C:\BuildAgent\work\92709d0ccafd7f46\Project.Tests\ProgramFile.Tests.cs:line 49

I was not facing this issue earlier. But after updating it i am facing this issue. Line 49 is

private readonly IMapper mapper;
var config = new MapperConfiguration(cfg => {
                cfg.AddProfile<ProgramFile>();
            });
mapper = config.CreateMapper();

**Comment by lbargaoanu** [comment]
Try upgrading the .Net framework. But other than that, you'll have to investigate what's different on that server and how we can repro the issue.

**Comment by NeenaDadwal** [comment]
Server is same for both the builds. And we are using latest version of .Net.

**Comment by lbargaoanu** [comment]
Without a repro, there is nothing we can do.

**Comment by SingleCopy** [comment]
I've resolved the issue and thought I'd post the fix, in case anyone else has the same issue. 

On TeamCity, one of the build steps is running dotcover to get the code coverage for the unit tests. In this instance, dotCover saw the calls to AutoMapper and was therefore trying to do coverage analysis on it. The fix was to add AutoMapper to the ExcludeFilters for dotCover.
