### ISSUE TITLE
MemberList.Source and ForPath

### ISSUE THREAD

**Issue by jlnostr** [AutoMapper/AutoMapper#3000]
### Source/destination types

```csharp
class TargetOuter
{
    public TargetInner Inner { get; set; }

    // The properties below should be ignored, they are not relevant
    public int Unrelated { get; set; }
    public string AlsoUnrelated { get; set; }
}

class TargetInner
{
    public string MyProp { get; set; }
}

class Input
{
    public string Source { get; set; }
}
```

### Mapping configuration

```csharp
Mapper.Initialize(opt => opt.CreateMap<Input, TargetOuter>(MemberList.Source)
                .ForPath(x => x.Inner.MyProp, y => y.MapFrom(x => x.Source)));
```

### Expected behavior
The call of `Mapper.AssertConfigurationIsValid()` should not throw an exception, because all properties from the source (note the `MemberList.Source` configuration value) have been mapped.

### Actual behavior
The call throws the following exception:

```
AutoMapper.AutoMapperConfigurationException: 
Unmapped members were found. Review the types and members below.
Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type
For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters
===============================================================
Input -> TargetOuter (Source member list)
AutoMapper_Assertion.Input -> AutoMapper_Assertion.TargetOuter (Source member list)

Unmapped properties:
Source

   at AutoMapper.ConfigurationValidator.AssertConfigurationIsValid(IEnumerable`1 typeMaps) in C:\projects\automapper\src\AutoMapper\ConfigurationValidator.cs:line 28
   at AutoMapper.MapperConfiguration.AssertConfigurationIsValid() in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 305
   at AutoMapper.Mapper.AssertConfigurationIsValid() in C:\projects\automapper\src\AutoMapper\Mapper.cs:line 179
```

The mapping actually works, which can be seen on the `equal` variable in the reproduce steps below.

### Steps to reproduce

```csharp
var input = new Input() {Source = "Hello World!"};

// The following line throws an exception, see above
// Mapper.AssertConfigurationIsValid();

var output = Mapper.Map<TargetOuter>(input)
var equal = output.Inner.MyProp == input.Source; // equal is true
```

**Comment by jbogard** [comment]
Configuration validation is NOT about "will this mapping work at runtime". Configuration validation is about "I've now introduce a library that may introduce a bunch of magic, let me make sure the magic is doing what I want."

AutoMapper assumes that you're flattening and projecting from a complex model to a simple one. It assumes that *every* destination member wants to be mapped in this way. Otherwise, you might add/remove/misspell something that gets missed. And since it's easy to get missed, AutoMapper enforces a convention.

Even though you might want these members to be ignored, someone else might think they should be mapped, and AutoMapper won't throw exceptions at runtime if things are "supposed" to be mapped but aren't.

**Comment by lbargaoanu** [comment]
@jbogard Just considering the code in the issue, I think @jlnostr has a point.

**Comment by jbogard** [comment]
Ahhhhhhh I see it now. I really shouldn't review GH issues at night.

**Comment by korenb** [comment]
Also for `MemberList.Source` 
teh expression `.ForAllOtherMembers(opt => opt.Ignore())` seems not working
