### ISSUE TITLE
Null values are unexpectedly converted

### ISSUE THREAD

**Issue by nicolataddei94** [AutoMapper/AutoMapper#3094]
Hi.

I just try to convert a dynamic object into class object.

```
public async Task<HttpStatusCode> Update(Guid companyId, dynamic companyToUpdate)
{
    var company = await _companyGenericRepository.GetByKeyAsync(companyId);
    company = _mapper.Map(companyToUpdate, company);
    return await _companyGenericRepository.UpdateAsync(companyId, company);
}
```

What I would like to do (and which in part succeeds) is to mantain old class object and update only fields contained in dynamic object.

At this point I have a problem and I dont't understand if it is a bug or not.

Null value contain in dynamic object are converted in empty string if string type, 0 if int type, ecc...

What should I do?

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by nicolataddei94** [comment]
> A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

https://gist.github.com/nicolataddei94/847951409d83900f884122c6ae57cebe

Is it a correct format?

I would say also that i use AutoMapper with netCore dependency injection if it could be useful.

In this case, despite my application, automapper overrides also old fields not present in dynamic, but there is the bug(?) above. 
Ex: null Sort in json becomes 0 in int? Model object

I hope I explained myself and sorry for bad english

**Comment by lbargaoanu** [comment]
The problem seems to be in the source `((object)source.Sort)==null` is false.

**Comment by nicolataddei94** [comment]
but `source.Sort == null` is true. So where is the problem? In AutoMapper that cast all to object transforming in not null the null values or I should found some tricks to let AutoMapper read the correct value. Because I have not any ideas

**Comment by lbargaoanu** [comment]
The problem is most likely with the way Newtonsoft.Json implements dynamic. That might make sense for them, but I don't think it makes much sense in the general case. Check [our tests](https://github.com/AutoMapper/AutoMapper/blob/88a7c788124c184ca570d21f4dda4da32cb17a3b/src/UnitTests/Mappers/DynamicMapperTests.cs#L172). I cannot repro that with some generic dynamic object/ExpandoObject. So you can either teach AM about how Newtonsoft.Json sees dynamic, or you can try to simply do the mapping with Newtonsoft.Json, by directly deserializing into your destination type. Whatever work for you. But as far as AM is concerned, this is a non issue. Unless you have a failing test similar to my link above.

**Comment by lbargaoanu** [comment]
[For example](https://stackoverflow.com/questions/47473087/using-automapper-to-map-from-dynamic-jobject-to-arbitrary-types-without-creating).

**Comment by nicolataddei94** [comment]
Yes, ,in fact the conclusion I reached was precisely the fact that at some point it was no longer JObject but JValue. Thanks a lot!
