### ISSUE TITLE
ASP.NET Core usage

### ISSUE THREAD

**Issue by RotterAxel** [AutoMapper/AutoMapper#3184]
In fact the existing documentation describes the proper way to use AM in ASP.NET Core. See also https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/blob/master/README.md.

_Originally posted by @lbargaoanu in https://github.com/AutoMapper/AutoMapper/pull/3183#issuecomment-519405409_

The link you sent about the 8.0 implementation has the exact same problems as the documentation I changed. It is not clear enough. The Stack Overflow issue I quoted as a source exists because of this and the answer even has close to 500 upvotes. So that might tell you that your documentation is lacking.

**Comment by lbargaoanu** [comment]
You did not answer the question. What is not clear?

**Comment by Tasteful** [comment]
I think what @RotterAxel is saying is that the example that already exists is not enough for beginners to understand how it should be configured correctly. 

Example the `configAction` parameter in the `AddAutoMapper´-extension should probably have more documentation about how to correctly configure AM with dependency injection. If profiles is the recommended way to configure mappings when using DI (or otherwise also) it should be good with some linking between the documentations so it is easy to understand how to set it up.

If we see both the https://github.com/AutoMapper/AutoMapper/pull/3183 with better steps and the [SO](https://stackoverflow.com/questions/40275195/how-to-set-up-automapper-in-asp-net-core) thread as source in the PR changes is not using the preferred way to handle registration if using the AM.Extensions.MS.DI-package.

**Comment by lbargaoanu** [comment]
We can add a link to that once someone writes it. But for the average developer I think the existing steps are clear enough. The XML docs for `AddAutoMapper` are another matter.

**Comment by lbargaoanu** [comment]
A PR is welcome with the proper content.
