### ISSUE TITLE
Support IEnumerable<T> for LINQ child member projections

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#3186]
Consider our types:

```c#
public class ParentDto {
    public IEnumerable<ChildDto> Children { get; set; }
}

public class Parent {
    public IEnumerable<Child> Children { get; set; }
}
```

When we call `ProjectTo`, our LINQ query is:

```c#
var parent = querayble.Select(p => new {
    Children = p.Children.Select(c => /* projection */).ToList()
});
```

However, the destination type is only `IEnumerable`, not a list. We should only call `ToList` if the destination type is a list. Right now we do `ToArray` if it's an array, then default back to `ToList`. We should match the destination type - only do `ToList` if the destination type is `IList`.

I ran into this on a projection from a MongoDB driver, which does not support `ToList` because that implies running the list at the server.

**Comment by BryanSan** [comment]
Hello!

Is there a way to turn off this functionality? The problem is that I have a class with several IEnumerable properties and this change is triggering a lot of ef lazy loading because I expect to have my IEnumerable properties materialised by automapper

**Comment by jbogard** [comment]
....what?

Lazy loading and ProjectTo don’t, and should never, mix.

**Comment by BryanSan** [comment]
Sorry! I think I didn't elaborate on my question.

I am doing a normal .ProjectTo() map from EF entities to a Dto. In my Dto I have multiple IEnumerable properties that map from my EF navigation properties. When I materialise the IQueryable<,> returned from the .ProjectTo() method e.g. with a .First() everything is materialise except for my IEnumerable properties, they are materialise when I use them(Lazy Loading). If I try this same example in an older version of Automapper everything is materialise after I call .First including my IEnumerable properties. This is due to this change :/ so I would like to turn off this functionality if it is possible

**Comment by jbogard** [comment]
Ah ok, the easiest thing would be to change your DTOs to be more explicit
about needing a materialized collection, instead of IEnumerable. Use a
list, array, collection etc
