### ISSUE TITLE
Constructor mapping with optional arguments

### ISSUE THREAD

**Issue by lbargaoanu** [AutoMapper/AutoMapper#3378]
At least the resolving part should be common to the other member maps. One problem is that optional values override matching values from the source.
Evolving things is cumbersome. I recently did that and added another `if`.

**Comment by pdemro** [comment]
Per #3392 It would be nice to auto map properties with optional arguments, especially in the case of generated code/models where there might be several dozen default constructor values.  In this situation the automapper config becomes very verbose which is unfortunate since, without optional constructor arguments, the automap declaration becomes one line
