### ISSUE TITLE
Memory footprint and caching

### ISSUE THREAD

**Issue by Gillardo** [AutoMapper/AutoMapper#3446]
This isnt a bug, but i am unable to find any information on this on stackoverflow that is relevant in this current version, so sorry if this is obvious.

I am looking into the meory footprint of my application and i am seeing a lot of what i believe is AutoMapper caching the maps between objects.  I have done a bit of reading online and it says that AutoMapper caches objects as well, encase it gets an object that is the same?  Is this true? Can it be turned off?

Also is there a way of turning off any caching of the maps altogether.  Yes i know this would mean recreating them on each request to my API, but i would like to try this and see what the performance and memory are like, also when trying to find a memory leak, this would be a nice thing to turn on/off

![image](https://user-images.githubusercontent.com/7406381/85306512-7fce0380-b4a6-11ea-88a4-2b1ad3210918.png)

**Comment by jbogard** [comment]
We do store the compiled expression tree because if we didn't, CPU utilization would be *extremely* high as expression tree compilation is an expensive operation. I don't know if this is caching or not, but we calculate the execution plan once, then compile it on first use. This compiled execution plan is stored with the configuration.

The second caching you're referring to is for during a map, which is something you have to turn on manually.

If you want to turn "off" caching, you would need to manually register AutoMapper, using the `Func`-based options to make `MapperConfiguration` `Transient` instead of singleton as it is today.

I don't know why the compiled delegates there are KBs in size - though I've not done any performance profiling on my apps (nor really needed to).

**Comment by jbogard** [comment]
One other thing - if I'm reading this right, those memory sizes are in bytes? So your entire app's memory is 470KB? Is that large?
