### ISSUE TITLE
[Rant] Deprecating functionality should allow for backwards-compatibility

### ISSUE THREAD

**Issue by astrohart** [AutoMapper/AutoMapper#3477]
I'd like to just make a polite suggestion.

I am new to AutoMapper.  It seems like just the right tool for the job.  However, I am having an issue with learning how to utilize it as a total n00b.

It seems to me like functionality that shows up in a Stack Overflow post or YouTube video is non-existent in the latest version of the library.  

This makes learning to utilize the library for the first time a bit of a challenge.

My suspicion is that the creators of AutoMapper, as I can also see by discussions on Stack Overflow posts, tend to "deprecate" functionality by straight-up deleting said code from the library.  

I think that, if this is true, then it is a bad practice as it does not support backwards-compatibility.  There are a lot of obsolete YouTube videos and SO posts out there now, due to missing overrides, static methods etc. which they teach.  

The best-practice is to deprecate functionality by marking it with an attribute, but otherwise leaving the code there.

It it curious to me why this practice is not adhered to.

**Comment by jbogard** [comment]
Because that's not best practice. The Obsolete attribute causes compiler warnings, and many folks turn warnings into errors, so it might as well be removed. Instead we use the upgrade guide for deprecated and removed calls.

I asked the .NET team about this and that's what they recommended.

What we can do better about is not adding APIs we don't want to support and just having a much higher bar since deleting is so disruptive.
