### ISSUE TITLE
IAsyncEnumerable support

### ISSUE THREAD

**Issue by onionhammer** [AutoMapper/AutoMapper#3567]
Opening this since #3239 is locked/closed.  With modern C# it is going to become increasingly common having IAsyncEnumerable data, so it would be great to support Projecting that data.

And no, not everybody is using EF/EF Core, there are other backing stores that IAsyncEnumerable is a great fit for, such as Cosmos's SDK.

**Comment by lbargaoanu** [comment]
You'll have to write your async code outside AM.

**Comment by jbogard** [comment]
In-memory AutoMapper (`Mapper.Map`) will NEVER support async, by design. It's an absolute awful mess to introduce async to a sync library.

As @lbargaoanu said, `ProjectTo` supports async just fine, since it's merely a shortcut to `Select(x => { })`.

I've used `ProjectTo` with EF, EF Core, MongoDB, CosmosDB, all works just fine. Unless there's something I'm missing, show code that does *not* use AutoMapper that does `IAsyncEnumerable` with projection.
