### ISSUE TITLE
True ReverseMap()

### ISSUE THREAD

**Issue by paolosanchi** [AutoMapper/AutoMapper#359]
The ReverseMap() method just do a reverse CreateMap. It Do not applay a reverse to every statements.
I know that probably lot of the custom configurations are not reversible, but anyway it would so much usefull if at least the ForMember mapping would be correctly reversed.
I've tried to make an extention method, but without success. Is it technically possible?

**Comment by StefanKert** [comment]
@jbogard Why has this been closed? Had been searching for a solution to this issue but didn´t come to an result. Is this behaviour per design? If so is there another way to generate ReverseMap() including the already formulated Expressions and not formulating these Mappings a second time (Code Duplication, error-prone).

Adding another example  @paolosanchi showed:

```C#
                cfg.CreateMap<IActivitesWindowSettings, DailyActivitiesWindow>()
                    .ForMember(x => x.Height, m => m.MapFrom(a => a.ActivitiesInputWindowHeight))
                    .ReverseMap()
                        .ForMember(x => x.ActivitiesInputWindowHeight, m => m.MapFrom(a => a.Height));
```

Basically there should be a way to tell AutoMapper to create a ReverseConfig to so that we can get to the shorter version showed here:

```C#
                cfg.CreateMap<IActivitesWindowSettings, DailyActivitiesWindow>()
                    .ForMember(x => x.Height, m => m.MapFrom(a => a.ActivitiesInputWindowHeight))
                    .ReverseMap();
```

Is there any specific reason that this is not supported or that this shouldn´t be supported?

**Comment by jbogard** [comment]
@StefanKert I'd rather have more specific issues for more specific features. Can you open an issue for your scenario?
