### ISSUE TITLE
Create signed version of AutoMapper 3

### ISSUE THREAD

**Issue by cd21h** [AutoMapper/AutoMapper#373]
Please create signed version of AutoMapper 3 NuGet package.

Many project depends on signed AutoMapper DLL. Having unsigned version only does not allows to update.

**Comment by Shazwazza** [comment]
So this unfortunately this is a massive breaking change. If you are going to change the assembly manifest this should be on a major version. Sure, if people rebuild their projects there shouldn't be an issue but for projects like CMS's that use Automapper, they cannot ship with the new version because all plugins built for it will no longer work. This should have been a version 4.0 change. We use Automapper in Umbraco but this means we won't be able to upgrade to 3.1 + until we release a new major version.

**Comment by Shazwazza** [comment]
haha... i just noticed this date, guess it goes to show we haven't shipped with an upgraded version for a while ;)
Some complaints are only starting to come through now for some reason. Not much we can do though for now!

**Comment by TonnyMediamonks** [comment]
If you hook into the ` AppDomain.CurrentDomain.AssemblyResolve += CurrentDomain_AssemblyResolve` event and remove the publickey from the `ResolveEventArgs.Name` and pass that again in `Assembly.Load("string with publickey removed")` and return that assembly. The appdomain will load the dll with or without a SN token / publickey token

**Comment by Shazwazza** [comment]
Wow! Will definitely check that out, thanks!
