### ISSUE TITLE
AutoMapper issue in MAUI iOS application

### ISSUE THREAD

**Issue by curia-damiano** [AutoMapper/AutoMapper#4177]
I am opening a new issue, after the existing issue #4087 has been closed without much clarification.
@busec0 has also provided a repro project at https://github.com/busec0/MauiAutomapper.
Can you please help invstigating how can we solve this crash?

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
You wrote some code that doesn't work. You go about solving it the usual way. Just because you use AM, it doesn't mean AM has much to do with your problem.
But if you think AM is the problem, you're welcome to isolate the issue to a few lines of AM, as requested when opening the issue.
