### ISSUE TITLE
Can't find missing mappings in included mapping.

### ISSUE THREAD

**Issue by siudeks** [AutoMapper/AutoMapper#533]
Automapper can't find missing mappings included mapping.

    [TestFixture]
    public sealed class ContractsTests
    {

        [Test]
        public void ShouldDiscoverMissingMappingsInIncludedType()
        {
            Mapper.CreateMap<object, BaseType>()
                .Include<object, ChildType>();
            Assert.Throws<AutoMapperConfigurationException>(Mapper.AssertConfigurationIsValid);
        }

        public class BaseType { }

        public class ChildType : BaseType
        {
            public string Property1 { get; set; }
        }
    }

**Comment by Serenyrddraig** [comment]
I believe that I have encountered a variation on this theme. I've structured my profile so that each configured Map is created in a separate method. The methods are called in descending class hierarchy order (from least derived to most derived) in my override of Profile.Configure. Largely to ease maintenance, each method that involves a subclass is in charge of 'including' itself in its parent map, e.g. 
        configurationStore.FindTypeMapFor(typeof(source), typeof(destination)).IncludeDerivedType(typeof(source), typeof(subClassDest));  

My issue is that if I execute this line BEFORE I create the subclass map, AssertConfigurationIsValid() succeeds. If I do it AFTER creating the subclass map, AssertConfigurationIsValid() generates a fault for unmapped properties in the child, e.g. this faults

        private void ConfigureFeeItem()
        {
            CreateMap<Item, FeeItem>()
                ;            
           ConfigStore.IncludeInMap<Item, LineItem>(typeof(FeeItem));
        }
whereas this does not
        private void ConfigureFeeItem()
        {
            ConfigStore.IncludeInMap<Item, LineItem>(typeof(FeeItem));
            CreateMap<Item, FeeItem>()
                ;
        }

where IncludeInMap is an ConfigurationStore extension method I wrote to encapsulate the FindTypeInMap/IncludeDerivedType sequence shown above.

I can create a repro for this if it is not a variant of this issue.

Just as an aside, it would be nice if the configurationStore was a protected property of Profile, rather than a private one to facilitate nerdy tricks like the above.
