### ISSUE TITLE
Mapping to an interface (only) with a  read-only property

### ISSUE THREAD

**Issue by timker** [AutoMapper/AutoMapper#587]
When mapping to a concrete-less interface, that has a read-only property, I would expect that property to be mapped.

Given this example:
http://lostechies.com/jimmybogard/2009/04/15/automapper-feature-interfaces-and-dynamic-mapping/

and removing the setter from here:

```
public interface ICreateOrderMessage
{
    string CustomerName { get; set; }
}
```

to:

```
public interface ICreateOrderMessage
{
    string CustomerName { get;  }
}
```

I would have thought CustomerName would still be populated...
Especially if I had explicitly configured the mapping
i.e

```
  .ForMember(x => x.CustomerName , m => m.MapFrom(s => s.Customer.Name ));
```

**Comment by bchristie** [comment]
Sorry to re-up an (older) thread, but I just ran across this as well; I expected the value to be populated despite exempting the setter from the interface (anticipating the proxy to define `{ get; private set; }`).

Perhaps [`if (property.CanWrite`](https://github.com/AutoMapper/AutoMapper/blob/develop/src/AutoMapper/Internal/ProxyGenerator.cs#L99-L101) could emit a private setter?

**Comment by petedavis** [comment]
I have also hit the same issue today. I have immutable command interface that I want to send, and instead of creating an internal concrete type that implements the interface, I thought I would use automapper.

in some contract assembly:

    public interface DoSomething
    {
        Guid AggregateId { get; }
    }

Which is all the consumer needs, and the contract states that it is immutable.

So the code I would have to write manually is:

    internal class DoSomethingCommand : DoSomething
    {
        public Guid AggreagateId { get; set; }
    }

Then I can use my concrete type and send that over the bus. 

So options are:
1. Add setters to immutable contact types so I can use AutoMapper
2. Ditch AutoMapper and create concrete types to instantiate for each interface.

**Comment by jbogard** [comment]
I do accept pull requests.

**Comment by matthewethomas** [comment]
I know this is a little old, but another option would be to set the destination property via reflection in the .BeforeMap or .AfterMap function, and then ignore the property on the ForMember setup function.
