### ISSUE TITLE
Mapping through constructor doesn't consider custom member mappings

### ISSUE THREAD

**Issue by matkoch** [AutoMapper/AutoMapper#633]
AutoMapper is able to use construct Destination objects using the constructor and simple name resolution as in #361. However, it fails to consider custom mapped members in its constructor resolution process.

A simple example is the following code. While it fails in the immutable version with private setter and constructor; it totally works if you only have a simple auto property with public getter and setter (and no constructor).

```
public void Main()
{
  Mapper.CreateMap<Src, Dest>().ForMember(x => x.ResolvedVal, opt => opt.ResolveUsing(x => x.Val));
      
  var res = Mapper.Map<Src, Dest>(new Src { Val = "test" });
}

public class Src
{
  public string Val { get; set; }
}

public class Dest
{
  public Dest (string resolvedVal)
  {
    ResolvedVal = resolvedVal;
  }

  public string ResolvedVal { get; private set; }
}
```

**Comment by IanYates** [comment]
Some good arguments here.  I agree with the ForCtorParamMatching suggestion put forward by @fschmied - the more correct .ForCtorParam() can be present and the more tool-friendly (but possibly incorrect) .ForCtorParamMatching() method available for those who know what they're doing and wish to opt in to potentially incorrect behaviour.  
As someone just getting started with AutoMapper I'd like to use it with the https://github.com/AArnott/ImmutableObjectGraph library that I've been using for quite some time.  That brings its own problems since the constructors are private (there's a static Create() factory method instead) but I've succesfully written JSON.Net converter contract classes and I'd like to do the same for AutoMapper when I get time.

**Comment by stevensrf11** [comment]
aaaaaaaaaa

**Comment by chrischu** [comment]
@jbogard  Why is this issue closed? Did you decide against the suggestion put forward by @fschmied?

**Comment by jbogard** [comment]
@chrischu I dunno, it was 3-4 years ago. I can't remember issues closed last week!

Feel free to open a new issue for a feature request. We can have a more targeted discussion then.
