### ISSUE TITLE
V3.3.0: Mapping EF5-Objects with NullSubstitute causes "Can't resolve this to Queryable Expression" exception in .Project().To()

### ISSUE THREAD

**Issue by Linus62** [AutoMapper/AutoMapper#642]
I have an application which worked fine with an older versions of Automapper.

Since I upgraded to 3.3.0 it thows the exception "Can't resolve this to Queryable Expression" out of a call to .Project().To<OrganisationViewModel>().
- There is a class "OrganisationViewModel" with a property "string Departement {get; set;}"
- There is a EF-Class "tabOrganisation" with a (foreign-key)-property "tabDepartement" which (optionally) references an EF-object of class "tabDepartement".
- There is a EF-Class "tabDepartement" which contains a property "Bezeichnung" which should be mapped to OrganisationViewModel.Departement 

The mapping looks like this:

```
        Mapper.CreateMap<tabOrganisation, OrganisationViewModel>()
            .ForMember(dest => dest.Departement, opt => opt.Condition(source => source.tabDepartement != null))
            .ForMember(dest => dest.Departement, opt => opt.MapFrom(source => source.tabDepartement.Bezeichnung))
            .ForMember(dest => dest.Departement, opt => opt.NullSubstitute("undefined"));
```

As soon as I remove .ForMember(dest => dest.Departement, opt => opt.NullSubstitute("undefined")) the exception disapears - but than I have no null substitution anymore.

**Comment by lschreck** [comment]
I have this very same error when using EF6 and AutoMapper 3.1.1 but in my case the root cause is (according to my debugging efforts) that when I have a mapping setting for a string member with a NullSubstitute option, the PrimitiveExtensions.IsNullableType method result will be false for the string type. Basically when the NullSubstitutionExpressionResultConverter's CanGetExpressionResolutionResult method gets evaluated for string ExpressionResolutionResult types, it will result false - which is understandable because as far as I can tell string is not Nullable<> and the nullable type check seem to be work only on Nullable<> types (also the string type won't have "HasValue" member when the VisitMember method will check for it).

Sorry for not providing a good repro for this, but if you think that it is worth to check this case, please reopen this ticket, and I will find some time to provide some sample code.

**Comment by jbogard** [comment]
So something like:
```
    Mapper.CreateMap<Source, Dest>().ForMember(d => d.SomeString, opt => opt.NullSubstitute("Blarg"));
```
?

**Comment by lschreck** [comment]
Yes, more specifically

`Mapper.CreateMap<Source, Dest>().ForMember(d => d.SomeString, opt => opt.NullSubstitute(string.Empty));`

Currently I have a workaround like `Mapper.CreateMap<Source, Dest>().ForMember(d => d.SomeString, opt => opt.MapFrom(entity => entity.SomeString ?? string.Empty);` but nevertheless using NullSubstitute for this would be much appropriate/cooler IMO.

Actually I am not really convinced that Entity Framework has anything to do with this, but I think this can be tested well enough.
