### ISSUE TITLE
AssertConfigurationIsValid(TypeMap typeMap) has different behavior 

### ISSUE THREAD

**Issue by vitorfariatomaz** [AutoMapper/AutoMapper#703]
This is my profile under test

    public class MenuProfile : Profile
    {
        protected override void Configure()
        {
            Mapper.CreateMap<Menu, MenuModel>();
        }

        public override string ProfileName
        {
            get { return this.GetType().Name; }
        }
    }

This is my test method, I'm having different results when using the TypeMap overload, is this normal?
    
    [TestMethod]
    public void MenuProfileTest()
    {
            Mapper.AssertConfigurationIsValid("MenuProfile");

            Mapper.AssertConfigurationIsValid(new MenuProfile().ProfileName);

            //this one throws AutoMapperConfigurationException
            Mapper.AssertConfigurationIsValid(Mapper.CreateMap<Menu, MenuModel>().TypeMap);
    }

**Comment by tdietrich513** [comment]
You might have the same problem I had. 

Inside your profile's `Configure` method, you're using the static `Mapper` instance instead of the `CreateMap` method that the `Profile` exposes. This creates a mapping not associated with your profile.

See: https://github.com/AutoMapper/AutoMapper/issues/707

**Comment by jbogard** [comment]
Yep, call `base.CreateMap`, not `Mapper.CreateMap`.
