### ISSUE TITLE
Please add support for generic version of TypeConverter

### ISSUE THREAD

**Issue by risogolo** [AutoMapper/AutoMapper#774]
I have a generic class with private setters and without parameterless constructor ( I have 2 constructors which expects some variables, one of the variables is the value of type of T)
I tried to create my own TypeConverter to use public constructor to map the object instead
of using property mapping since setters are private

![image](https://cloud.githubusercontent.com/assets/13233569/8567418/7e25deac-2565-11e5-9d50-fab6e324ceef.png)

and use it by calling
```
Mapper.CreateMap(typeof(RequestResult<>), typeof(DtoRequestResult<>)).ConvertUsing(typeof(RequestResultToDtoRequestResultTypeConverter<>));
```
but it does not work this way, or do you suggest any other apporach

**Comment by jbogard** [comment]
Open generics are supported in 3.3.1, but this kind of use of it isn't. Interesting use case, I'll add it to 4.0

**Comment by lbargaoanu** [comment]
I thought dynamic might be a good idea [here](https://github.com/lbargaoanu/AutoMapper/blob/650194467d225d98488bb979d5ff50f87053f676/src/AutoMapper/Internal/DeferredInstantiatedConverter.cs#L17). Too much? :) It seems to be supported on Xamarin, but I'm sure it can be done the old fashioned way.

**Comment by jbogard** [comment]
wellllll i don't think that'll work. I have to actually close that
converter type.

**Comment by lbargaoanu** [comment]
Yeah, I saw it didn't work and I deleted the original message. It didn't work because of the [DualConverter test](https://github.com/lbargaoanu/AutoMapper/blob/587ce3fc38d6319f1d9050d5b73b7fd7e0fc6bd8/src/UnitTests/Bug/MultipleTypeConverterInterfaces.cs). It always invoked the public method.

**Comment by risogolo** [comment]
I was able to overcome this "issue" with Configuring visibility, so the AutoMapper is setting the object via private setters, and I had to add private parametersless constructor, but this is something i did not want to do, because my class is supposed to be kind of immutable, so I'd like to rather use the constructor for setting the class if this will be even possible

**Comment by jbogard** [comment]
Fixed!

**Comment by mikocot** [comment]
Is there any reason to limit the GenericTypeConverter to only one generic parameter?

I would like to introduce a converter of lists ex `List<DTO>` -> `List<Entity>,` I can easily define a mapping for those two, but the Converter fails if it requires 2 parameters:

`public class TestConverter<TSource, TDestination> : ITypeConverter<TSource, TDestination>`

due to the 'The number of generic arguments provided doesn't equal the arity of the generic type definition.Parameter name: instantiation', mapping:

```
 config.CreateMap(typeof (SourceTest<>), typeof (DestinationTest<>))
          .ConvertUsing(typeof (TestConverter<,>));
```

It works for the TestConverter<T>  : ITypeConverter<T. T> but it's useless for my scenario.
