### ISSUE TITLE
Mapping complex Objects with AutoMapper

### ISSUE THREAD

**Issue by denkyira5544** [AutoMapper/AutoMapper#875]
I have a complex database Model with joins. I don't want to use store procedure so I want to use AutoMapper to flatten it so I can query it using Linq. I can't seem to figure out how to flatten it using AutoMapper and structuremap. Below are my classes generated from the Entity Framework using code first from existing database. Also my database model. I am using an Interface and Implementing a class to query the objects. I need to get users who has permissions to a contract. 

[Table("Contract")]
    public class Contract
    {
       public Contract()
        {
            CDRLs = new HashSet<CDRL>();
            ContractDocuments = new HashSet<ContractDocument>();
            WDTOes = new HashSet<WDTO>();
        }

    [Table("PMO")]
    public class PMO
    {         
        public PMO()
        {
            Contracts = new HashSet<Contract>();
            Products = new HashSet<Product>();
            USERS = new HashSet<USER>();
        }

		 [Table("USERS")]
    public class USER
    {
        
        public USER()
        {
            Organizations = new HashSet<Organization>();
            Organizations1 = new HashSet<Organization>();
            Products = new HashSet<Product>();
            Products1 = new HashSet<Product>();
            Programs = new HashSet<Program>();
            Programs1 = new HashSet<Program>();
            PMOes = new HashSet<PMO>();
            ROLES = new HashSet<ROLE>();
        }
		
		
		[Table("ROLES")]
    public class ROLE
    {
        
        public ROLE()
        {
            PERMISSIONS = new HashSet<PERMISSION>();
            USERS = new HashSet<USER>();
            LastModified = DateTime.Now;
            InsertDate = DateTime.Now;
        }
		
		
		
   [Table("PERMISSIONS")]
    public class PERMISSION
    {
         
        public PERMISSION()
        {
            ROLES = new HashSet<ROLE>();
        }
 
![capture3](https://cloud.githubusercontent.com/assets/14190703/9751439/e7feb7ca-5672-11e5-84f9-1201cf385771.PNG)

**Comment by TehWardy** [comment]
Thinking about this in dto form ...

public class PermissionMapDto
{
     public int UserId { get; set; }
     public IList<int> ContractIds { get; set; }
     public IList<int> RoleIds { get; set; }
     public IList<int> PmoIds { get; set; }
}

For permissions, each role then further has a collection of Permissions, and also each pmo has a collection of contracts so the problem is, how do you say "What are the collection of permissions for this user vfor this contract?", that is then a separate question to "For this user, what are the colleciton of contracts?", the issue that there isn't relationship between these question results.

Its like saying "A user has a collection of contracts, they also have a collection of permissions", but there is now way to say "for this contract, the user has these permissions" 

In other words, if a user has a permission, they have it for all contracts so why bother trying to flatten the data at all, figure out the users permissions then store them in session or something with a simple select many ...

var usersPermissions = user.SelectMany(u => u.Roles.Select(r => r.Permissions))

That makes me think that what you really want is to improve your data model or imply a join that simply doesn't exist with some assumptions.

How I would solve this ...

Users are granted permissions by being given roles.
Grant contracts permissions in the same way by creating a join table between contracts and roles.

Then you can ask the system questions like "get me the roles for this contract, and get me the roles for this user, take the roles that exist in both, as the effective roles for the user for this contract from which you can pull the permission information you need.

New table: 
Contract_Role
   ContractId
   RoleId

To Map create a dto like this ...

class PermissionMapDto
{
    int UserId
    int RoleId
    int ContractId
    ICollection<Permission>
}

if you run a join query on the db or create a view then you should be able to take that view and stuff it directly in to a collection of these dto's ...

select RoleId, ur.UserId, cr.ContractId 
from Roles 
join User_Role ur on RoleId = ur.RoleId
join Contract_Role cr on RoleId = cr.RoleId

Thinking about it you could probably map from Role to PermissionMapDto with a little work.

**Comment by denkyira5544** [comment]
Thanks a lot and appreciate it very much. I am going to do it the way you suggested.

**Comment by denkyira5544** [comment]
Hi Paul,
I have created the PermissionMapDto class as you suggested. I have done the mapping in my Configuration file like this:
 public void Execute()
        {
            Mapper.CreateMap<Organization, PermissionDto>()
                .ForMember(dest => dest.PERMISSIONS, opt => opt.MapFrom(src => src.ROLES))
                .ForMember(dest => dest.USERS, opt => opt.MapFrom(src => src.OrganizationId));
            Mapper.AssertConfigurationIsValid();
        }

Now I need to call the Mapper in my Repository class to check if the user has the required permission. I can't seem to get that part. I am doing something like this:
 public void LoadContracts(int contractID)
        {
                 Mapper.Map<PermissionDto>(typeof (Organization));
            IEnumerable<Contract> uniqueContracts = data.Contracts;
            var contractQuery = uniqueContracts.Where(
                c =>
                    (c.ContractYearType.ContractYearTypeID == (int) ContractYearType_Enum.Base ||
                     c.ContractYearType.ContractYearTypeID == (int) ContractYearType_Enum.None ||
                     c.ContractYearTypeID.HasValue == false) &&
                     if user Role has permission------->this where I am struggling. Any help will be appreciated



        }

**Comment by TehWardy** [comment]
Ok so assuming we are on the same page here you now have a collection of roles for each contract from the new join table and each user has a collection of roles through the existing db schema.

so you could say that the permissions for a user on a specific contract would look something like ...

User.Roles.Where(r => contract.Roles.Contains(r)).Select(r => r.Permissions);

So back to our DTO ....

class PermissionMapDto
{
  int UserId
  int RoleId
  int ContractId
  ICollection<Permission> Permissions
}

I think the way this ultimately works is that you would need to map to something like ...
   Mapper.CreateMap<User, ICollection<PermissionMapDto>>()

This is where you reach the limits of my knowledge with automapper, at this point I wouldn't use automapper as I don't feel it is the right tool for the job. 

You'll want a method like this ...

ICollection<PermissionMapDto> GetPermissionMappingsFor(User user, Contract contract) 
{
     var result = new List<PermissionMapDto>();

     foreach(var contractRole in Contract.Roles)
    {
          if(user.Roles.Contains(contractRole)) {
             result.Add(new PermissionMapDto{ 
                  UserId = user.Id, 
                  ContractId = contract.Id,
                  Permissions = contractRole.Permissions
             });
          }
    }
    return result;
}


There's likely some "automapper equivilent" for this but being so early on a monday morning I have not woken up enough to figure this out yet.
But i'm guessing you may need to do something funky to get it to work with the Projection stuff for ef so its queryable.

That said, my thinking is that if i just built that from a bunch of connected entities I don't see why I couldn't then further query on it using lazy loading ... this however comes with a performance warning (you may want to cache your roles and permissions at the very least), but it depends on the type of questions you want this to answer :)

**Comment by denkyira5544** [comment]
Thanks Paul, I will Implement it and let you know but so far we are on the same page. I appreciate your help

**Comment by TehWardy** [comment]
There may be, once you have it all working a cleaner implementation, I usually have a habit of looking at the propblem, getting it working but messy then going ... "hang on a minute why am i doing all that when i can just do ...", the problem is that until you get it working you won't be able to see where that can happen :8ball:

**Comment by denkyira5544** [comment]
Hi Paul
Thank you very much for your directions. I have finally got it working using AutoMapper DTOs
