### ISSUE TITLE
Materialization

### ISSUE THREAD

**Issue by jasonholloway** [AutoMapper/AutoMapper#880]
Hey, I've been fiddling away at a prototype of something which (hopefully) I can interest you in.

------------------------------

#### The Background
ProjectUsing and the QueryableExtensions are attractive. They promise the quiet satisfaction of minimizing EF's data throughput, while also eliminating the various bits of plumbing code needed to push the same data through AutoMapper. They bring closer to reality the happy vision of a slimmed-down, genericized controller that prepares models according to declarative rules.

#### The Problem
Would-be fans of ProjectUsing are immediately rebuffed by the starkness of its expectations. Or rather, EF's intolerant query-processing regime bangs its hammer and spits out exceptions at all but the most anodyne of projections, thereby scaring the inadvertent user.

Projections are forbidden from using parameterized constructors; from accessing members unknown to EF's metadata; from referring to constants of a non-primitive type; and from invoking anything but a very small subset of recognised methods. Straight property-mapping - the meat and drink of AutoMapper - works fine, as it happens, because EF has no qualms with simple member-binding on construction. But anything funkier falls foul of its proscriptive tastes.

This is sensible behaviour, of course, as by forcibly limiting queries to these hygienic standards, EF makes its own job easier to efficiently perform. 

But in doing so, it ruins AutoMapper's hopes of being an integrated data-fetching and model-preparation layer. It forms a chasm across which only very few preparatory behaviours can hop.

#### The Solution
If only there were some way to efficiently straddle this gap, with sub-projections of the overall projection distributed to either the server (EF) or the client (AutoMapper), as circumstances permitted...

If only there were some mediating agent, fitted with various cooperative strategies, that could tell the server, when faced with forbidden projections, to return tuples of the requisite data instead, with the client finishing the projection locally...

Well, would you believe it, I've been working on exactly this for the past couple of weeks. See here: https://github.com/jasonholloway/AutoMapper/tree/materialize2 (there are several new projects in the solution)

**In particular, look at the Materialize.Demo console project, which runs a full projection and prints out details of each stage (the SqlServer service needs to be running)**

-------------------------------------------------
### From the Outside In
A new extension method is made available on `IQueryable`: `MaterializeAs<TDest>()` which returns the interface `IMaterializable<TDest>` deriving from `IEnumerable<TDest>` and augmented with various extension methods corresponding to the unary methods of `Queryable`, such as `First<TDest>()`, `Last<TDest>()`, etc.

This forms the limited public wrapper of what is internally a brand new `IQueryProvider`, represented by the `Reifiable` class, which serves `ReifyQuery` queryables. As an `IQueryProvider` it is however largely unimplemented beyond simple enumeration and unary methods (and would be for the conceivable future) - hence its being hidden away from misuse.

Reifiable's implementation of `IQueryProvider.Execute()` therefore oversees the library's core operation: serving incoming queries by rewriting the `Expression` of the source query, executing this via the source `IQueryProvider`, and then appropriately transforming the returned objects to yield the requested destination types. It does this consistently by assembling an appropriate stack of `IModifier` classes, each of which performs both source-expression-rewriting and fetched-result-transformation in an ideally-balanced manner.

This is all a bit difficult to explain so I've drawn a diagram:
![Modifiers diagram](https://raw.githubusercontent.com/jasonholloway/AutoMapper/materialize2/src/Materialize/modifiers.png)
*(note that I've managed to get the mapper modifiers and other modifiers the wrong way round)*

Most of the modifier stack is formed of `MapperModifer` instances, provided by an cached structure of `IMapStrategy` classes. In aggregate, these core modifiers almost always append a new `Select` projection to the source query, and then transform whatever that projection fetches client-side.  

The structure of these modifers is determined by AutoMapper's `TypeMap` dictionary, via the behaviours of the `PropertyMapRule` and `TranslationRule` classes, which themselves create appropriate `IMapStrategy` instances (which in turn create appropriate `IModifier` instances).

I'll stop there.

-------------------------------------------------
### Progress
As things stand, it's fair to say all the core functionality is in place. There are however important parts still to tack on:
* EF-specific query proscriptions (for thorough implementation, requires testing against the metadata of the given DbContext, and therefore a hard dependency against EF) 
* Only properties needed for projections should be fetched (if detectable from expression)

Plus some standard AutoMapper behaviour is not yet integrated:
* ~~Collection-to-collection mapping~~ :sparkles:
* Custom constructors
* Before- and after-mapping hooks
* Nice handling of null properties

Nevertheless, none of these (or others unmentioned) represent significant leaps from the existing functionality.

--------------------------------------------------
### Finally
All of which above leads me to the main question: is this something that interests you, as an idea and/or as an implementation? 

I've written it so far as a dependent library, with references only to AutoMapper's existing public API. But throughout I've been secretly nurturing the hope that it might be considered for the main project.

**Comment by TylerCarlson1** [comment]
Have you looked at UseAsDataSource()?  https://github.com/AutoMapper/AutoMapper/wiki/Expression-Translation-(UseAsDataSource)

I think this is doing the same thing with translation expressions from DTOs to EF objects without exposing the EF objects.  This is mostly used for WCF OData retrieving, where you would only have access to the DTOs, but applies to general EF translation as well.

Also have #871 which is trying to expand on this functionality.  It seems to share some of the ideas you have, like before and after hooks.

**Comment by jasonholloway** [comment]
You're not wrong! Am going to have a good read of #871 now... will report back shortly.

Seems though like you're working on the other client-server boundary of AutoMapper, and we're both meeting in the middle.

**Comment by jasonholloway** [comment]
...by shortly I mean on Sunday probably :)

**Comment by jasonholloway** [comment]
My belated findings:

`AsDataSource` (as per #871) and `MaterializeAs` both want to turn AutoMapper into a pipeline. One starts from the problem of exposing an `IQueryable` of mapped objects to a client, the other from the problem of selectively dealing with an upstream server. But both meet in their overall vision, and in their shared means of achieving it:
- Serving incoming queries via `IQueryProvider`
- Generating a mapped source query expression via AutoMapper's mappings 
- Amending this same source expression to match the further clauses of the incoming query
- Executing the source query
- Post-processing the results of the source query

Both `MaterializeAs` and `AsDataSource` do all of these to differing extents of implementation. So there's overlap, without a doubt. It's the same overall problem space, with the same solutions suggesting themselves.

If I was to give one important difference in implementation, though, it would be this: `MaterializeAs` doesn't delegate to AutoMapper's existing expression-mapping mechanism. 

Instead, it fends for itself - and in so doing it has the pleasure of maintaining its own behavioural data structures (derived from AutoMapper's registered TypeMaps, of course). This means that all of its operations can be closely integrated with its central function: the mapping of an object graph. This can be convenient.

An example:
- `AsDataSource` projects into a flat local buffer, which is its opportunity to execute client-side filterings and post-processing steps. Most incoming queries can be fairly easily rewritten to map to execute on this enumerable directly, which is something of a windfall. But there are many other operations that would require more knowledge of what the buffer actually contains, object-graph-wise. And when faced with this, what have you got? An unarticulated buffer, and a foreign dictionary of TypeMaps.
- `MaterializeAs` deals with each concealed node of the local buffer as part of its holistic mapping operation (this is the transform step on `IModifier`). The shape of the object graph is immanent to each action. And of course the enumerable buffer as a whole is itself a node in the mapping - so there is no less opportunity to perform client-side linq filtering etc.

**Comment by TylerCarlson1** [comment]
That's a pretty accurate assessment of UseDataSource().  It's only the first implementation and does the bare minimum of what Automapper can do right now.  How you can expand that and to what limits are still up in the air.

As for using the same thing as IQueryableMapping, well that's because I didn't want to duplicate the code for translating queries.  They both are a means to achieve the same goal, just done through 2 different ways.  I had to write a whole bunch of robust scenarios, and there are a few new ones that have shown up and need to get fixed.  Maintaining both code sets would be a hassle.  Seeing you have written your own implementation, you know how hard expression translation can be.

**Comment by jasonholloway** [comment]
Yep, the code can get pretty messy with expressions, visitors, etc. This to me is fair reason to try and be as structured as possible in approaching the problem, to split the eventual tangle into smaller, more nicely-scoped portions - even though it's complex up front, it's more stable from that point on (or at least should be!)

I've got a question about limits, as it happens. I've got this idea (shared with @gentledepp, naturally) of servicing some query commands by projecting first to a local buffer, and then filtering/projecting/whatever from there. This is already done to compensate for EF not liking some things, but - because I've limited the outer `IQueryable` interface to functions like `First()` and `Take()` - the possibility hasn't been there of the user inadvertently dragging back an entire, expanded set of mapped data just to filter it down locally with a client-only predicate.

But if `Where()` were to be implemented, then... eek!

My plan would be to push as much filtering onto the server as possible, but there'll always be the possibility of client-only predicates being passed, and within this there'll always be the possibility of an invisible local buffer data explosion...

What to do - ban all client-only predicates? Seems harsh and disappointing.

**Comment by TylerCarlson1** [comment]
Yea I was wondering why you were inheriting from IEnumerable and not IQueryable.  UseAsDataSource inherits fom IQueryable, so it already has First, Last (EF not supported), Where, Take, OrderBy, OrderByDesc, Select, Skip, and all the other possible uses there.  No need to rewrite IQueryable's methods.
All I had to do is just translate the Expression of these Extension methods, and the lambda statements inside using a single expression mapper.  Since it's universal you can make up your own Extension Methods and they would translate accordingly, although I don't have any examples of why you would do that.  Expression mapper handles all expression types, including sub lambdas that use both the parent lambda parameter and child lambda parameter, so it has the ability to map anything and everything.

As for breaking it up or keeping it as one, I'm not sure which is better now.  Breaking it up into pieces might be better for structure, but I don't know if that will help in understanding the complexity of the problem.
For how I've been testing it to make sure everything works it's easy to debug and keep track of position since it's in one file.  Some scenarios cover a combination of multiple types of mappings and not switching files is helpful.  Sub-lambdas are one thing that helps keeping one file because there is a 2 pass system of parameter mappings that needs to be done.  Ex: `parentDto => parentDto.Children.Where(childDto => childDto.LastName == parentDto.LastName)`

As for client side predicates yes you will have blowups no matter what.  Even without automapper you will have that and will blow up or not run as SQL code and be slow.  Don't know if you can really reliably handle all of that, I could be wrong.  As for post client-side predicates you can always have the option for `ToList().Where(codeExecutedPredicate);` or whatever you may want.

I think the next big thing in #871 is updating the items like a Before Map or After Map does.  Maybe just After Map is possible.  Problem with UseAsDataSource is `Select` as now the result type is not what you expect.

**Comment by gentledepp** [comment]
As for the "Select" problem, I recently had the following idea:
If the resulting type is not TDto but some anonymous object that was created because of a Select-Expression, the following could be done (pseudo code)
<pre>
if(isNotOfTypeTDto && enumerationHandlerPresent){
    // convert each anonymous object to a TDto
    // call the enumeration handler (possibly with a list of properties present in the anonymous object, so in your handler, you could skip setting additional properties in case they are not even queried for)
    // convert the TDtos back to anonymous objects
}
</pre>

That would be kind of a typesafe solution for this problem. Wouldn't it?

Also, one of my colleagues was pretty excited about that feature. He only mentioned that he'd prefer to register such a handler globally using 
<pre>
Mapper.CreateMap<TEntity, TDto>(x => x.OnEnumerated(handler))
</pre>
as registering it separately on every call to AsDataSource() would be too much of a hassle for him

**Comment by TylerCarlson1** [comment]
Another option is if you do after map and make it pass in an expression, you might be able to translate using a new ExpressionVisitor to apply settings to the dto, and possibly translate that over to the anon type.  That way there's no need to covert to dto and back.  Maybe one for individual item and one for the entire enumeration.  That way you can run it against dto's and if not dto's you can translate the actions from the DTO and see if they apply to the anon type in the select statement

**Comment by jasonholloway** [comment]
Hey, I am still working on this, despite appearances... sorry for having disappeared

**Comment by jbogard** [comment]
Going to close this for now, until the PRs are all sorted.
