### ISSUE TITLE
Change automapper to not use global state(please)

### ISSUE THREAD

**Issue by jannickj** [AutoMapper/AutoMapper#903]
So much time spent on this library and it is completely useless because of this.

**Comment by jbogard** [comment]
Elaborate? There's never been a restriction to have AutoMapper be static.
The Mapper class is a small shim on top of instances.

**Comment by jannickj** [comment]
The way the documentation is explaining use I need to do

   AutoMapper.Mapper.CreateMap<A, B>(); <-- Global state saving maps
   B b = AutoMapper.Mapper.Map<A, B>(A: a); <-- this is no longer testable and is very fragile.

If there is non-global state based way to use it I think it should be first in the documentation.

**Comment by jbogard** [comment]
The reason for global state is that it's fine for 99.99% of use cases. It's how we use it on all of our projects. I'm not sure what isn't testable, we have AutoMapper going in all of our tests just fine. We don't mock it of course, that would be a waste of time. I did quite a bit of work (well not me, someone with a PR) to un-globalize AutoMapper in 3.0. So the only global state is in Mapper, otherwise you can just use instance methods.

It's not documented because no one has contributed the documentation on the wiki. I don't put it as the first use case because I don't think it *should* be the first use case. What specifically is not testable and what is fragile?

**Comment by jannickj** [comment]
Anything that is global state is inherently fragile because any change anywhere in the code and have a huge impact.

> The reason for global state is that it's fine for 99.99% of use cases

Even if I accepted this premise then why excluse 0.01%?

But don't take my words for why you shouldn't use global state:
http://programmers.stackexchange.com/questions/148108/why-is-global-state-so-evil

**Comment by jbogard** [comment]
Specifically, what issues are YOU having? I ask because I've used
AutoMapper for going on 8 years without issues of static instances. And
that 0.01% is not excluded, you can certainly use AutoMapper without the
static class, I just don't know why you would, what specific problems are
you seeing? What has been fragile, what broke in your application because
AutoMapper is using two static fields?

**Comment by adam-resdiary** [comment]
I don't know if this is any use, but what we do is wrap AutoMapper with an interface to make it easier to unit test code that uses AutoMapper, without actually relying on the mappings. So something like this:

```csharp
public interface IMapper<A, B>
{
    A Map(B source);
    B Map(A source);
    ...
}

public class MapperBase<A, B> : IMapper<A, B>
{
    public A Map(B source)
    {
        return Mapper.Map<A>(source);
    }
    ...
}
```

Then in our unit tests, we can just do stuff like:

```csharp
[Test]
public void Test()
{
    var personMapper = new Mock<IMapper<Person, PersonDto>>();
    
    var person = new Person();
    var personDto = new PersonDto();

    personMapper.Setup(m => m.Map(person)).Returns(personDto);

    ...
}
```

And our IoC container just automatically wires up IMappers using MapperBase, so we don't have to explicitly provide implementations for every type of mapper we want.

It just means we can keep the tests really simple by not actually caring about the data or the mapping, and we can test our mappings separate to the code that uses them.

Like @jbogard says - we've never had any issues with the fact that AutoMapper uses static fields, although it would have been handy if there was an IMapper interface available out the box so we didn't have to wrap it ourselves (apologies if there is something like this that we've just missed).

Cheers,
Adam

**Comment by jbogard** [comment]
@adam-resdiary The IMappingEngine interface exists OOTB.
