### ISSUE TITLE
Mapping to proxy instead of configured concrete type

### ISSUE THREAD

**Issue by texavery77** [AutoMapper/AutoMapper#926]
Hello,
I noticed an unexpected mapping using nested properties of interface type with two different implementing types that need to be mapped. Automapper 4.0.4 shows different behavior than Automapper 3.3.1, which behaves as expected and according to documentation.

See following comment as example:

**Comment by texavery77** [comment]
Example program, which fails (leaving out actual class/interface definitions, which are rather obvious):

static void Main(string[] args)
        {
            Mapper.CreateMap<Customer, CustomerData>();          
            Mapper.CreateMap<Address, IAddress>().As<AddressData>();
            Mapper.AssertConfigurationIsValid();

            var customer = new Customer()
            {
                Name = "John Doe",
                Address = new Address()
                {
                    City = "Hamburg",
                    Street = "Fishstreet 999",
                    Zipcode = 20409
                },

                Addresses = new List<IAddress>()
                {
                    new Address()
                {
                    City = "Hamburg",
                    Street = "Fishstreet 999",
                    Zipcode = 20409
                },
                new Address()
                {
                    City = "Hamburg",
                    Street = "Fishstreet 999",
                    Zipcode = 20409
                },
                
                }
            };

            var c2 = Mapper.Map<CustomerData>(customer);

            // Both fail in AutoMapper 4.0.4, but not on 3.x
            Debug.Assert(c2.Address is AddressData);
            Debug.Assert(c2.Addresses.First() is AddressData);

**Comment by lbargaoanu** [comment]
Please make a gist with a complete example.

**Comment by TylerCarlson1** [comment]
MyGet has latest build and should fix this inheritance issue.
https://www.myget.org/F/automapperdev/api/v2

**Comment by lbargaoanu** [comment]
Actually it still fails.

**Comment by lbargaoanu** [comment]
[This](https://github.com/AutoMapper/AutoMapper/blob/0ff92f9b57e84f8749ed929388f6f2f6fc1f81e3/src/UnitTests/MappingInheritance/ShouldSupportOnlyDestinationTypeBeingDerived.cs#L41) test seems weird to me. Create a map to CustomerStubDTO, no Name propery, but override with CustomerDTO which has Name and then assert that you map also the Name. And the reason I stumbled into this test is because is the only one that fails if I implement As simply by replacing the destination type with the override (so removing [this](https://github.com/AutoMapper/AutoMapper/blob/0ff92f9b57e84f8749ed929388f6f2f6fc1f81e3/src/AutoMapper/ConfigurationStore.cs#L175) if).

**Comment by TylerCarlson1** [comment]
As and Included share a lot of similarities, but have two very different implementations.  They both override the type map used, and they both need to be sealed before they are able to be used to override the type map.  As of right now when you use a map you seal the type map and all that are included, but you don't seal the DestinationTypeOverride, which is what As sets.  That's why it works when it's in mapper.initialize and not out of.  And why Includes work outside of initialize as well.

The possibly reason for the test in question, is not only does it override the type that was mapped to, but also used the overridden TypeMap itself, which would include the Name map.

**Comment by lbargaoanu** [comment]
All I want to say is that the test in question doesn't seem like a compelling scenario to me and getting rid of it would allow removing some code from the whole "find the right TypeMap" business. This is complicated code and causes quite a few issues. One strategy to simplify it is to choose which corner cases we want to support.

**Comment by jbogard** [comment]
The point of As was to redirect the type map, honestly I'm not sure it's really needed at this point?

**Comment by TylerCarlson1** [comment]
Would it make sense to make `CreateMap<T,TDto>().As<TDto2>()`
just a shortcut for `CreateMap<T,TDto>().Include<T,TDto2>()` and get the same effect?

Honestly when I first learning about it, this was my assumption of what As was doing.

**Comment by lbargaoanu** [comment]
I know we didn't agree to anything, but that's what I have now. I guess this would change the meaning of As to simply replacing the destination type. If we agree, then I can delete the failing test.

**Comment by lbargaoanu** [comment]
@TylerCarlson1 Apparently As is not exactly Include. I've tried the idea but got nowhere.

**Comment by lbargaoanu** [comment]
In this version of the code, the problem test passed when I replaced As with Include. Which kind of makes sense :) It needed to override the type map, not just the destination type. Anyway... :)

**Comment by jbogard** [comment]
@lbargaoanu is the PR good then?

**Comment by lbargaoanu** [comment]
Yes :)

**Comment by jbogard** [comment]
OK, reviewing this PR, merging it and changing my mind, this worked *accidentally* originally. As is intended to redirect from one type map to another. The second type map does not exist. You either need to create a map to the correct type, or use ConstructUsing.

**Comment by lbargaoanu** [comment]
OK, but back to your original point. Can't we get rid of As or at least implement it in terms of Include?

**Comment by jbogard** [comment]
The problem is that they provide different functionality. With Include, you're getting a superset of configuration. A -> B and A' -> B', you get all config from A and A'. With As, A -> B and A -> B', you're forwarding the resolution to A -> B, so it's as if the original type map from A -> B' never existed. The above example was not the intended behavior of As, though.

**Comment by lbargaoanu** [comment]
If you put it like this, it makes sense :) But that code still looks scary. I guess we'll know it's right when people stop complaining.

**Comment by jbogard** [comment]
Which code? The type map cache calculation? Yeah that one isn't as straightforward as I liked. But at least the ResolveTypeMap stuff got *way* simpler, it just checks your base types.
